### ISSUE TITLE
Support push using ssh

### ISSUE THREAD

**Issue by proudust** [peter-evans/create-pull-request#103]
To get around #48, would be great if create-pull-request could support push using ssh.
It is more secure than using a personal token because it can be set for each repository.

**Comment by peter-evans** [comment]
Interesting idea. This would only work to trigger checks run in `on: push` workflows though. Checks run in `on: pull_request` workflows would still not fire because a GitHub auth token will be needed to create the PR.

I will do some research and think about how to support this feature.

**Comment by peter-evans** [comment]
@proudust I don't see options in GitHub for scoping an SSH key to a specific repository. SSH keys set [here](https://github.com/settings/keys) are tied to an account and so can be used to access all repositories. Is there something I'm missing?

**Comment by proudust** [comment]
@peter-evans Try using [Deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys).

**Comment by peter-evans** [comment]
What I've decided to do is make sure the action will work when a repository is checked out via SSH. I don't think handling the SSH key itself should be the responsibility of this action.

How to use SSH (deploy keys) with create-pull-request action:
1. [Create an new SSH key pair](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) for your repository
2. Add the contents of the public (.pub) file to a new repository [Deploy Key](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) and check the box to "Allow write access."
3. Add a secret to the repository containing the entire contents of the private key.
4. As shown in the partial workflow below, use the [`webfactory/ssh-agent`](webfactory/ssh-agent) action to install the key and clone your repository. Remember to checkout the `base` of your pull request if it's not the default branch, e.g. `git checkout my-branch`.

```
    steps:
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout via SSH
        run: git clone git@github.com:peter-evans/create-pull-request.git .

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
