### ISSUE TITLE
Issue about .gitignore

### ISSUE THREAD

**Issue by carmoreno1** [peter-evans/create-pull-request#1030]
### Issue with `.gitignore`

First of all, thank you for this amazing action, It has been helpful to me. Right now I'm facing an issue regarding the files sent to a pull request. There are folders named `__pychace__` that I want to ignore but it has been impossible. I tried to use the `add-path` attribute too

### My .yml file
```yml
name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  Run-migrations:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.CARLOS_PERSONAL_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install python deps
        run: pip install -r requirements.txt

      - name: set redshift credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: .github/set-redshift-credentials.sh

      # Configuring flayway action with the env variables added in the previous step.

      - uses: joshuaavalon/flyway-action@v1
        with:
          url: jdbc:redshift://${{ env.DW_HOST }}:${{ env.DW_PORT }}/${{ env.DW_DATABASE }}
          user: ${{ env.DW_USER }}
          password: ${{ env.DW_PASSWORD }}
          locations: filesystem:./sql/migrations

      - name: Create branch and move the migrations to the correct location
        run: .github/create-branch-migrations.sh

      - name: Create bump pull request
        uses: peter-evans/create-pull-request@v3.5.1
        with:
          token: '${{ secrets.CARLOS_PERSONAL_TOKEN }}'
          commit-message: 'Chore: Moving migrations to the correct location'
          title: 'Chore(bump): Move migrations to the correct location'
          branch: ${{ env.MIGRATION_BRANCH }}
          add-paths: sql/
```
My .gitignore has this line:

`**/__pycache__/`

I mentioned that I try to use the add-path attribute, this was the output:

`Warning: Unexpected input(s) 'add-paths', valid inputs are ['token', 'path', 'commit-message', 'committer', 'author', 'signoff', 'branch', 'delete-branch', 'branch-suffix', 'base', 'push-to-fork', 'title', 'body', 'labels', 'assignees', 'reviewers', 'team-reviewers', 'milestone', 'draft']
`
