### ISSUE TITLE
🐛 bug: creates PR on upstream repo AND fork

### ISSUE THREAD

**Issue by ericis** [peter-evans/create-pull-request#1031]
### Creates PR on upstream repo AND fork

@peter-evans, Our project's workflow is generating two pull requests; one for the [upstream repository](https://github.com/ourchitecture/hello-cloud/pull/163) and another for the [forked repository](https://github.com/ericis/hello-cloud/pull/9). We only want the upstream repo PR and not the forked PR. I've attempted to apply the guidance for ["Restrictions on repository forks"](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks), but the workflow completely [skipped the pull request entirely](https://github.com/ourchitecture/hello-cloud/runs/4731223966?check_suite_focus=true).

![image](https://user-images.githubusercontent.com/974919/148464180-909b7033-e7fc-4680-bdc5-009e554b99cb.png)

### Steps to reproduce

The workflow used in this process is located here:
https://github.com/ourchitecture/hello-cloud/blob/cb1ba484a066278342029bd97181f7c7a01025f7/.github/workflows/documentation.yml#L31-L44

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        # only:
        # - push, not pr
        # - primary repo, not forks
        if: ${{ github.event_name == 'push' && github.event.push.head.repo.full_name == github.repository }}
        with:
          title: "docs: auto-generated documentation"
          signoff: true
          commit-message: "docs: auto-generated documentation [skip ci]"
          body: "Automatically generated documentation that requires a PR, because the main branch is protected."
          labels: "documentation"
          reviewers: "ericis"
          assignees: "ericis"
```

The process that leads to this bug is documented in the sequence diagram below.

[![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgTSBhcyBNYWludGFpbmVyXG4gICAgcGFydGljaXBhbnQgQyBhcyBDb250cmlidXRvclxuICAgIHBhcnRpY2lwYW50IEYgYXMgUmVwb3NpdG9yeSBGb3JrXG4gICAgcGFydGljaXBhbnQgUiBhcyBSZXBvc2l0b3J5XG4gICAgcGFydGljaXBhbnQgR0hBIGFzIEdpdEh1YiBBY3Rpb25zXG4gICAgcGFydGljaXBhbnQgQ1BSIGFzIHBldGVyLWV2YW5zL2NyZWF0ZS1wdWxsLXJlcXVlc3RcbiAgICBwYXJ0aWNpcGFudCBHSFBhZ2VzIGFzIEdpdEh1YiBQYWdlc1xuXG4gICAgQy0-PkY6IFB1c2ggZmVhdHVyZSBicmFuY2ggY2hhbmdlc1xuICAgIEMtPj5SOiBTdWJtaXQgUFJcbiAgICBNLT4-UjogUmV2aWV3LCBhcHByb3ZlIGFuZCBtZXJnZSBjb250cmlidXRvciBQUlxuICAgIEYtLT4-UjogTWVyZ2UgZmVhdHVyZSBicmFuY2ggdG8gbWFpblxuICAgIFItLT4-R0hBOiBCdWlsZCBvZmZpY2lhbCBkb2N1bWVudGF0aW9uXG4gICAgR0hBLS0-PkNQUjogR2VuZXJhdGUgYSBQUlxuICAgIENQUi0-PlI6IEdlbmVyYXRlIGEgUFJcbiAgICByZWN0IHJnYig5MCwgNjAsIDYwKVxuICAgIENQUi0-PkY6IEdlbmVyYXRlIGEgUFJcbiAgICBOb3RlIHJpZ2h0IG9mIEY6IOKaoO-4jyBDb250cmlidXRvcnMgbXVzdCBpZ25vcmU8YnI-YW5kIGNsb3NlIHRoaXMgUFIhIE1lcmdpbmc8YnI-aXQgYmFjayB0byB0aGUgZm9yaydzIFwibWFpblwiPGJyPmJyYW5jaCB3aWxsIHJlc3VsdCBpbiBtZXJnZTxicj5jb25mbGljdHMgYW5kIGNoYWxsZW5nZXMgc3luY2luZzxicj53aXRoIHRoZSBvcmlnaW5hbCBSZXBvc2l0b3J5LlxuICAgIGVuZFxuICAgIE0tPj5SOiBSZXZpZXcsIGFwcHJvdmUgYW5kIG1lcmdlIGRvY3VtZW50YXRpb24gUFJcbiAgICBHSEEtPj5HSFBhZ2VzOiBCdWlsZCBhbmQgcHVibGlzaCBHaXRIdWIgUGFnZXNcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkYXJrIn0sInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)](https://mermaid.live/edit/#eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgTSBhcyBNYWludGFpbmVyXG4gICAgcGFydGljaXBhbnQgQyBhcyBDb250cmlidXRvclxuICAgIHBhcnRpY2lwYW50IEYgYXMgUmVwb3NpdG9yeSBGb3JrXG4gICAgcGFydGljaXBhbnQgUiBhcyBSZXBvc2l0b3J5XG4gICAgcGFydGljaXBhbnQgR0hBIGFzIEdpdEh1YiBBY3Rpb25zXG4gICAgcGFydGljaXBhbnQgQ1BSIGFzIHBldGVyLWV2YW5zL2NyZWF0ZS1wdWxsLXJlcXVlc3RcbiAgICBwYXJ0aWNpcGFudCBHSFBhZ2VzIGFzIEdpdEh1YiBQYWdlc1xuXG4gICAgQy0-PkY6IFB1c2ggZmVhdHVyZSBicmFuY2ggY2hhbmdlc1xuICAgIEMtPj5SOiBTdWJtaXQgUFJcbiAgICBNLT4-UjogUmV2aWV3LCBhcHByb3ZlIGFuZCBtZXJnZSBjb250cmlidXRvciBQUlxuICAgIEYtLT4-UjogTWVyZ2UgZmVhdHVyZSBicmFuY2ggdG8gbWFpblxuICAgIFItLT4-R0hBOiBCdWlsZCBvZmZpY2lhbCBkb2N1bWVudGF0aW9uXG4gICAgR0hBLS0-PkNQUjogR2VuZXJhdGUgYSBQUlxuICAgIENQUi0-PlI6IEdlbmVyYXRlIGEgUFJcbiAgICByZWN0IHJnYig5MCwgNjAsIDYwKVxuICAgIENQUi0-PkY6IEdlbmVyYXRlIGEgUFJcbiAgICBOb3RlIHJpZ2h0IG9mIEY6IOKaoO-4jyBDb250cmlidXRvcnMgbXVzdCBpZ25vcmU8YnI-YW5kIGNsb3NlIHRoaXMgUFIhIE1lcmdpbmc8YnI-aXQgYmFjayB0byB0aGUgZm9yaydzIFwibWFpblwiPGJyPmJyYW5jaCB3aWxsIHJlc3VsdCBpbiBtZXJnZTxicj5jb25mbGljdHMgYW5kIGNoYWxsZW5nZXMgc3luY2luZzxicj53aXRoIHRoZSBvcmlnaW5hbCBSZXBvc2l0b3J5LlxuICAgIGVuZFxuICAgIE0tPj5SOiBSZXZpZXcsIGFwcHJvdmUgYW5kIG1lcmdlIGRvY3VtZW50YXRpb24gUFJcbiAgICBHSEEtPj5HSFBhZ2VzOiBCdWlsZCBhbmQgcHVibGlzaCBHaXRIdWIgUGFnZXNcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkYXJrXCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)
