### ISSUE TITLE
How to use env variables inside fields?

### ISSUE THREAD

**Issue by Vyom-Yadav** [peter-evans/create-pull-request#1036]
Hi,
I just started using your action and I have a simple problem. I have a simple script-
```YAML
- name: Current Year
        id: CURRENT_YEAR
        run: |
          echo "::set-output name=year::$(date +'%Y')"
- name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          year: ${{ steps.CURRENT_YEAR.outputs.year }}
        with:
          commit-message: "${year}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: bump-year
          delete-branch: true
          body: '$year'
          title: ${year}
```
I am not able to set the value of `body`, `title` etc. to the environment variable, it keeps displaying text instead of value. Though I am able to retrieve `$year` in other steps of my file barring above mentioned fields, I am fairly new, any help will be appreciated.
