### ISSUE TITLE
problem with actions which should react on pull_request to base branch

### ISSUE THREAD

**Issue by SebastianBakala-TomTom** [peter-evans/create-pull-request#1037]
### Subject of the issue

Hi.
I'm expieriencing a strange issue.
When I'm using your action

```yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            xyz/*
          commit-message: pr
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[Automated] yada yada yada'
          body: |
            Update report
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
```

the other action which should be triggered when pull request to specific branch is created
```yaml
on:
  pull_request:
    branches:
      - dev
```

doesn't start, but it's an aciton which is a required check by any pull request.

### Steps to reproduce

I cannot share my action with you - it's enterprise repo, so I've pasted some snippets.

I'll be glad for any help.

Regards,
 SB
