### ISSUE TITLE
PR doesn't trigger other workflows using PAT

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [peter-evans/create-pull-request#1060]
I have set a personal token that has `repo` and `workflow` scopes but when the PR is created, the PR workflow is not triggered.

Renovate GitHub Action which creates a pull request is triggering the PR workflows using a token with the same scopes.

```yaml
- name: Create Pull Request
  uses: peter-evans/create-pull-request@v3.12.1
  with:
    token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    committer: GitHub Action<action@github.com>
    branch: 'rc/${{ steps.create-jira-task.outputs.issue }}'
    delete-branch: true
    title: 'RC ${{ steps.create-jira-task.outputs.issue }}'
    body: |
      Changelog:
      ${{ env.CHANGELOG}}
    team-reviewers: |
      android
    labels: |
      version-${{ github.event.inputs.scope }}
```
