### ISSUE TITLE
Destination branch

### ISSUE THREAD

**Issue by mrkpatchaa-sf** [peter-evans/create-pull-request#1072]
### Destination branch option

Hi, is it possible to have a destination branch option?
Let's say I'm creating a release from `develop` -> `release/v123` and want the PR to be created for `main`, instead of the base (`develop`).

**Comment by peter-evans** [comment]
Hi @mrkpatchaa-sf 

The "destination" branch is referred to as the `base` of a pull request. The action determines the `base` from the locally checked out branch name. So as long as you have checked out `main` locally, that will be the target `base` of the pull request.

I recommend reading this part of the docs for an explanation:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#events-and-checkout

There are situations when for some reason it's not easy to checkout the branch you want as the `base` first, before applying the changes and running the action. In those rare situations, you can use the `base` input to set the target branch. The action will then "rebase" your changes onto this branch before creating the pull request.

**Comment by AfroDevGirl** [comment]
@peter-evans I'm a little confused on the expected functionality. Like @mrkpatchaa-sf I'm creating a release from `develop`, which is the default branch in the repo, and I want the PR to be compared to the `main` branch. But when the action executes pull requests aren't being created.

Here is the step output:
```
Pull request branch target repository set to serendipity-in-software/camp-social
Configuring credential for HTTPS authentication
Checking the base repository state
Pull request branch to create or update set to 'release/1'
Configuring the committer and author
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  release/1
  Working base is branch 'release/1'
  /usr/bin/git checkout --progress -B 7f776d5d-f9d0-44[19](https://github.com/serendipity-in-software/camp-social/runs/5456620723?check_suite_focus=true#step:4:19)-8e90-77fc7e65a[32](https://github.com/serendipity-in-software/camp-social/runs/5456620723?check_suite_focus=true#step:4:32)0 HEAD --
  Switched to a new branch '7f776d5d-f9d0-4[41](https://github.com/serendipity-in-software/camp-social/runs/5456620723?check_suite_focus=true#step:4:41)9-8e90-77fc7e65a320'
  /usr/bin/git status --porcelain -unormal
  /usr/bin/git diff --quiet
  /usr/bin/git diff --quiet --staged
  Resetting working base branch 'release/1'
  /usr/bin/git checkout --progress release/1 --
  Switched to branch 'release/1'
  Your branch is up to date with 'origin/release/1'.
  /usr/bin/git reset --hard origin/release/1
  HEAD is now at 5a99788 Remove checkout argument
  Rebasing commits made to branch 'release/1' on to base branch 'main'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin main:main
  Resolving deltas: 100% (18020/18020), completed with 361 local objects.
  From https://github.com/serendipity-in-software/camp-social
   * [new branch]        main       -> main
   * [new branch]        main       -> origin/main
  /usr/bin/git checkout --progress main --
  Switched to branch 'main'
  /usr/bin/git rev-list --reverse release/1..7f776d5d-f9d0-4419-8e90-77fc7e65a320 .
  /usr/bin/git checkout --progress -B 7f776d5d-f9d0-4419-8e90-77fc7e65a320 HEAD --
  Switched to and reset branch '7f776d5d-f9d0-4419-8e90-77fc7e65a320'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin main:main
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules origin release/1:refs/remotes/origin/release/1
  Pull request branch 'release/1' already exists as remote branch 'origin/release/1'
  /usr/bin/git checkout --progress release/1 --
  Switched to branch 'release/1'
  Your branch is up to date with 'origin/release/1'.
  /usr/bin/git diff --quiet release/1..7f776d5d-f9d0-4419-8e90-77fc7e65a320
  Resetting 'release/1'
  /usr/bin/git checkout --progress -B release/1 7f776d5d-f9d0-4419-8e90-77fc7e65a320 --
  Reset branch 'release/1'
  Your branch is behind 'origin/release/1' by 7 commits, and can be fast-forwarded.
    (use "git pull" to update your local branch)
  /usr/bin/git rev-list --right-only --count origin/release/1...release/1
  0
  /usr/bin/git rev-list --left-only --count origin/release/1...release/1
  7
  Updated branch 'release/1'
  /usr/bin/git rev-list --right-only --count main...release/1
  0
  /usr/bin/git rev-parse HEAD
  005967f6746e74b8867eeff3f607024e20d79008
  /usr/bin/git branch --delete --force 7f776d5d-f9d0-4419-8e90-77fc7e65a320
  Deleted branch 7f776d5d-f9d0-4419-8e90-77fc7e65a320 (was 005967f6).
Pushing pull request branch to 'origin/release/1'
Branch 'release/1' no longer differs from base branch 'main'
Deleting branch 'release/1'
/usr/bin/git push --delete --force origin refs/heads/release/1
To https://github.com/serendipity-in-software/camp-social
 - [deleted]           release/1
```

And this is my workflow yml:
```
steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set ENV Vars
        id: env
        run: |
          echo ::set-output name=branch_name::$(git branch --show-current)
          echo ::set-output name=commits::$(git log --left-right --graph --cherry-pick --oneline main...$(git branch --show-current))
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.env.outputs.branch_name }}
          title: Deploy ${{ steps.env.outputs.branch_name }} to production
          body: |
            Commits in this release candidate:
            ${{ steps.env.outputs.commits }}
          labels: release-candidate
          delete-branch: true
          base: main
```

It seems to me that a new branch (`main`) is being created when the origin main already exists, but that's just a rough guess. Any thoughts on what could be going on here?
