### ISSUE TITLE
Use case: keeping a branch up-to-date with another

### ISSUE THREAD

**Issue by thisismydesign** [peter-evans/create-pull-request#108]
Great project, thanks. I was wondering if it can fulfill the use case of keeping a branch up-to-date with another (without adding new commits or branches). Along the lines of https://github.com/repo-sync/pull-request but I found your project much more advanced so I'd prefer to use it. AFAICT this boils down to a small feature request, but I'd explain my use case just to make sure.

Ideally, I'd like the following:
- upon new commits in a base branch (e.g. `master`) there's a PR opened to target branches (e.g. `staging`, `production`)
- there's a single automated PR from base to a target branch
- if the target branch is updated, this PR is kept up-to-date (e.g. closed)
- there can be any number of manually created PRs between the base and deploy branches that will not be affected

I think in theory this could work. In my example, I'd run this action on `master`, set the PR base (`base`) to my production branch. The concern/request I have is the ability to set `branch` to `master` using Strategy A but make it so that it's not deleted, even after merging the PR.
> If subsequent changes cause the branch to no longer differ from the base the pull request will be automatically closed and the branch deleted.

In the default context, it makes sense to delete a merged PR's branch. I can see 2 ways my use case could be supported:
- if `branch` wasn't created by this action, it should not be deleted by default
- an optional input to not delete the branch

**Comment by peter-evans** [comment]
@thisismydesign Thank you for sharing your use case. This is a really interesting one and had me scratching my head for a while to figure out if this was possible with create-pull-request action. I think I've got a solution that works well.

This workflow works by allowing the action to create a branch called `production-promotion` that is continually updated on push to `master`. The PR is created from `production-promotion` to `production`. If the PR is closed and the branch deleted, it will just be recreated next time there are new changes to master.
```
name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production-promotion
```
Let me know what you think and if it fits your use case.
