### ISSUE TITLE
Use a .md template for body

### ISSUE THREAD

**Issue by kenzie-rasmussen** [peter-evans/create-pull-request#1086]
Hello!

Some of the PRs that I will be making require more substantial documentation and summaries. I'd like to be able to create a template.md file and have the PR action import that template as the summary instead of listing inline documentation.

Please let me know if this is feasible!

As an example, this action provides that feature using the input pr_template: https://github.com/marketplace/actions/github-pull-request-action. (peter-evans/create-pull-request provides essential functionality, so I do not wish to switch to this action. It's simply an example of a implemented feature)

**Comment by peter-evans** [comment]
Hi @kenzie-rasmussen 

Rather than add templating functionality to the action I would like to recommend using [render-template](https://github.com/chuhlomin/render-template) in a separate workflow step.

There is an example here of how to use it:
https://github.com/peter-evans/create-or-update-comment#using-a-markdown-template

**Comment by tooomm** [comment]
> Rather than add templating functionality to the action I would like to recommend using [render-template](https://github.com/chuhlomin/render-template) in a separate workflow step.

Hello Peter, I came to your repo to request a very similar use case.
We are currently using the mentioned "render-template" action that you suggested back then.

However, it's a "Docker action" which does not run on macOS and Windows as noted in their README.
Also, the new `ubuntu-slim` runner designed exactly for simpler automation tasks has [no "Docker in Docker" support](https://docs.github.com/en/actions/reference/runners/github-hosted-runners#single-cpu-runners). We started to use the slim runner and ran into errors because the render-template action can not be downloaded at the beginning of the job in which we want to create a PR.

It would already help for simple cases if users can link to a .md file for `body` and use the static text from the file to have a cleaner "source" and workflow file, and more easily manage larger body contents.
Same might be helpful for commit-message where text could also be a bit more comprehensive compared to the other inputs.

Instead:
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated pr
```

<br>

It could be:
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: '[Example] Update report'
          body: ./ci_templates/report_template.md
          labels: automated pr
```

With the `report_template.md` file containing the former text
```
Update report
- Updated with *today's* date
- Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request
```

If needed, users can build logic and update the file content dynamically before consumption.

<br>

Edit:
I see now that file input was also requested already, and you commented in https://github.com/peter-evans/create-pull-request/issues/1098#issuecomment-1073203417.
