### ISSUE TITLE
Not able to create PR after pushing the branch

### ISSUE THREAD

**Issue by ducretje-evooq** [peter-evans/create-pull-request#1096]
### No PR is created after successfully pushing the branch

When running this action, the new branch is pushed, but the action fail on `Attempting creation of pull request` with the following error:
`::error::Not Found`

### Steps to reproduce

The repo is private, I can't give you the link, but here is the workflow

```yaml
name: "TEST"

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow to manually trigger the pipeline
  push:
    branches:
      - main

jobs:
  nuke:
    runs-on: ubuntu-20.04
    name: "TEST"
    strategy:
      matrix:
        name: ["test"]

    steps:
      - name: Set ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.INFRA_GHA }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Hide ${{ matrix.name }}-dev.tf
        id: hide
        run: mv ${{ matrix.name }}-dev.tf ${{ matrix.name }}-dev.tf.hidden
        working-directory: ./test-infra/${{ matrix.name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          signoff: false
          committer: me <me@example.com>
          author:  me <me@example.com>
          delete-branch: true
          branch: beep_boop
          title: '[Phoenix] Nuke'
          body: |
            ${{ matrix.name }}-dev destruction
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: |
            alpha
          draft: true
```

I saw it's not the first time this is happening but I'm not sure it has been solved.
https://github.com/peter-evans/create-pull-request/issues/634

I never made it work, and there are no Github issue ongoing at this time.

I also tried to remove all the options, and just use

```yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

But I got the same results.

**Comment by peter-evans** [comment]
Hi @ducretje-evooq 

Does this happen consistently when you run the workflow, or is it just occasionally?
If it's happening consistently then there must be something wrong permissions-wise I think.

What is this step doing? It doesn't look like it's doing anything useful in the workflow.
```
      - name: Set ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.INFRA_GHA }}
```

If possible, please provide the full run log.
