### ISSUE TITLE
Pull request body mangles bash output

### ISSUE THREAD

**Issue by NotMyFault** [peter-evans/create-pull-request#1115]
Heyo,

I have a bash script that logs what it is doing. This output I'd like to use as comment in the PR body.
This is my current workflow setup:
```yaml
name: Update since annotation
on:
  release:
    types: [published]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run update-since-todo.sh
      run: echo ::set-output name=PROGRESS::$(./update-since-todo.sh)
      id: run_script
      shell: bash
    - name: Get the newest tag
      id: get_tag
      run: echo ::set-output name=NEWEST_TAG::${GITHUB_REF/refs\/tags\//}  
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update `@since TODO` annotations from ${{ steps.get_tag.outputs.NEWEST_TAG }} 
        title: Update `@since TODO` annotations
        body: |
          This is an automatic pull request that updates `@since TODO` annotations matching the appropriate GitHub tag.
          ${{ steps.run_script.outputs.PROGRESS }}
        branch: chore/master/update-since-todo
        base: master
        labels: chore
        delete-branch: true
```
The workflow creates a PR fine and proposes the changes properly, however, the actual file output is mangled. It displays the following as PR description:
![](https://i.imgur.com/HcKlyK2.png)
when the actual console output shown at the GitHub workflow uses proper formatting:
![](https://i.imgur.com/HrvIjuu.png)

Am I doing something wrong? The PR body should use the same formatting like the console output, but it appears it omits formatting at all.

For reference, the script can be obtained here: https://github.com/jenkinsci/jenkins/blob/master/update-since-todo.sh

Thanks in advance!
