### ISSUE TITLE
Branch Being Deleted - PR Not Creating During Build 

### ISSUE THREAD

**Issue by jcquiles** [peter-evans/create-pull-request#1148]
Hey @peter-evans I seem to be missing something when automatically merging one branch to another. 

- Currently the workflow **runs** but there isnt a PR being created. My base branch (**react-qa**) changes to a different branch (**deploy-qa**), and then deletes because im assuming it falls into the rule of **If a pull request already exists and there are no further changes (i.e. no diff with the current pull request branch) then the action exits silently.** However im not sure why?
- I was hoping you could lend me some insight on what I could missing here, or what I could add in my build to prevent this. 
- Here is the workflow and some things I noticed in the build.

```
  Switched to branch 'react-qa'
  /usr/bin/git rev-list --reverse deploy-qa..a4bb32dc-11e4-46b8-9b70-a4b473176fff .
  /usr/bin/git checkout --progress -B a4bb32dc-11e4-46b8-9b70-a4b473176fff HEAD --
  Switched to and reset branch 'a4bb32dc-11e4-46b8-9b70-a4b473176fff'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin react-qa:react-qa
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules origin deploy-qa:refs/remotes/origin/deploy-qa
  Pull request branch 'deploy-qa' already exists as remote branch 'origin/deploy-qa'
  /usr/bin/git checkout --progress deploy-qa --
  Switched to branch 'deploy-qa'
```
```
Pull request branch to create or update set to 'deploy-qa'
Configuring the committer and author
  Configured git committer as 'GitHub <noreply@github.com>'
  Configured git author as 'trugr <trugr@users.noreply.github.com>'
Create or update the pull request branch
Branch 'deploy-qa' no longer differs from base branch 'react-qa'
Deleting branch 'deploy-qa'
/usr/bin/git push --delete --force origin refs/heads/deploy-qa
```
```
name: Deploy React Dev to QA

on: workflow_dispatch

jobs:
  deployToQA:
    runs-on: ubuntu-latest

    steps:
      - name: checkout react-dev code
        uses: actions/checkout@v2
        with:
          ref: "react-dev"

      - run: echo "checkout react-dev job status is ${{ job.status }}."

      - name: create PR to deploy to QA
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: react-dev # the pull request branch name
          base: react-qa
          token: ${{ secrets.GITHUB_TOKEN }}
          title: QA Deploy (${{ github.actor }})
          commit-message: create PR to deploy react-dev to react-qa
          body: Auto-generated PR (via Github Actions manual workflow) to deploy react-dev to react-qa. Intiated by ${{ github.actor }}.
          delete-branch: false # delete the branch when closing pull requests, and when undeleted after merging. 
          labels: automated pr # common or newline-seperated list of labels
          draft: false
          assignees: trugr
          reviewers: trugr

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          
      - name: merge PR
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: merge
```

**Comment by peter-evans** [comment]
Hi @jcquiles 

The problem is that the branch `react-dev` already exists. That's not how the action works. The `branch` input of the action is created and managed by the action.

It looks like what you are trying to do is create a pull request from `react-dev` to update `react-qa`. Please see this example for how to sync two existing branches:
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

Your solution should look something close to this:
```
jobs:
  qaPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: react-qa
      - name: Reset reach-qa branch
        run: |
          git fetch origin react-dev:react-dev
          git reset --hard react-dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: qa-promotion
```
