### ISSUE TITLE
Branch strategy using base branch name

### ISSUE THREAD

**Issue by Matts966** [peter-evans/create-pull-request#1149]
### Subject of the issue

When maintaining multiple branches, it is useful to name branches `${target-base-branch}-suffix`.

**Comment by peter-evans** [comment]
Hi @Matts966 

You can do what you want like this:
```yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${target-base-branch}
          branch-suffix: random
```

But be aware of the [downsides](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch) of using this "alternative strategy."
