### ISSUE TITLE
[Question] How do you create linebreaks while using the `body` option?

### ISSUE THREAD

**Issue by dep** [peter-evans/create-pull-request#1154]
### Subject of the issue

Is it possible to break the `body` into multiple paragraphs using newlines?

```
- name: Create Pull Request
  uses: peter-evans/create-pull-request@v4
  with:
    token: ${{ secrets.GEM_RELEASE_GIT_TOKEN }}
    commit-message: 'Promoting ${{ steps.tag.outputs.result }} to BarWEB'
    title: 'Promoting ${{ steps.tag.outputs.result }} to BarWEB'
    body: '- [ ] Author TODO: Update the PR title to contain the originating JIRA ID (ex. `STORY-1234: `). This PR promotes to the latest version of a Foo Application to BarWEB. Please [review the Foo commit log](https://github.com/Bar/Foo/commits/main) to ensure that the correct individual is made the assignee so they can carry their change through the BarWEB lifecycle.${{ steps.changelog_reader.outputs.log_entry }}'
    branch: ${{ steps.tag.outputs.result }}
    assignees: dep
    reviewers: dep
```

I tried `\n` but this just printed "\n"
