### ISSUE TITLE
add-paths seems to prevent the action from seeing a diff

### ISSUE THREAD

**Issue by IceTDrinker** [peter-evans/create-pull-request#1160]
### Subject of the issue

I ran the action in a workflow to commit modified ipynbs, but the git diff step seems to be failing despite a modified ipynb being there see the call to the action below and the log of a workflow that did not work as expected.

Edit: I can confirm that running the action without add-paths yields the expected result in my workflow.

### Steps to reproduce

```yaml
      - name: Open PR
        uses: peter-evans/create-pull-request@f1a7646cead32c950d90344a4fb5d4e926972a8f
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: "chore: refresh notebooks"
          branch: "chore/refresh-notebooks-for-${{ github.ref_name }}"
          base: "${{ github.ref_name }}"
          title: "Refresh notebooks for ${{ github.ref_name }}"
          body: "Automatic PR with notebooks refresh for ${{ github.ref_name }}."
          add-paths: |
            'docs/**/*.ipynb'
```

And here are the logs from the workflow with comments on what seems to be happening.

```console
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  chore/fix-silly-makefile-mistake
  Working base is branch 'chore/fix-silly-makefile-mistake'
  /usr/bin/git checkout --progress -B 7c646724-8f2c-4348-b33c-97a84bba877f HEAD --
  Switched to a new branch '7c646724-8f2c-4348-b33c-97a84bba877f'

  # HERE HERE HERE HERE HERE
  # Note it found a modified ipynb

  M	docs/user/advanced_examples/ConvolutionalNeuralNetwork.ipynb
  /usr/bin/git status --porcelain -unormal -- 'docs/**/*.ipynb'

  # HERE HERE HERE HERE HERE
  # But for whatever reason this makes the isDirty call not see the repo is dirty
  # I checked locally the git diff commands and a modified ConvolutionalNeuralNetwork.ipynb
  # git diff --quiet -- 'docs/**/*.ipynb' returns 1 in my shell but something is going wrong here it seems
  # Suggestion, also log the return codes of these commands to see what may be happening

  /usr/bin/git diff --quiet -- 'docs/**/*.ipynb'
  /usr/bin/git diff --quiet --staged -- 'docs/**/*.ipynb'

  # HERE HERE HERE HERE HERE
  # Nothing is committed, we direclty go to the repo cleanup which makes me say that the call to git.isDirty returns false
  # https://github.com/peter-evans/create-pull-request/blob/f1a7646cead32c950d90344a4fb5d4e926972a8f/src/create-or-update-branch.ts#L122
  # I don't know typescript so I don't know what may be going wrong in the code

  /usr/bin/git reset --hard
  HEAD is now at c197ecc chore: fix silly quote mistake
  /usr/bin/git clean -f -d
  Resetting working base branch 'chore/fix-silly-makefile-mistake'
  /usr/bin/git checkout --progress chore/fix-silly-makefile-mistake --
  Switched to branch 'chore/fix-silly-makefile-mistake'
  Your branch is up to date with 'origin/chore/fix-silly-makefile-mistake'.
  /usr/bin/git reset --hard origin/chore/fix-silly-makefile-mistake
  HEAD is now at c197ecc chore: fix silly quote mistake
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow origin chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake:refs/remotes/origin/chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake
  fatal: couldn't find remote ref chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake
  Pull request branch 'chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake' does not exist yet.
  /usr/bin/git checkout --progress -B chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake 7c646724-8f2c-4348-b33c-97a84bba877f --
  Switched to a new branch 'chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake'
  /usr/bin/git rev-list --right-only --count chore/fix-silly-makefile-mistake...chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake
  0
  
  # HERE HERE HERE HERE HERE
  # Nothing was committed so no PR opened

  Branch 'chore/refresh-notebooks-for-chore/fix-silly-makefile-mistake' is not ahead of base 'chore/fix-silly-makefile-mistake' and will not be created
  /usr/bin/git rev-parse HEAD
  c197ecc3629125a156038fd5e4e84c13678a193a
  /usr/bin/git branch --delete --force 7c646724-8f2c-4348-b33c-97a84bba877f
  Deleted branch 7c646724-8f2c-4348-b33c-97a84bba877f (was c197ecc).
```
