### ISSUE TITLE
delete-branch

### ISSUE THREAD

**Issue by ReenigneArcher** [peter-evans/create-pull-request#1171]
### Subject of the issue
Looking for any ideas on how to solve this particular issue.

My workflow runs on a push event into `nightly` branch when specific files are modified. The reason is that the `Update Strings` step will always show a new file (it puts the date modified in the header of the file).

```yaml
name: localize

on:
  push:
    branches: [nightly]
    paths:  # prevents workflow from running unless these files change
      - 'retroarcher.py'
      - 'pyra/**.py'
      - 'web/templates/**'
  workflow_dispatch:

jobs:
  localize:
    name: Update Localization
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python 3.9
      uses: actions/setup-python@v3  # https://github.com/actions/setup-python
      with:
        python-version: '3.9'

    - name: Set up Python 3.9 Dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -r requirements.txt

    - name: Update Strings
      run: |
        python ./scripts/_locale.py --extract

    - name: Create/Update Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: |
          locale/*.po
        token: ${{ secrets.GH_PAT }}  # must trigger PR tests
        commit-message: New localization template
        branch: localize/update
        delete-branch: true
        base: nightly
        title: New Babel Updates
        body: |
          Update report
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          babel
          l10n
```

To get the `delete-branch` functionality to work, I'd assume I need to add `locale/*.po` to the paths in the trigger; however that would create an endless loop of PRs (assuming I merge them).

I had a look here, but did not see a pull request `merged` event. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request ... I'm not sure if the `closed` type includes `merged`.

Do you have any recommendations for how to get the `delete-branch` working, without running my python steps?
