### ISSUE TITLE
PR closed by @github-actions after I close / reopen it

### ISSUE THREAD

**Issue by ozh** [peter-evans/create-pull-request#1172]
Hello @peter-evans,

### Subject of the issue : 

I close then re-open issues to trigger workflows : the bot closes them

### Steps : 

1. I'm using your workflow (v4) to update an external binary when it changes. So far, so good.
2. As expected when the PR is created, further workflows are not triggered.
3. To trigger them and following your advice, I close then immediately reopens the PR : workflows this time are indeed triggered, but a couple seconds after the PR is automatically closed, interrupting the workflows 😢 

Example: https://github.com/YOURLS/YOURLS/pull/3293 
![image](https://user-images.githubusercontent.com/223647/164059823-8c486468-e2d7-44e9-9b5f-5d17ded1c868.png)

I purposely removed the `delete-branch` setting, hoping that it would not entice the bot to close the PR (?) and it gets even more confused, stating both a closed and unmerged PR and a successfully merged and closed PR. Example: https://github.com/YOURLS/YOURLS/pull/3296
![image](https://user-images.githubusercontent.com/223647/164060170-2c0d640c-fb5c-436a-beb8-db8000fe84b1.png)
 
### My workflow : 

The workflow I'm using is basically : 

```yml
name: Update GeoIP DB

on:
  schedule:
    - cron: '37 13 * * 1'
  push:
    branches: [ master ]
  pull_request:
    paths:
      - '.github/workflows/update-geoip.yml'
      - 'includes/geo/*'
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-geoip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if newer GeoIP DB
        CODE TO UPDATE THE BINARY

      - name: "Debug info: Show git status"
        run: git status -vv --untracked=all

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: auto-update-geoip
          commit-message: "Update GeoIP DB"
          title: "Update GeoIP DB"
          body: "Updated GeoIP database"
```

Actual workflow here : https://github.com/YOURLS/YOURLS/blob/master/.github/workflows/update-geoip.yml

Any help very much appreciated !

**Comment by peter-evans** [comment]
Hi @ozh 

The reason it gets closed is here: https://github.com/YOURLS/YOURLS/runs/6082202574?check_suite_focus=true#step:6:508

> Branch 'auto-update-geoip' no longer differs from base branch 'master'

There is no diff between 'auto-update-geoip' and `master` so the pull request is closed automatically by GitHub's API.

**Comment by ozh** [comment]
Thanks Peter for looking into this !

Here is the actual chain of events : 

- Flow `Update GeoIP DB #26` : PR is created because the branch does differ from master, see https://github.com/YOURLS/YOURLS/runs/6090464920?check_suite_focus=true#step:6:89 -- this PR is created against `master` as shown in https://github.com/YOURLS/YOURLS/runs/6090464920?check_suite_focus=true#step:2:43
- I close the PR
- I re-open the PR : all workflows are triggered, including the one that opened the PR : now "`Update GeoIP DB #27`" where indeed it says that master no longer differs https://github.com/YOURLS/YOURLS/runs/6090511993?check_suite_focus=true#step:6:508 but it's not created against `master`, it's actually a PR against the branch created by the previous flow: https://github.com/YOURLS/YOURLS/runs/6090511993?check_suite_focus=true#step:2:43 -- so it's normal that there is no change

I've updated the workflow to use a github app as you explain in your docs, and the same flow happens without my closing/reopening.

So in my understanding, I need to prevent the workflow to be triggered from a PR that was created by itself : is there any way I can tell the action ?

**Comment by ozh** [comment]
I understand this may be out of the scope of your action.

Thanks for this superb action !

**Comment by peter-evans** [comment]
Hi @ozh 

Sorry for the delay in responding.

I think you can do something like this to prevent the workflow running on a PR that was created by the workflow.
```yml
jobs:
  update-geoip:
    # Check if the PR is not raised by this workflow
    if: startsWith(github.head_ref, 'auto-update-geoip') == false
    runs-on: ubuntu-latest
    steps:
    ...
```
