### ISSUE TITLE
Action omits previous commits to `branch`

### ISSUE THREAD

**Issue by btrautmann** [peter-evans/create-pull-request#1173]
### Subject of the issue

We have a use case where there are previous commits to the branch from which we're looking to open a PR. Unfortunately the behavior we're seeing is the following:

**Scenario 1**
- job A checks out `branch-a`, makes a commit, and pushes it (this is an empty commit using `--allow-empty` but I don't believe this matters)
- job B checks out `branch-a` and correctly sees this commit in `git log`, uses that commit for some implied versioning and uploads artifacts to be committed in the next job
- job C checks out `branch-a`, downloads artifacts from job B, and attempts to commit them and open a PR using `create-pull-request` action from `branch-a` to `main`, but unfortunately only the commit made by `create-pull-request` itself is contained within the PR, and NOT the one from job A

**Scenario 2**
I also tested by adding an additional job B2 between B and C that downloaded the artifacts and committed them manually, THEN used `create-pull-request` _without_ any commits specified to open the PR. In _this_ case it said that the branch did not differ from the base branch `main` (i.e, neither the commits from job A or job B2 were respected/shown).

### Steps to reproduce

Create a workflow that contains at least 1 job prior to this action being run that commits a code change onto the branch that will later be used as the `branch` input to this action. They're not included in the PR into `base`.

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow. _I can't do this bit as the repository is private_

_Edit/Update:_

To prove to myself that this should indeed work, I left the workflow in the same shape it was, but migrated to using the `github-script` to open the PR.

```yaml
  - name: Create pull request
    id: create_pull_request
    uses: actions/github-script@v6
    with:
      script: |
        const { repo, owner } = context.repo;
        const result = await github.rest.pulls.create({
          title: 'chore(release): Prep for next release',
          owner,
          repo,
          head: 'branch-a',
          base: 'main',
          body: [
            'This PR is auto-generated by',
            '[actions/github-script](https://github.com/actions/github-script).'
          ].join('\n')
        });
```

This worked as expected, and contained both commits from job A and job B2 in the second scenario above.

**Comment by peter-evans** [comment]
Hi @btrautmann 

The action is not designed to be used on existing branches. The action creates and maintains the PR branch itself, and any manual commits or commits outside of the workflow raising the PR will be ignored. This is intentional and part of the design of this action.

However, you can work around this for your specific scenario. One way to achieve it would be to make your own commit before the action runs by cherry picking job A's commit. See this section of the readme for how to make your own commits before the action runs:
https://github.com/peter-evans/create-pull-request#create-your-own-commits

**Comment by btrautmann** [comment]
Thanks @peter-evans and I do apologize for not fully reading tho docs before opening an issue! For future readers, we were able to make this work as suggested in the linked docs, something along the lines of:

```yaml
 - name: Add minor bump to PR branch
    shell: bash
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git add path/to/config/files
      git commit -m "chore(MINOR): prep for future release v${{ needs.calculate_versions.outputs.build_name }}'
      git push origin --delete bot/release-prep
  - name: Create pull request
    id: create_pull_request
    uses: peter-evans/create-pull-request@v4
```

So basically we pushed the commit we needed to calculate the new version to a temporary branch, run the job that calculates the versions, then do all of our commits on a fresh checkout of `main` and simply open the PR. We delete the temporary branch as well just to clean up after ourselves 🙃
