### ISSUE TITLE
nektos/act: Attempting creation of pull request: error::Not Found

### ISSUE THREAD

**Issue by rodrigobrim** [peter-evans/create-pull-request#1177]
### Using [act](https://github.com/nektos/act) to test my workflows, I can't create the PR:

```
| f38a729f25093f60b2d130674491247ff88f972a
| [command]/usr/bin/git branch --delete --force cf22f947-4da0-474f-8daa-08054330e475
| Deleted branch cf22f947-4da0-474f-8daa-08054330e475 (was ea91aa9).
[Daily image update/UpdateImageVersion]   ❓  ::endgroup::
[Daily image update/UpdateImageVersion]   ❓  ::group::Create or update the pull request
| Attempting creation of pull request
[Daily image update/UpdateImageVersion]   ❗  ::error::Not Found
[Daily image update/UpdateImageVersion]   ❓  ::group::Restore persisted git credentials
| [command]/usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
[Daily image update/UpdateImageVersion]   ❓  ::endgroup::
[Daily image update/UpdateImageVersion]   ❌  Failure - Create Pull Request for solo
[Daily image update/UpdateImageVersion] exit with `FAILURE`: 1
Error: Job 'UpdateImageVersion' failed
```

### Steps to reproduce

I'm using act version 0.2.26, with a personal docker image with my ssh key inside (for some reason, the GITHUB_TOKEN as a secret doesn't work also).

The previous snippet was acquired with the following command: act schedule -s ACTIONS_RUNNER_DEBUG=true

**Comment by rodrigobrim** [comment]
The workflow:

```
name: Daily image update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  UpdateImageVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: New file
        run: touch new-file
      
      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@v4.0.2
```
