### ISSUE TITLE
Error when running git cherry-pick command

### ISSUE THREAD

**Issue by mriiad** [peter-evans/create-pull-request#1178]
Hi @peter-evans, thank you for this very helpful GA and congratulations for your great work 🙌🏼

### Subject of the issue

My goal is to execute `git cherry-pick <commit_sha>` command which will be useful to find changes and allow me to create a PR right after.

### Steps to reproduce
To achieve this objective, I replaced the command creating 'report.txt' file by `git cherry-pick <commit_sha>`

here's the error I got:
```
fatal: bad object <sha>
Error: Process completed with exit code 128.
```

here's a part of my .yml file:
```- uses: actions/checkout@v3
      - name: Make changes to pull request
        run: git cherry-pick <sha>
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@mohamed.riad.support.com>
          signoff: false
          path: origin/develop
          branch: 8620_cherryPick_3
          base: release/target
          delete-branch: true
          title: '[AUTO] create pull request'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: yanniser
          reviewers: yanniser
          team-reviewers: |
            owners
            maintainers
          #milestone: 1
          draft: false```

**Comment by peter-evans** [comment]
Hi @mriiad 

It's difficult to diagnose what is wrong here, but it looks like that error is in the step where you are doing the `git cherry-pick`. My advice would be to remove the `create-pull-request` step and debug your workflow to make sure it's working as you expect before raising the PR.

**Comment by mriiad** [comment]
Hello @peter-evans, thanks for replying.

The problem with the `git cherry-pick <SHA>` command is due to the **SHA** (commit id) which is unknown neither on the **branch** nor on the **base** because it's done on the branch **master**.

Is there any solution to make it available in the used environment please ?

**Comment by mriiad** [comment]
Good news: the problem is solved thanks to some git commands, so my new yml file is:
```
      - name: Make changes to pull request
        run: |
          git config --global user.name "mriiad"
          git fetch
          git cherry-pick <sha>
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@mohamed.riad.support.com>
          signoff: false
          path: origin/develop
          branch: 8620_cherryPick_3
          base: release/target
          delete-branch: true
          title: '[AUTO] create pull request'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: yanniser
          reviewers: yanniser
          team-reviewers: |
            owners
            maintainers
          #milestone: 1
          draft: false
```

Thank you @peter-evans 🙌🏼
