### ISSUE TITLE
Help: branch isn't being created

### ISSUE THREAD

**Issue by arctouch-douglasfornaro** [peter-evans/create-pull-request#1186]
### Branch isn't being created

I'd like to keep my master branch up to date with the hotfixes. This is my scenario:
Master branch is considered the development branch.
Every new release we create a new release branch: `release-3`, `release-3.1`, etc.
If we find some issue in the release, we fix it in the release branch, make a hotfix and then push to master to keep it up to date.
I'd like to automatize this part by creating a PR to master.

This is the script so far:
```
name: Release Auto PR
on:
  push:
    branches:
      - 'release-**'

jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: peter-evans/create-pull-request@v4
        name: pull-request
        with:
          delete-branch: true
          branch: github-actions/hot-fix
          branch-suffix: random
          base: master
          title: Pulling ${{ github.ref }} into master
          body: |
            Merge release branch hotfixes upstream into master
```

This is the log from workflow:
```
  /usr/bin/git checkout --progress master --
  Switched to branch 'master'
  /usr/bin/git rev-list --reverse release-6.22..c6a02fc3-a5b3-44c2-b6b7-50910f9c1374 .
  /usr/bin/git checkout --progress -B c6a02fc3-a5b3-44c2-b6b7-50910f9c1374 HEAD --
  Switched to and reset branch 'c6a02fc3-a5b3-44c2-b6b7-50910f9c1374'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin master:master
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules origin github-actions/hot-fix-8czc2xo:refs/remotes/origin/github-actions/hot-fix-8czc2xo
  fatal: couldn't find remote ref github-actions/hot-fix-8czc2xo
  Pull request branch 'github-actions/hot-fix-8czc2xo' does not exist yet.
  /usr/bin/git checkout --progress -B github-actions/hot-fix-8czc2xo c6a02fc3-a5b3-44c2-b6b7-50910f9c1374 --
  Switched to a new branch 'github-actions/hot-fix-8czc2xo'
  /usr/bin/git rev-list --right-only --count master...github-actions/hot-fix-8czc2xo
  0
  Branch 'github-actions/hot-fix-8czc2xo' is not ahead of base 'master' and will not be created
  /usr/bin/git rev-parse HEAD
  4cd16c703884f013a1cd9017d614d572ca2a9d96
  /usr/bin/git branch --delete --force c6a02fc3-a5b3-44c2-b6b7-50910f9c1374
  Deleted branch c6a02fc3-a5b3-44c2-b6b7-50910f9c1374 (was 4cd16c7038).
```

Branch is not being created just like this log is saying `  Branch 'github-actions/hot-fix-8czc2xo' is not ahead of base 'master' and will not be created`.
What am I missing in the script? Can someone help me?

**Comment by peter-evans** [comment]
Hi @arctouch-douglasfornaro 

Please see this example. I think it will help you with this scenario.
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

**Comment by griechelTs** [comment]
@peter-evans I am also running into this issue. Implementing the suggestion from your link above failed with a different reason: `fatal: refusing to fetch into branch 'refs/heads/master'`

I'm trying to periodically create PRs to keep a non-default branch up to date with the default branch 'master`. My spec is below:

```
jobs:
  request-prod-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Merge daily changes into Production
          title: Merge daily changes into Production
          body: Merge daily changes into Production
          base: release
          labels: automated-pr
          branch: autopr/daily-prod
          delete-branch: true
```
