### ISSUE TITLE
Merge conflicts when keeping a branch up to date with main

### ISSUE THREAD

**Issue by Gabe1203** [peter-evans/create-pull-request#1188]
### Subject of the issue

When creating a PR off of main to be merged into a production branch we get a ton of merge conflicts. Ideally this would not be the case but I'm not sure what we're doing wrong or if there is even a way to avoid this. Not sure this is a bug with this action or just something we'll have to deal with every-time we want to merge our main branch into production. Thanks for the help!

### Steps to reproduce

Our github action code:
```
productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: production-promotion
```
If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
