### ISSUE TITLE
Creating a single pull request for different OS

### ISSUE THREAD

**Issue by aminya** [peter-evans/create-pull-request#119]
### Subject of the issue

Creating a single pull request for different OS

### Steps to reproduce
Is it possible to create a single PR for different OS?

I have a workflow file like this:
https://github.com/aminya/Example.jl/blob/017d772f3b36e50a32913c7d0d76e72f3fa849db/.github/workflows/SnoopCompileMulti.yml#L34
that generates separate PRs for different OS. I want to know if I can merge these two together (they don't have conflicts).

Ref. https://github.com/timholy/SnoopCompile.jl/pull/71

**Comment by peter-evans** [comment]
@aminya In order to merge together the changes from the two jobs and raise them in a single pull request I would look into using [upload-artifact](https://github.com/actions/upload-artifact) and [download-artifact](https://github.com/actions/download-artifact) actions. This is one of the standard ways to pass data between jobs.

Then you could try to do something like this, where the changes from both jobs are downloaded in a final job and the pull request created.
```
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2

      # Create changes for ${{ matrix.os }}

      # Upload an artifact for ${{ matrix.os }} changes
      - uses: actions/upload-artifact@v1
         with:
           name: my-artifact-${{ matrix.os }}
           path: path/to/artifact

  createPullRequest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Download an artifact for ubuntu-latest changes
      - uses: actions/download-artifact@v1
         with:
           name: my-artifact-ubuntu-latest
           path: path/to/artifact

      # Download an artifact for windows-latest changes
      - uses: actions/download-artifact@v1
         with:
           name: my-artifact-windows-latest
           path: path/to/artifact

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
