### ISSUE TITLE
not able to properly keep staging up-to-date with development

### ISSUE THREAD

**Issue by balusarakesh** [peter-evans/create-pull-request#1197]
### Subject of the issue
Hi,
 - We are trying to keep the staging branch up-to-date with development branch but everytime a PR is created against `staging` branch it consists of commits that are already merged in the `staging` branch (which is super weird because the changed files in the PR show that it's gonna make changes that already exist in the upstream `staging` branch)
  - we are following the docs [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another)

### Steps to reproduce
out github actions workflow:
```
  create-pull-request:
    if: github.event_name != 'pull_request'
    runs-on:
      - feature/generic
      - size/xs
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - name: Reset branch
        run: |
          cd $GITHUB_WORKSPACE
          git fetch origin development:development
          git reset --hard development
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: '${{ steps.github-token.outputs.token }}'
          commit-message: Updates from development branch into staging
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: development-to-staging
          delete-branch: false
          title: '[Automated] Updates from development branch into staging'
          body: |
            Updates from development branch into staging
          draft: false
```

 - the above action will generate a PR against `staging` branch with a new branch called `development-to-staging`
 - but the PR shows changes which are already present in the `staging` branch
 
basically when a PR is generated against `staging` branch with this action, we only want to see the new commits that don't exist in the `staging` branch

I've been digging more into this and I think what we want is a `two-dot` diff in the pull request instead of `three-dot` diff which is the default

 - Thank you
