### ISSUE TITLE
Not able to create PR based on local changes

### ISSUE THREAD

**Issue by bc-dima-pasieka** [peter-evans/create-pull-request#1199]
### Subject of the issue

I'm trying to autogenerate some files after pushing to master/main and create a PR based on changes. But I'm getting the next error:
```
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  master
  Working base is branch 'master'
  /usr/bin/git remote prune origin
/usr/bin/git rev-parse --short HEAD
f7463d4

Pull request branch to create or update set to 'create-pull-request/patch-f7463d4'

Configuring the committer and author
  Configured git committer as 'GitHub <noreply@github.com>'
  Configured git author as 'bc-dima-pasieka <bc-dima-pasieka@users.noreply.github.com>'

Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  master
  Working base is branch 'master'
  /usr/bin/git checkout --progress -B 3cf75f5c-0baf-45fe-ac5b-32a2c11038a8 HEAD --
  Switched to a new branch '3cf75f5c-0baf-45fe-ac5b-32a2c11038a8'
  M changed/file/is/going/here
  /usr/bin/git status --porcelain -unormal -- QQQ
  /usr/bin/git diff --quiet -- QQQ
  /usr/bin/git diff --quiet --staged -- QQQ
  /usr/bin/git reset --hard
  HEAD is now at f7463d4 COMMIT_NAME
  /usr/bin/git clean -f -d
  Resetting working base branch 'master'
  /usr/bin/git checkout --progress master --
  Switched to branch 'master'
  Your branch is up to date with 'origin/master'.
  /usr/bin/git reset --hard origin/master
  HEAD is now at f7463d4 COMMIT_NAME
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin create-pull-request/patch-f7463d4:refs/remotes/origin/create-pull-request/patch-f7463d4
  fatal: couldn't find remote ref create-pull-request/patch-f7463d4
  Pull request branch 'create-pull-request/patch-f7463d4' does not exist yet.
  /usr/bin/git checkout --progress -B create-pull-request/patch-f7463d4 3cf75f5c-0baf-45fe-ac5b-32a2c11038a8 --
  Switched to a new branch 'create-pull-request/patch-f7463d4'
  /usr/bin/git rev-list --right-only --count master...create-pull-request/patch-f7463d4
  0
  Branch 'create-pull-request/patch-f7463d4' is not ahead of base 'master' and will not be created
  /usr/bin/git rev-parse HEAD
  f7463d43172616d937645f5665bd1fcce40261a7
  /usr/bin/git branch --delete --force 3cf75f5c-0baf-45fe-ac5b-32a2c11038a8
  Deleted branch 3cf75f5c-0baf-45fe-ac5b-32a2c11038a8 (was f7463d4).
```

### Steps to reproduce
GA configuration looks like this:
```
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  do-stuff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # other jobs to create/modify files
    # ...

    
    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'XXX'
        title: 'YYY'
        labels: 'github-action'
        reviewers: 'ZZZ'
        branch-suffix: short-commit-hash
        delete-branch: true
        add-paths: 'QQQ'
```

I would expect the action to create a PR based on local changes.
Is there something that I missed from the documentation? Thanks!
