### ISSUE TITLE
Option to not create PR if one already exists

### ISSUE THREAD

**Issue by scottgigante-immunai** [peter-evans/create-pull-request#1201]
I would like to avoid force pushing to the target branch if a PR already exists -- specifically, if the action has already run, the relevant PR has already been created and I would rather not rerun CI. Is it possible to skip the action if a) the base branch already exists, b) there is already a PR from the base branch to the target branch, or c) pushing to the base branch would require a force push?

**Comment by peter-evans** [comment]
Hi @scottgigante-immunai 

The action does not have these kind of features because it's designed purposely to update itself in this way. If you don't want the action to run in specific cases then you can write a condition in the workflow to prevent it. The action is opinionated in this way, so I'm keeping that kind of logic external to the action and managed by the workflow.

There is a little more info in this issue:
https://github.com/peter-evans/create-pull-request/issues/1062#issuecomment-1044548704

**Comment by scottgigante-immunai** [comment]
Thanks @peter-evans , that makes sense. Here's how I'm going to include this in my workflow, let me know if you have a cleaner way:
```
  - name: Check for available updates
    run: |
      echo "BRANCH_EXISTS=$(git ls-remote --heads origin ${UPDATE_BRANCH_NAME} | tr -d '\n')" >> $GITHUB_ENV

  - name: Create Pull Request
    if: "env.BRANCH_EXISTS == ''"
    uses: peter-evans/create-pull-request@v4
    with:
      branch: ${{ env.UPDATE_BRANCH_NAME }}
```
