### ISSUE TITLE
fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by topikito** [peter-evans/create-pull-request#122]
### Subject of the issue

ref HEAD is not a symbolic ref

### Steps to reproduce

We are using your action to automatically open a pull request after changes have been made to some JS files which require building a bundle.

This is how we are using the action
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto compiled JS"
          title: "Auto compiled JS"
          body: "This pull request was automatically generated as new changes on the JS project were found"
          branch: "auto/javascript-compiled"
          branch-suffix: timestamp
```

In this particular case, we made a change and committed directly to master. This, in v1, worked well. Now in v2, we get the above error. We migrated to v2 because we were experiencing some python issues this morning and decided to upgrade.

**Comment by peter-evans** [comment]
Hi @topikito 

Please see [this short guide](https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md) for updating from v1 to v2.

Most likely the problem is due to your workflow using `actions/checkout@v1`. Please upgrade to `actions/checkout@v2`. If that doesn't solve the issue, please post your workflow so I can see how you are checking out and making changes to pull request.

**Comment by topikito** [comment]
Thanks @peter-evans , apologies for not checking that before. Will try it out and, if necessary, mention you again.

**Comment by maxim-lobanov** [comment]
I have faced with the same issue in different context and just want to share my findings and solution, may be it will be useful for someone:

When workflow is triggered by `release` event, step `- uses: actions/checkout@v2` will check out tag instead of branch and `create-pull-request` step will fail with the `fatal: ref HEAD is not a symbolic ref` error.

The solution is pretty simple:
```
- uses: actions/checkout@v2
      with:
        ref: 'master'
```

**Comment by peter-evans** [comment]
@maxim-lobanov I just wanted to let you know that I've just added support for events which checkout a commit, not a branch, provided the `base` input is supplied.

I've released `v3.2.0` with support for this. Please see [events which checkout a commit](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#events-which-checkout-a-commit)

Basically this means that for the `release` event you can make changes directly on top of the tag commit. The action will then rebase them onto the branch supplied by the `base` input.

```yml
on:
  release:
    types: [published]

jobs:
  published:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - uses: peter-evans/create-pull-request@v3
        with:
          base: master
```
