### ISSUE TITLE
   ! [remote rejected] HEAD

### ISSUE THREAD

**Issue by thatrandomperson5** [peter-evans/create-pull-request#1234]
### Subject of the issue

I get this error here:
```

   ! [remote rejected] HEAD -> actions/prettier (refusing to allow a GitHub App to create or update workflow `.github/workflows/formatter.yml` without `workflows` permission)
```

### Steps to reproduce

Run yml:
```yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Html code with prettier push"
          commit-message: ":art: Format Html code with prettier"
          body: |
            There appear to be some html formatting errors in ${{ github.sha }}. This pull request
            uses the [prettier](https://prettier.io) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/prettier       

```
[Link](https://github.com/thatrandomperson5/thatrandomperson5.github.io/actions/runs/2928729464/workflow)
