### ISSUE TITLE
Flag to stop the branch deletion when branches match (mostly for gh-pages)

### ISSUE THREAD

**Issue by pauliver** [peter-evans/create-pull-request#124]
### Subject of the issue

Great Script! I'm using this script to branch from master to gh-pages automatically. 

When they match the script try's to blow away the gh-pages directory, but that is where github pages are served from. Ideally some flag that we could set to prevent:

> Branch 'gh-pages' no longer differs from base branch 'master'
> Closing pull request and deleting branch 'gh-pages' 

### Steps to reproduce

```yml
name: Create Thumbnails, Compressed images, Build Jekyll Site, Branch to Release on Success
env:
  URL: "example.com"
  AutoMergeLabel: "automerge"
  GHPages: "gh-pages"
  CurrentBranch: "master"
  Repo: "repo"
  Owner: "owner"
  # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

on:
  push:
    branches: [master]
# page_build: # Pretty sure this was triggering endlessly
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  process_images:
    name: Process Images with DotNet ${{ matrix.dotnet }}
    runs-on: [windows-latest]
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main 
      - name: Checkout Image Tools
        uses: actions/checkout@v2
        with:
          repository: pauliver/CSharp-Image-Action
          path: ImgTools
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
     
      - name: Restore Dependancies
        run: dotnet restore ImgTools/

      - name: Build Image Tools
        run: dotnet build ImgTools/ --configuration Release
      
      - name: Run the Image Tools
        run: dotnet  ${{github.workspace}}\ImgTools\bin\Release\netcoreapp3.1\CSharp-Image-Action.dll  ${{github.workspace}}\main\gallery\ ${{github.workspace}}\main\ https://${{env.URL}}

      - name: Commit the resized files and .json
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add *
          git commit -m "Add resized images" -a
        working-directory: main 
        shell: powershell
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: main   
  build_jekyll_site:
    name: Build the site in the jekyll/builder container
    needs: process_images
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
  create_pr_if_success:
    name: Create PR to gh-pages if everything works
    needs: [process_images, build_jekyll_site]
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.1 #https://github.com/marketplace/actions/create-pull-request
        with:
          path: main
          base: ${{env.CurrentBranch}}
          branch: ${{env.GHPages}}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "tests all passed, creating PR for ${{env.GHPages}}"
          labels: ${{env.AutoMergeLabel}}
```

**Comment by peter-evans** [comment]
Hi @pauliver 

If you want to create a pull request that will be merged into the `gh-pages` branch then that branch is the `base`, not `branch`. My understanding of your use case is to keep the `gh-pages` branch up-to-date with `master` by raising PRs when there are changes. If that is the case, please try the following instead.

```
  create_pr_if_success:
    name: Create PR to gh-pages if everything works
    needs: [process_images, build_jekyll_site]
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{env.GHPages}}
      - name: Reset GitHub Pages branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.1 #https://github.com/marketplace/actions/create-pull-request
        with:
          branch: github-pages-promotion
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "tests all passed, creating PR for ${{env.GHPages}}"
          labels: ${{env.AutoMergeLabel}}
```
The workflow first checks out the `gh-pages` branch, because this is the `base` of the pull request. It then resets the branch to match `master`. If there are changes, the action will raise a PR to update the `gh-pages` branch. The pull request branch is called `github-pages-promotion`. When the PR is merged or closed, the `github-pages-promotion` branch can be deleted without affecting `gh-pages` or `master`.
