### ISSUE TITLE
Cannot sign commit using Github App auth

### ISSUE THREAD

**Issue by andridzi** [peter-evans/create-pull-request#1241]
### Subject of the issue

Cannot sign commit using Github App auth.

### Steps to reproduce

As mentioned in [docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-bots), `Signature verification for bots` will only work if there is `no custom author information, custom committer information, and no custom signature information`.

Even if put correct `committer` and `author` fields commit will not be signed.
It will be signed only when `committer` and `author` fields not set at all.

**Comment by peter-evans** [comment]
Hi @andridzi 

Please could you explain in more detail about what you are trying and what does/doesn't work.

> It will be signed only when committer and author fields not set at all.

So are you saying it works when you set the `committer` and `author` to empty strings? e.g.
```yml
      - uses: peter-evans/create-pull-request@v4
        with:
          committer: ''
          author: ''
```
