### ISSUE TITLE
Unable to create PR from a tag

### ISSUE THREAD

**Issue by rcclemente** [peter-evans/create-pull-request#1242]
### Subject of the issue

We are currently tagging any merges to `dev` and we want to use this action when deploying a tag to `uat` and `prod`

We want to manually trigger this action for creating PRs, so users select a tag  

I consulted the docs https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#events-which-checkout-a-commit

### Steps to reproduce
Select the tag to deploy to trigger the workflow 

<img width="1466" alt="Screen Shot 2022-09-05 at 17 26 03 " src="https://user-images.githubusercontent.com/22880578/188416361-679ed4d4-8222-465e-a383-226efad041d5.png">

### Log

under: Create or update the pull request branch
```
  /usr/bin/git checkout --progress uat --
  Switched to branch 'uat'
  /usr/bin/git rev-list --reverse f4bccabf4c0108c95e066e97840b04d55b2536fa..90a53eeb-3187-4b99-ba46-64b83e106f0d .
  /usr/bin/git checkout --progress -B 90a53eeb-3187-4b99-ba46-64b83e106f0d HEAD --
  Switched to and reset branch '90a53eeb-3187-4b99-ba46-64b83e106f0d'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin uat:uat
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin create-pull-request/patch:refs/remotes/origin/create-pull-request/patch
  fatal: couldn't find remote ref create-pull-request/patch
  Pull request branch 'create-pull-request/patch' does not exist yet.
  /usr/bin/git checkout --progress -B create-pull-request/patch 90a53eeb-3187-4b99-ba46-64b83e106f0d --
  Switched to a new branch 'create-pull-request/patch'
  /usr/bin/git rev-list --right-only --count uat...create-pull-request/patch
  0
  Branch 'create-pull-request/patch' is not ahead of base 'uat' and will not be created
  /usr/bin/git rev-parse HEAD
  d52ab35ad5f780d3c971364be49ce26cf9948022
  /usr/bin/git branch --delete --force 90a53eeb-3187-4b99-ba46-64b83e106f0d
  Deleted branch 90a53eeb-3187-4b99-ba46-64b83e106f0d (was d52ab35).
```

### Workflow 
```
name: UAT Release
on:
  workflow_dispatch:

jobs:
  uat_release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Create Pull Request to UAT
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag
        run: |
          echo "GITHUB_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
      - name: Set Title
        run: |
          echo "GITHUB_TITLE='[UAT] Release ${{ env.GITHUB_TAG }}'" >> $GITHUB_ENV
      - name: Append commit
        run: |
          git config user.name 'Github bot'
          git config user.email 'github.bot@users.noreply.github.com'
          echo "${{ env.GITHUB_TITLE }} `date +%s`"> releaseinfo.txt
          git add -A
          git commit -m "${{ env.GITHUB_TITLE }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          base: "uat"
          
          labels: |
            UAT
          title: "${{ env.GITHUB_TITLE }}"
          body: |
            ## Describe your changes
            ## Checklist before requesting a review
            - [ ] Verified that this worked with DEV environment
```

Any suggestion on how to make this work? Thanks :)

**Comment by peter-evans** [comment]
Hi @rcclemente 

Please see this section:
https://github.com/peter-evans/create-pull-request#create-your-own-commits

When creating commits you must be checked out on a branch with a remote. It won't work for detached head states.

I think what you are trying to do overall is not well suited to this action. You already have the commits with the tag. You can just create a branch where your tag is and make a pull request from the two branches using your own call to the GitHub API with something like [github-script](https://github.com/actions/github-script). This action is best suited for situations where changes are being made during the workflow and don't exist already.

**Comment by rcclemente** [comment]
Hi @peter-evans 

Just some additional information 

Our current git strategy is 

1. Create a Pull request
2. Merge to DEV and git tag/release 
3. Create a PR with that tag 

The `Append Commit` part was not essential, I should have removed it.

Below is the correct workflow. Would `[create-pull-request](https://github.com/peter-evans/create-pull-request)` still not work with this? 

Thanks for your response

```
name: UAT Release
on:
  workflow_dispatch:

jobs:
  uat_release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Create Pull Request to UAT
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag
        run: |
          echo "GITHUB_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
      - name: Set Title
        run: |
          echo "GITHUB_TITLE='[UAT] Release ${{ env.GITHUB_TAG }}'" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          base: "uat"
          
          labels: |
            UAT
          title: "${{ env.GITHUB_TITLE }}"
          body: |
            ## Describe your changes
            ## Checklist before requesting a review
            - [ ] Verified that this worked with DEV environment
```

**Comment by peter-evans** [comment]
The problem here is that you don't have any way for the action to understand what you want to do.

Either:
1. Create a temporary branch on the commit tag and use something similar to [this example](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another).
2. Check out branch `uat` (the base), and make new commits locally to match the diff between `uat` and the tag. This might be a bit more tricky and I don't have an example.

**Comment by rcclemente** [comment]
@peter-evans 

Thanks for you help. Managed to make it work with option 1

PRs are created properly now

```
name: UAT Release
on:
  workflow_dispatch:

jobs:
  uat_release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Create Pull Request to UAT
    steps:
      - uses: actions/checkout@v3
        with:
          ref: uat
      - name: Set Tag
        run: |
          echo "PR_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
      - name: Reset promotion branch
        run: |
          git fetch --all
          git reset --hard ${{ env.PR_TAG }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch: "${{env.PR_TAG}}-uat-release"
          base: uat
          team-reviewers: |
            @mysale/cloud-engineering-team
          labels: |
            UAT
          title: "[UAT] Release ${{ env.PR_TAG }}"
          body: |
            ## Describe your changes
            created by: ${{github.actor}}

            ## Checklist before requesting a review
            - [ ] Verified that this worked with DEV environment

```
