### ISSUE TITLE
How to configure head to create PRs from feature branches to master?

### ISSUE THREAD

**Issue by xhujerr** [peter-evans/create-pull-request#1243]
### Subject of the issue

I don't understand how should I configure the `branch` to create pull requests from feature branches. Sorry for asking such a basic question, but I wasn't able to figure it out.

To illustrate I'd like to borrow an example from [thomaseizinger](https://github.com/thomaseizinger) / [create-pull-request](https://github.com/thomaseizinger/create-pull-request):
```
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:    
        head: ${{ github.ref }}
        base: master
```        
this will create pull request 
- from `my-feature-1` to `master` when I push to `upstream/my-feature-1`
- from `my-feature-2` to `master` when I push to `upstream/my-feature-2`

I struggle to understand the what corresponds to the `head` here.

### Steps to reproduce

When I try:
```
      - name: Create Pull Request from feature to master
        id: cpr_master
        uses: peter-evans/create-pull-request@v4
        with:
            base: master
```
I get an error `refname 'refs/heads/my-feature-1' is ambiguous`.

The closest I was able to get to what I want was with config:

```
name: pull_request
on:
  push:
    branches-ignore:
      - create-ami
      - deploy-*
      - PR/*

jobs:
  createPullRequest:
    runs-on: self-hosted
    steps:

      - uses: tibdex/github-app-token@v1
        id: get-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: Create Pull Request from feature to master
        id: cpr_master
        uses: peter-evans/create-pull-request@v4
        if: ${{ ! contains(fromJson('["master", "create-ami","deploy-","PR/"]'), github.ref_name) }}
        with:
            base: master
            branch: ${{ github.ref }}
            author: ${{ github.actor }} <${{ github.actor }}@mydomain.com>
            title: "AutoPR: merge ${{ github.ref_name }} to master: ${{ github.event.head_commit.message }}"
            token: ${{ steps.get-token.outputs.token }}
```
 but then subsequent call of github API `api/v3/repos/org/repo/pulls/99/merge` fails with
 ```
 {
  "message": "Head branch was modified. Review and try the merge again.",
  "documentation_url": "https://docs.github.com/enterprise/3.5/rest/reference/pulls#merge-a-pull-request"
}
```
also after manual merging of such pull request, the latest commit is missing. 

So I assume that it is not the correct way.

How should I specify `head` for a feature branch whose name is every time different?
