### ISSUE TITLE
Having difficulty syncing branches

### ISSUE THREAD

**Issue by nwhobart** [peter-evans/create-pull-request#1244]
### Subject of the issue

Hello @peter-evans . Thanks for the great action but I'm having some issues. My problem is similar to https://github.com/peter-evans/create-pull-request/issues/1148 however the proposed solution in both the issue and the documentation don't seem to be working for me. 

I have four existing branches: 

`staging`
`uat`
`partner`
`production`

I'm trying to simply create a PR from `staging` to `uat`.  I am using a `workflow_call` that looks something like this: 

```
jobs:
  create_pr:
    name: pull request
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_target_branch }}

      - name: create token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: reset source branch
        run: |
          git fetch origin ${{ inputs.pr_source_branch }}:${{ inputs.pr_source_branch }}
          git reset --hard ${{ inputs.pr_source_branch }}

      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: ${{ inputs.pr_target_branch }}-promotion
          base: ${{ inputs.pr_source_branch }}
```

where `pr_source_branch` == `staging` and `pr_target_branch` == `uat` 

I am running the action from the `staging` branch and when I do no PR is created and I see the following in logs: 

`Rebasing commits made to branch 'uat' on to base branch 'staging'`

a whole lot of  `fetch` logs and then:

```
  The previous cherry-pick is now empty, possibly due to conflict resolution.
  If you wish to commit it anyway, use:
  
      git commit --allow-empty
  
  Otherwise, please use 'git cherry-pick --skip'
  On branch staging
  You are currently cherry-picking commit 800339b.
    (all conflicts fixed: run "git cherry-pick --continue")
    (use "git cherry-pick --skip" to skip this patch)
    (use "git cherry-pick --abort" to cancel the cherry-pick operation)
  
  nothing to commit, working tree clean
  /usr/bin/git checkout --progress -B 4c0325a1-fa74-44e0-b6db-ee1633cfc253 HEAD --
  Switched to and reset branch '4c0325a1-fa74-44e0-b6db-ee1633cfc253'
  warning: cancelling a cherry picking in progress
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin staging:staging
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin uat-promotion:refs/remotes/origin/uat-promotion
  fatal: couldn't find remote ref uat-promotion
  Pull request branch 'uat-promotion' does not exist yet.
  /usr/bin/git checkout --progress -B uat-promotion 4c0325a1-fa74-44e0-b6db-ee1633cfc253 --
  Switched to a new branch 'uat-promotion'
  /usr/bin/git rev-list --right-only --count staging...uat-promotion
  0
  Branch 'uat-promotion' is not ahead of base 'staging' and will not be created
  /usr/bin/git rev-parse HEAD
  800339b73866cc897ef4ff8e46bf99a445abbb25
  /usr/bin/git branch --delete --force 4c0325a1-fa74-44e0-b6db-ee1633cfc253
  Deleted branch 4c0325a1-fa74-44e0-b6db-ee1633cfc253 (was 800339b).
  ```

I cannot figure out what I'm doing wrong. While I don't _have_ to do the workflow from the `staging` branch it sure does make life easier. 

My job looks something like this: 

```
jobs:
  create-pr:
    uses: <org>/<team>/.github/workflows/create_pr.yaml@main
    secrets: inherit
    with:
      pr_target_branch: 'uat'
      pr_source_branch: 'staging'
```

Thanks for any help in restoring my sanity!
