### ISSUE TITLE
Cannot set the author to bot when a PAT is used

### ISSUE THREAD

**Issue by 030** [peter-evans/create-pull-request#1266]
### Subject of the issue

Cannot set the author to bot when a PAT is used. Instead, when the PR is created then I am the author, while the bot should be the owner.

### Steps to reproduce

```
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        assignees: '030'
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        base: main
        commit-message: 'build(deps): Update versions.'
        committer: GitHub <noreply@github.com>
        delete-branch: true
        reviewers: '030'
        title: 'Update dependencies.'
        token: ${{ secrets.PAT }}
```
