### ISSUE TITLE
Continuous update of PR across workflows

### ISSUE THREAD

**Issue by comc** [peter-evans/create-pull-request#1295]
### Subject of the issue

Looking for best practice / guidance on using this action with the MegaLinter package for continuous updates to the PR based on a "typical" workflow defined as:

1. Dev opens project PR (PPR)
2. MegaLinter runs linting with `APPLY_FIXES: all` and `APPLY_FIXED_MODE: pull_request` configured
3. This `create-pull-request` action opens linter PR (LPR) with commit for fixes, when applicable
4. Dev adds _N_ commits to PPR, each triggering a MegaLinter workflow with potential for applied fixes
5. Each commit from MegaLinter workflow is added to LPR (rebased on latest PPR) until dev merges LPR to PPR branch

Currently, the LPRs are not capturing commits beyond the first, opening commit of the LPR.

#### Config:

- MegaLinter is running with a Personal Access Token (PAT)
- `create-pull-request` action configured as follows (MegaLinter default):
```
      # Create pull request if applicable (for now works only on PR from same repository, not from forks)
      - name: Create Pull Request with applied fixes
        id: cpr
        if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{ github.head_ref }}
          branch: create-pull-request/patch/${{ github.ref_name }}
          commit-message: "[MegaLinter] Apply linters automatic fixes"
          delete-branch: true
          labels: bot
          title: "[MegaLinter] Apply linters automatic fixes"
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
```

#### Steps:

Described above in "Subject of the issue"

### Questions

- Is there a specific configuration missing that's required to ensure PRs get updated?
- Are the PRs opened by this action not intended to work across consecutive workflows?
