### ISSUE TITLE
"Keep a branch up-to-date with another" example not working?

### ISSUE THREAD

**Issue by basickarl** [peter-evans/create-pull-request#1297]
### Subject of the issue

I had a look at your example of how to update a branch when `main-ci-dev` is updated (https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another):

workflow file:

```
name: Merge main into next
on:
  push:
    branches:
      - main-ci-dev

jobs:
  stuffz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1-ci-dev
      - name: Reset promotion branch
        run: |
          git fetch origin main-ci-dev:main-ci-dev
          git reset --hard main-ci-dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: v1-ci-dev-promotion
```

github action logs:
```
Run actions/checkout@v3
Syncing repository: neo4j/neo4j-design
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/1ce26605-6993-43ec-bcd3-2b5e03e0654d' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/neo4j-design/neo4j-design
Deleting the contents of '/home/runner/work/neo4j-design/neo4j-design'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/v1-ci-dev*:refs/remotes/origin/v1-ci-dev* +refs/tags/v1-ci-dev*:refs/tags/v1-ci-dev*
  The process '/usr/bin/git' failed with exit code 1
  Waiting [14](https://github.com/neo4j/neo4j-design/actions/runs/3312737154/jobs/5469779095#step:3:15) seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/v1-ci-dev*:refs/remotes/origin/v1-ci-dev* +refs/tags/v1-ci-dev*:refs/tags/v1-ci-dev*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/v1-ci-dev*:refs/remotes/origin/v1-ci-dev* +refs/tags/v1-ci-dev*:refs/tags/v1-ci-dev*
  Error: The process '/usr/bin/git' failed with exit code 1

```

Whenever a change to main happens we want a pull request to be created where we would like to update our branch `v1-ci-dev` with the changes just pushed to `main-ci-dev`. `main-ci-dev` is not our default branch nor is `v1-ci-dev`.

Is there something I've misunderstood?
