### ISSUE TITLE
Create PR is failing when using submodules (but only changes in the root repo)

### ISSUE THREAD

**Issue by skirsten** [peter-evans/create-pull-request#1299]
### Subject of the issue

Hi,
we are using submodules and this action. We are only doing changes to the "root" repo and not any submodule. When its time to create the PR it fails:

```sh
# ... everything works
/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin auto-updater/patch:refs/remotes/origin/auto-updater/patch
# ^ works
/usr/bin/git checkout --progress auto-updater/patch --
  error: The following untracked working tree files would be overwritten by checkout:
  	my-submodule/file1.txt
  	my-submodule/file2.txt
``` 

This is probably because of the `--no-recurse-submodules` setting.

### Steps to reproduce

workflow
```yaml
- uses: actions/checkout@v3
  with:
    submodules: true
    token: ${{ secrets.MY_TOKEN }}

- run: date > test.txt

- name: Create pull request
  uses: peter-evans/create-pull-request@v4
  with:
    ...
```

Any help is appreciated!

**Comment by peter-evans** [comment]
Hi @skirsten 

> We are only doing changes to the "root" repo and not any submodule.

If you are only making changes to the root repo then do you need to checkout the submodules in the first place? Does it work if you change the initial checkout like this?

```diff
        - uses: actions/checkout@v3
          with:
-           submodules: true
            token: ${{ secrets.MY_TOKEN }}
        
        - run: date > test.txt
        
        - name: Create pull request
          uses: peter-evans/create-pull-request@v4
          with:
            ...
```

Or perhaps the changes are derived from the submodules and you can't do this?

**Comment by skirsten** [comment]
Hi @peter-evans,

> Or perhaps the changes are derived from the submodules and you can't do this?

Yes, unfortunately to generate the changes in the CI it requires the submodule to be checked out.

> Does it work if you change the initial checkout like this?

Before :point_up: the requirement of the submodule, we were using this action for a long time without any problems. So if the "change generation code" could function without the submodule, yes it would work.

Thanks

**Comment by peter-evans** [comment]
Ok, understood. I will look at finding a way to fix this when I have some time.

In the meantime, there is a potential workaround. This is how it works:
1. Separate the workflow into two jobs, the second job depending on the first using the `needs:` keyword
2. In the first job, checkout the submodules and create the repository changes.
3. At the end of the first job, use [upload-artifact](https://github.com/actions/upload-artifact) to store the changes.
4. In the second job, run checkout only for the root repo, without the submodules.
5. Use [download-artifact](https://github.com/actions/download-artifact) to copy the changes created in the first job over the local repo.
6. Execute create-pull-request

**Comment by peter-evans** [comment]
@skirsten I've tried to reproduce this but have been unsuccessful. 

These are some tests I ran that all created and updated PRs no problem.
```yml
  createPullRequest1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report1.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: test1

  createPullRequest2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Make changes to pull request
        run: date +%s > report2.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: test2

  createPullRequest3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Make changes to pull request
        run: date +%s > report3.txt

      - name: Add untracked changes inside submodule
        run: date +%s > my-submodule/temp.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: test3
```

You mentioned that you switched to using submodules recently. What I think might be happening is that the submodule exists on some branches but not all. So when you checkout a branch that doesn't have the submodule it's trying to checkout a directory to the same path as the submodule, or something like that. That's the best idea I can think of to explain this.
