### ISSUE TITLE
Creating multiple pull requests with different base branches but same commits

### ISSUE THREAD

**Issue by Wipster** [peter-evans/create-pull-request#1302]
### Subject of the issue

Sticking to git flow a created hotfix branch should be merged into dev and main. Thus I'd like to create at least two PRs when doing e.g. a composer update.

### Steps to reproduce

This is how I tried to achieve what I need. This results in the pr being closed immediately probably because the second step has no commits.

```
name Upgrade

on: workflow_dispatch

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - run: composer update "mycore/project-*" --with-all-dependencies

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: hotfix-upgrade
          base: main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: hotfix-upgrade
          base: dev
```

My current workaround ist to use github command line.

```
 - name: create pull request
      run: gh pr create -B dev -H hotfix-upgrade --title 'Upgrade' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Is my use case doable with this action or is it not intended to be used like this?
