### ISSUE TITLE
[Help needed] Copy a file from one repository to another by submitting a PR

### ISSUE THREAD

**Issue by agostonr** [peter-evans/create-pull-request#1304]
### Subject of the issue

Hello, 
I'm trying to set up a runner that copies my documentation files (any pdf) from my private repo to a publicly available repository that only stores the docs. Here's the workflow script I put together:

```
name: Open documentation PR in docs repository

on:
  push:
    branches: [ "master" ]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: me/documentation-repo
          
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            *.pdf
          token: ${{ secrets.PAT }}
          commit-message: Update documentation
          committer: GitHub <noreply@github.com>
          author: me <myemail@email.com>
          signoff: false
          base: master
          branch: update-docs
          delete-branch: true
          title: 'Update documentation'
          body: |
            Update documentation
```

The workflow runs fine and ends up green, but nothing happens so I checked the logs. There I found that 

`Branch 'update-docs' is not ahead of base 'master' and will not be created`

meaning, the automation wanted to find the pdf files on the docs repo to open a PR, but since that's the old documentation, not the new from the private repo, it didn't create a PR. 

### Question

My question is that is it possible to open a PR to copy certain files from one repo to the other and if so, how to do it?

**Comment by peter-evans** [comment]
Hi @agostonr 

Yes, you can do this. The step you are missing is to actually make the changes locally. You are checking out base branch, which is correct, but then you aren't making any local changes that you want to include in the pull request. Just setting `add-paths` to `*.pdf` is not enough. You actually need to update the locally checked out branch. See examples in the documentation for help.

**Comment by david-alpert-nl** [comment]
@peter-evans I am not clear on the sequence of events here.

I have an existing workflow running in repo A:
- check out repo A
- make changes
- check them in and push to repo A

how can I take the contents of folder `./typings` from repo A and open a PR into repo B to push the updated `./typings` file from one repo to another?

**Comment by peter-evans** [comment]
For that use case I recommend splitting the workflow into two jobs:

job1:
- checkout repo A
- make changes
- upload artifact of `./typings`

job2:
- checkout repo B
- download artifact of `./typings`
- create pull request

The workflow will look something like this:
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo A
      - uses: actions/checkout@v3
      # Make changes / build artifact
      - run: ...
      # Save as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: typings
          path: typings
  pullRequest:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # Checkout repo B
      - uses: actions/checkout@v3
        with:
          repo: my-org/repoB
          token: ...
      # Download artifact from first job
      - uses: actions/download-artifact@v3
        with:
          name: typings
          path: typings
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ...
```
