### ISSUE TITLE
Branch updated without PR

### ISSUE THREAD

**Issue by aryaraj132** [peter-evans/create-pull-request#1306]
### Subject of the issue
Base branch updated without creating PR

I am trying to create a workflow which automatically create a PR for changes in any branch other than main, It is currently updating the main branch but without creating PR

### Steps to reproduce
Here is the .yml configuration I am using
```
name: Run the Action on each commit
on:
  push:
    branches-ignore: 
      - main
jobs:
  update-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          commit-message: '[CI] test ${{ matrix.target }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Updates [${{ github.ref }} => main]"
          branch: main
          body: |
            This is an automated pull request to update the container collection README.md.
            Please review the changes before merging.
          labels: |
            update
            automated pr
          assignees: aryaraj132
          reviewers: aryaraj132
          milestone: 1
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
```

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by aryaraj132** [comment]
Output of the workflow:
![image](https://user-images.githubusercontent.com/61931454/201025711-bba6e969-6fe7-4920-926e-e6e1c70c4c2f.png)

**Comment by peter-evans** [comment]
Hi @aryaraj132 

This is not how the action works. You are missing the step to actually make changes to be included in pull requests. Please take some time to read the documentation and understand how this action works. There are also examples linked from the readme.

You must make changes to include before calling the action.
```yml
      - uses: actions/checkout@v3

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
```
