### ISSUE TITLE
Create PR on Schedule (like every monday 8:00 am)

### ISSUE THREAD

**Issue by JigarM** [peter-evans/create-pull-request#131]
Can we create a new PR from specific branch on schedule?
My requirement is need to create auto PR from `develop` to `master` on every week/specific day.

```csharp name: Create Pull Request
on:
  schedule:
    - cron: '0 8 * * MON'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge development to master
          title: '[Example] Add report file'
          body: |
            Auto-generated PR to make sure our `master` branch should have the latest code 
          labels: ready for review
          assignees: JigarM
          reviewers: JigarM
          branch: develop

**Comment by peter-evans** [comment]
@JigarM You can do that, yes. Please see [this example](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another).

Here is what that pattern would look like for your workflow. It checks out `master`, resets to `develop`, and then creates a PR to merge into master. The PR branch is named `master-promotion` (you can rename it to whatever you want, but don't use an existing branch).
```
    steps:
      - uses: actions/checkout@v2
      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge development to master
          title: '[Example] Add report file'
          body: |
            Auto-generated PR to make sure our `master` branch should have the latest code 
          labels: ready for review
          assignees: JigarM
          reviewers: JigarM
          branch: master-promotion
```

**Comment by JigarM** [comment]
@peter-evans Thanks for the quick response. Let me try this way.
I did the mistake to set the PR branch name with existing branch. I hope it should work. Will update you here.

Thanks anyway.!!!

**Comment by JigarM** [comment]
Output:

```csharp 
Target repository set to JigarM/SSD
Pull request branch to create or update set to 'develop-promotion'
Configured git committer as 'Jigar <@gmail.com>'
Configured git author as 'Jigar<@gmail.com>'
Rebasing commits made to branch 'develop' on to base branch 'master'
Pull request branch 'develop-promotion' does not exist yet
Branch 'develop-promotion' is not ahead of base 'master' and will not be created

**Comment by JigarM** [comment]
@peter-evans Below changes works fine for me.

```
name: Create Pull Request
on:
  push:
  schedule:
    - cron: '0 8 * * MON'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge `development` to `master`
          title: Merge develop to master
          body: |
            Auto-generated PR to make sure our master branch should have the latest code 
          labels: ready for review
          branch: develop-promotion
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}" 
```

Thanks for the help!!!!

**Comment by JigarM** [comment]
@peter-evans One more thing I want to share. Github action can't trigger the workflow on schedule time. such as when I write this, nothing happens.
```
on:
  schedule:
    - cron: '0 8 * * MON'
```

But when I add push, the action triggered on push
```
on:
  push:
  schedule:
    - cron: '0 8 * * MON'
```

So, how we can schedule without "push" call?
