### ISSUE TITLE
Pull request keeps updating with identical content over and over again

### ISSUE THREAD

**Issue by villesau** [peter-evans/create-pull-request#1339]
### Pull request keeps updating with identical content over and over again

We built an action which pulls new translations and makes a pull request out of it. This happens every 15 minutes. If the pull request is not merged, the action is run again and the same changes are force pushed to the same branch.

### Steps to reproduce

Have following kind of workflow:

```yml
name: "Pull translations"
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  pullLocalazyTranslations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn translations:download # do some changes to the repo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update translations
          signoff: false
          branch: update-translations
          delete-branch: true
          title: "Update translations"
          body: Update translations
          draft: false
```

This will force push the same changes over and over again. This is very problematic since it generates quite some costs by triggering CI run on every push. It also means that the PR is actually building most of the time which makes it very hard to merge. Is there a way to avoid it?
