### ISSUE TITLE
fatal: could not read Username for 'https://github.com': Device not configured

### ISSUE THREAD

**Issue by LindaNab** [peter-evans/create-pull-request#136]
### Create-pull-request throws error

I am running a job using github actions on my repo (see www.github.com/lindanab/me_neo/actions) and use create-pull-request to provoke a pull request after the job has run. The pull request seems to throw an error when the job exceeds 1 hour:

Compare for example: 
https://github.com/lindanab/me_neo/actions/runs/62244781 (did run),
and
https://github.com/LindaNab/me_neo/actions/runs/62443469 (failed),
while https://github.com/LindaNab/me_neo/blob/master/.github/workflows/main.yml has not changed. 

The error is:
Pull request branch to create or update set to 'patch'
Supplied committer will also be used as the author.
Configured git committer as 'Linda Nab <LindaNab@users.noreply.github.com>'
Configured git author as 'Linda Nab <LindaNab@users.noreply.github.com>'
Uncommitted changes found. Adding a commit.
Traceback (most recent call last):
  File "/Users/runner/runners/2.165.2/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py", line 191, in <module>
    result = coub.create_or_update_branch(repo, repo_url, commit_message, base, branch)
  File "/Users/runner/runners/2.165.2/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_or_update_branch.py", line 70, in create_or_update_branch
    repo.git.fetch("--force", repo_url, f"{working_base}:{working_base}")
  File "/Users/runner/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git -c http.https://github.com/.extraheader=AUTHORIZATION: basic *** fetch --force https://github.com/LindaNab/me_neo master:master
  stderr: 'fatal: could not read Username for 'https://github.com': Device not configured'
**##[error]The process '/Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python' failed with exit code 1**

**Comment by peter-evans** [comment]
Hi @LindaNab 

It does seem to have only failed on the runs that ran over 1 hour, which is very strange if it's not a coincidence. Assuming that is the case, it's possible that something in the virtual machine is timing out after 1 hour. Are you able to try using `runs-on: ubuntu-latest` instead of `runs-on: macOS-latest` to see if that makes a difference?

**Comment by LindaNab** [comment]
Hi @peter-evans 
Thanks for your reply, I've changed runs-on: macOS-latest to runs-on: ubuntu-latest but unfortunately, this didn't make a difference (i.e., the same error occurred):
https://github.com/LindaNab/me_neo/actions/runs/62822395

**Comment by peter-evans** [comment]
This is a very strange issue. I'll need to take some time to try and reproduce this and figure out what is going on. If something really is timing out after an hour on the Actions runner then it might be out of my control.

One possible way you could try to work around this is by separating the workflow into two jobs. The first job executes your workload and produces the output. The output is then uploaded as an artifact using the [upload-artifact](https://github.com/actions/upload-artifact) action. The second job checks out the repository again, downloads the artifact with [download-artifact](https://github.com/actions/download-artifact) action, and then raises a pull request. Creating a "fresh job" like this might work around the issue.

```
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scen_num: [0, 1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Run simulation study for scen_num ${{ matrix.scen_num }}
        run: |-
          Rscript rcode/testjob.R ${{ matrix.scen_num }} 5
      - uses: actions/upload-artifact@v1
        with:
          name: data-output-${{ matrix.scen_num }}
          path: data/output
  pullRequest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scen_num: [0, 1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: data-output-${{ matrix.scen_num }}
          path: data/output
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add sim output simulation study datagen_scen scen_num ${{ matrix.scen_num }}
          committer: Linda Nab <LindaNab@users.noreply.github.com>
          branch: patch${{ matrix.scen_num }}
```
