### ISSUE TITLE
[error]Working base branch '[branch name]' was created by this action. Unable to continue.

### ISSUE THREAD

**Issue by fabich** [peter-evans/create-pull-request#137]
Why is it not possible to create PR with a working branch I created in same action?

```
name: Create and save OpenAPI specification files
# on: repository_dispatch
on:
  watch:
    types: [started]
jobs:
commit-files:
    name: Commit OpenAPI specification files
    needs: create-files
    runs-on: ubuntu-latest
    steps:
      - name: Download OpenAPI specification files from previous job
        uses: actions/download-artifact@v1
        with:
          name: spec-files
      - name: Get version number
        shell: bash
        run: |
          value=`cat spec-files/version.txt`
          echo ::set-output name=version::$value
        id: get-version
      - name: Get date
        shell: bash
        run: |
          echo ::set-output name=date::$(date '+%Y%m%d-%H%M')
        id: get-date
      - name: Create new branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GitHub_PAT }}
        with:
          branch: v${{ steps.get-version.outputs.version }}-${{ steps.get-date.outputs.date }}
      - name: Checkout OpenAPI specification files
        uses: actions/checkout@v2
        with:
          ref: v${{ steps.get-version.outputs.version }}-${{ steps.get-date.outputs.date }}
          token: ${{ secrets.GitHub_PAT }}
          path: repo
      - name: Copy files to src folder
        run: |
          rm -rf repo/src
          cp -r spec-files/*.json repo/src
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GitHub_PAT }}
          commit-message: Added new OpenAPI specification files v${{ steps.get-version.outputs.version }}-${{ steps.get-date.outputs.date }}
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          title: "[v${{ steps.get-version.outputs.version }}] Add new OpenAPI specification files ${{ steps.get-date.outputs.date }}"
          branch: v${{ steps.get-version.outputs.version }}-${{ steps.get-date.outputs.date }}
          path: repo
```
Error:
```
##[error]Working base branch 'v1.9.3-20200324-1447' was created by this action. Unable to continue. Exiting.
##[error]The process '/opt/hostedtoolcache/Python/3.8.2/x64/bin/python' failed with exit code 1
```
