### ISSUE TITLE
Keeps on failing: fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by qdm12** [peter-evans/create-pull-request#142]
I have the following Github workflow

```yml
name: Misspells
on: [pull_request,push]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
          branch-suffix: timestamp
```

But unfortunately it fails with the logs when a pull request is made:

```
Target repository set to qdm12/pingodown
  stderr: 'fatal: ref HEAD is not a symbolic ref'
##[error]The checked out ref is not a valid base for a pull request. Unable to continue. Exiting.
##[error]The process '/opt/hostedtoolcache/Python/3.8.2/x64/bin/python' failed with exit code 1
/usr/bin/git config --local --add http.https://github.com/.extraheader AUTHORIZATION: basic ***
```

[Full log](https://github.com/qdm12/pingodown/runs/537816859?check_suite_focus=true)

[Example of PR from typo branch](https://github.com/qdm12/pingodown/pull/1)

Any help would be greatly appreciated as I would ideally like to use this action for other workflows as well! 👍

**Comment by peter-evans** [comment]
Hi @qdm12 

The issue is that `pull_request` events checkout a merge commit. If you want to raise a pull request to merge into an existing pull request you need to checkout the `head_ref`. See the documentation here:
https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#pull-request-events

Also, `push` should only run on `master` so that you aren't creating two PRs for pull request branches.
```
name: Misspells
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on push
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Checkout on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
          branch-suffix: timestamp
```

When using `branch-suffix: timestamp`, you might end up with a lot of PRs created if your repo has a lot of activity. It can be a bit awkward to use this action well on `pull_request` events. Personally, I would avoid if possible and just make the solution simpler by running on push to `master` only. That way you can use the fixed-branch strategy easier.

```
name: Misspells
on:
  push:
    branches:
      - master
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
```
