### ISSUE TITLE
Deleting Files in Follower Branch

### ISSUE THREAD

**Issue by skeep-exogee** [peter-evans/create-pull-request#1424]
### Deleting Files in Follower Branch

We have been using this action to keep main in sync with staging branch each night. This is working great for new and modified files.

Recently, we noticed that files deleted in the main branch are not deleted in the staging branch.

How can we ensure that files deleted in main are also deleted in staging?

### Steps to reproduce

We are using the action as follows:

```
name: sync-changes-on-main-to-staging
on: [workflow_dispatch]

jobs:
  sync-changes-on-main-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging

      - name: Set Git Configs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin main:main
          git merge main -X theirs --allow-unrelated-histories

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Merge main to staging"
          branch: staging-promotion
          delete-branch: true
          token: ${{ secrets.PAT }}

```
