### ISSUE TITLE
Branch protection error

### ISSUE THREAD

**Issue by SamuelMolling** [peter-evans/create-pull-request#1425]
Good Morning,

I'm having problems with my action, because my repository has branch protection and I would like to know if there is a way to fix it.

Basically I did a PR from the feature/git-action -> develop branch and when I run the action I get this error

```
  remote: error: GH006: Protected branch update failed for refs/heads/staging.        
  remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information. Cannot force-push to this protected branch Waiting on code owner review from DBA.        
  To <REPO>
   ! [remote rejected] HEAD -> staging (protected branch hook declined)
```

My file is as follows

```
name: Create PR Automatic
on:
  push:
    branches:
      - develop
      - staging
jobs:
  staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Reset staging branch
        run: |
          git fetch origin develop:develop --update-head-ok
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: staging
          team-reviewers: DBA
```
