### ISSUE TITLE
PR against fork 

### ISSUE THREAD

**Issue by jderusse** [peter-evans/create-pull-request#143]
This issue is not identical to #71

The purpose is to run the Action in the main repo. But use SSH to push code in a fork.

Why:
- least privilege: the SSH key does not grant access to the main repo, but just to a fork 

```yaml
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout via SSH
      run: |
        git clone --branch master git@github.com:${{ github.repository }}.git .
        git remote set-url origin git@github.com:fork/fork.git .

    - name: Task
      run: |
        touch foo
   
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: fork:bot-code-update <= ??
        head_repository: fork <= ??
```

**Comment by peter-evans** [comment]
Hi @jderusse 

Interesting use case! Try the following workflow. I've not had chance to test it yet, but I think it might work. You will need to create a `repo` scoped [Personal Access Token (PAT)](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) so that the main repo can create a pull request in the remote repository.

Do you need the `Task` step? I'm assuming you just want to update the fork's `master` branch from the `master` branch of the main repo.

```
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: actions/checkout@v2
       with:
         ref: master

    - name: Set remote URL
      run: |
        git remote set-url origin git@github.com:fork/fork.git .
   
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.PAT }}
        branch: bot-code-update
```
