### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/create-pull-request#1460]
### Subject of the issue

in one of our actions I stumbled over a deprecation warning:

![image](https://user-images.githubusercontent.com/47448731/210762131-958cbcb1-af5c-4929-93e3-55907ead0a5a.png)

### Steps to reproduce

the action looks like

```
- name: Create Pull Request
        uses: https://github.com/peter-evans/create-pull-request/tree/v4v4
        with:
          path: kunzmann
          title: Sync automation configuration from templates
          body: |
            This pull request contains 'automation workflows' and was triggered in ${{github.event.client_payload.pull_request.html_url}}
          commit-message: Sync automation configuration from templates
          token: ${{ secrets.PHP_GH_ACTION }}
          author: ${{ github.event.client_payload.github.actor }} <${{ github.event.client_payload.github.actor }}@users.noreply.github.com>
          committer: ${{ github.event.client_payload.github.actor }} <${{ github.event.client_payload.github.actor }}@users.noreply.github.com>
          assignees: ${{ github.event.client_payload.github.actor }}
          labels: automerge
          draft: true
```
