### ISSUE TITLE
Create 2 PRs towards master and develop

### ISSUE THREAD

**Issue by SotirisAtTV4** [peter-evans/create-pull-request#1462]
I am trying to follow a simple GitFlow model in my scenario:
I have a `master` and a `develop` branch that are used according to https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow. Nothing fancy or strange, just the two basic branches of the GitFlow model.

I also have a branch that for now can be assumed to be hardcoded and be the `release/2.0.0` branch that after I add a bunch of commits to it I want to merge into both the `master` and `develop` branches by opening two PRs towards `master` and `develop` respectively.

My github action is quite straightforward:

```
name: 'WIP - Make new release'

on:
  workflow_dispatch:

jobs:
  create-pr-towards-master:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the code'
        uses: actions/checkout@v3.0.0
        with:
          ref: develop

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 11

      # checkout master
      - name: 'Checkout master branch'
        uses: actions/checkout@v2
        with:
          ref: master

      # reset local master to match develop
      - name: 'Reset master branch'
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: 'Create a PR towards master'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ORG_PAT_READ_TOOLS }}
          branch: release/2.0.0-rc
          base: master
          title: (chore) [NO-JIRA] Merge RC branch to master
          body: Merge the RC branch to master
          delete-branch: false
          draft: false

          
  create-pr-towards-develop:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the code'
        uses: actions/checkout@v3.0.0
        with:
          ref: develop

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 11

      # checkout develop
      - name: 'Checkout develop branch'
        uses: actions/checkout@v2
        with:
          ref: develop

      # reset local master to match develop
      - name: 'Reset develop branch'
        run: |
          git fetch origin develop:develop

      - name: 'Create a PR towards develop'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ORG_PAT_READ_TOOLS }}
          branch: release/2.0.0-rc
          base: develop
          title: (chore) [NO-JIRA] Merge RC branch to develop
          body: Merge the RC branch to develop
          delete-branch: false
          draft: false
          
```

Does your action need to have as value of the `branch` field the name of an existing branch or a branch that will be created?
  
I am most possibly doing something wrong when resetting the branches but I cannot find out what I am doing wrong. My knowledge of git is quite limited so if you could help me with my scenario I would be grateful.

Thanks.

**Comment by peter-evans** [comment]
Hi @SotirisAtTV4 

There is an example for how to do this in the docs here:
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

In your case it will look something like this. Use this as a starting point:
```yml
jobs:
  create-pr-towards-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Reset develop branch
        run: |
          git fetch origin release/2.0.0:release/2.0.0
          git reset --hard release/2.0.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-develop-with-release
```
