### ISSUE TITLE
Error protected branch

### ISSUE THREAD

**Issue by SamuelMolling** [peter-evans/create-pull-request#1519]
Basically I'm currently using the tretuna/sync-branches@1.4.0 action, but I'm having a problem there and I'm looking at other actions that could help me. When testing this action, I have the following error:

But this works in that other action, could you tell me how can I fix this here?

```
remote: error: GH006: Protected branch update failed for refs/heads/staging.
   remote: error: Cannot force-push to this protected branch Waiting on code owner review from OWNER.
   To https://github.com/repo
    ! [remote rejected] HEAD -> staging (protected branch hook declined)
```

**Comment by SamuelMolling** [comment]
```
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches develop to staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CUSTOM_SECRET }}
          base: develop
          branch: staging
```

**Comment by SamuelMolling** [comment]
```
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches develop to staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets. CUSTOM_SECRET}}
          FROM_BRANCH: 'develop'
          TO_BRANCH: 'staging'
```
