### ISSUE TITLE
delete-branch: true doesn't delete the Branch

### ISSUE THREAD

**Issue by mietzen** [peter-evans/create-pull-request#1520]
### Subject of the issue

`delete-branch: true` doesn't delete the branch after merge

### Steps to reproduce

Set `delete-branch: true` and use auto merge to merge it:

```
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          delete-branch: true
          title: '[Github Action Bot] Update'
          commit-message: Update
          committer: GitHub Action Bot <action@github.com>
          author: GitHub Action Bot <action@github.com>
          branch: auto-update
          branch-suffix: timestamp
          assignees: mietzen
          labels: |
            automated pr
            update

      - name: Automerge if possible
        if: steps.commit.outputs.change == 'yes' && steps.pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          merge-method: squash
```
