### ISSUE TITLE
Running create-pull-request action inside a composite action with twice checked out repositories doesn't work.

### ISSUE THREAD

**Issue by Haegi** [peter-evans/create-pull-request#1522]
### Subject of the issue

I want to call `create-pull-request` inside a composite actions.
This composite action is checked out with a tag. But the action should update things and therefore has to checkout the same repository in main. This doesn't seems to work because the `create-pull-request` action just shows `fatal: couldn't find remote ref <branch>` and `Branch <branch> is not ahead of base 'main' and will not be created`

### Steps to reproduce

Composite action call
```yaml
  update:
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: <repo>
          path: <some-path>
          fetch-depth: 0
          ref: action-0.1.0

      - name: Run update
        uses: ./<some-path>/.github/actions/update/
        with:
...
```

Composite action
```yaml
...
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        path: ./<some-path>
        repository: <repo>
        ref: main

    - name: update
      shell: bash
      working-directory: ./<some-path>
      run: ./scripts

    - name: create pull-request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'update'
        base: main
        branch: ${{ github.run_id }}
        delete-branch: true
        title: 'update'
        draft: false
        path: <some-path>
```
