### ISSUE TITLE
use this action on a private repo

### ISSUE THREAD

**Issue by staabm** [peter-evans/create-pull-request#156]
I try to build a workflow in which I copy a file from a source repo into a dest repo while using pull requests.

my workflow which is triggered via a slash-command (thx for another great action ;-)) looks like

```
name: Sync automation templates into our php repositories

on:
  repository_dispatch:
    types: [sync-command] # triggered by /sync PR comment

jobs:

  template-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.STAABM_TOKEN }}
        repository: complex-gmbh/php-automation-templates
        ref: master
        path: templates-master

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.STAABM_TOKEN }}
        repository: complex-gmbh/kunzmann
        ref: production
        path: kunzmann
        
    - run: |
        cp templates-master/templates/pr-badge-fast-track.yml kunzmann/.github/pr-badge-fast-track.yml
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        path: kunzmann
        token: ${{ secrets.STAABM_TOKEN }}
```

I am wondering that I can see "permisson-errors" and got the impression that this create-pull-request action might not work for private repos?

![grafik](https://user-images.githubusercontent.com/120441/78689551-bf00a580-78f6-11ea-9c85-f1e316868c8c.png)
