### ISSUE TITLE
Does not run on push action

### ISSUE THREAD

**Issue by SamuelMolling** [peter-evans/create-pull-request#1575]
### Subject of the issue

I have two actions to create automatic prs from dev -> stg and stg -> dev.

When I perform the merge in dev, it automatically creates a pr with the changes for stg, however if I close this pr, I would like it to also create for prd, but that does not happen.

### Steps to reproduce

Create a pr for the develop environment and after performing the merge, the action will run. But the second time it doesn't work.

auto_pr_stg.yml
```
name: Create PR Automatic to Staging
on:
  push:
    branches:
      - develop
    paths:
      - xpto/**
      - .github/**
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches develop to staging
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - name: Reset staging branch
        run: |
          git fetch origin develop:develop --update-head-ok
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: feature/dev-to-stg
          title: Sync Develop to Staging
          body: |
             - Automatic PR from Develop to Staging
             - By: DBRE Team
          labels: |
            Env: Staging
            From: Auto PR
          token: ${{ secrets.AUTO_MERGE }}
          branch-suffix: short-commit-hash
```

auto_pr_prd.yml
```
name: Create PR Automatic to Master
on:
  push:
    branches:
      - staging
    paths:
      - xpto/**
      - .github/**
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches staging to master
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin staging:staging --update-head-ok
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: feature/dev-to-stg
          title: Sync staging to master
          body: |
             - Automatic PR from staging to master
             - By: DBRE Team
          labels: |
            Env: master
            From: Auto PR
          token: ${{ secrets.AUTO_MERGE }}
          branch-suffix: short-commit-hash
```

And now a question I'm not sure about:

Considering that I have 2 different features and uploaded both in develop, with 2 different PRs, feature A and B. The action creates a PR for each PR performed in the branch, taking only the change of each one or it considers, for example, B came after A and took A along?

**Comment by peter-evans** [comment]
Hi @SamuelMolling 

In `auto_pr_prd.yml` you should change the `branch` input to something different so it doesn't conflict with the other workflow.

As for `branch-suffix`, I would strongly advise not to use that. That feature only exists for backwards compatibility. See the documentation [here](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch). I would highly recommend you just let the action update PRs automatically. If you do that then both feature A and B will end up in the same PR and it will cause less problems.

**Comment by SamuelMolling** [comment]
In this way?

```
name: Create PR Automatic to Master
on:
  push:
    branches:
      - staging
    paths:
      - xpto/**
      - .github/**
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches staging to master
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin staging:staging --update-head-ok
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: feature/dev-to-master
          title: Sync staging to master
          body: |
             - Automatic PR from staging to master
             - By: DBRE Team
          labels: |
            Env: master
            From: Auto PR
          token: ${{ secrets.AUTO_MERGE }}
```

**Comment by SamuelMolling** [comment]
@peter-evans Basically, when I open two requests in develop, it joins the two in the same pr that was opened in the staging branch, I wanted it to be in different prs, because they are different features and maybe they go up at different times.

**Comment by peter-evans** [comment]
@SamuelMolling Make sure the `branch` input is different in the workflows. That's probably why it's reusing the same branch and PR.

**Comment by SamuelMolling** [comment]
This branch option, right @peter-evans ?

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: feature/dev-to-stg
          title: Sync Develop to Staging
          body: |
             - Automatic PR from Develop to Staging
             - By: DBRE Team
          labels: |
            Env: Staging
            From: Auto PR
          token: ${{ secrets.AUTO_MERGE }}
          delete-branch: true
```

Do I need to use one of the strategies in that [URL](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch)?

Any recommendations like that?
