### ISSUE TITLE
Does not retain previous commits to the branch

### ISSUE THREAD

**Issue by boxadesign** [peter-evans/create-pull-request#1576]
### Subject of the issue

I have the following workflow which can be described as:

- Manually update package.json version
- Commit change on a branch specifically named "create/release"

When branch is pushed:

- Action -  Update a readme with the version number in package.json
- Action - Run a build command
- Action - Create a PR to merge into main with the changes

The problem is that the original commit of package.json is lost. The readme is updated correctly and committed. As well as the output from the build command.

Here is my code:

```
name: Build Release

on:
  push:
    branches:
      - create/release

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get version from package.json
        id: get-version
        run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
        
      - name: Get current version from main branch
        id: get-current-version
        run: echo "CURRENT_VERSION=$(curl -s https://raw.githubusercontent.com/ONSdigital/design-system-react/main/package.json | jq -r '.version')" >> $GITHUB_ENV
        
      - name: Compare versions
        if: env.PACKAGE_VERSION == env.CURRENT_VERSION
        run: exit 1
        env:
          ERROR_MESSAGE: "Package version is the same as HEAD."
        
      - name: Replace version in readme.md
        run: sed -i "s/\(https:\/\/github.com\/ONSdigital\/design-system-react#\)v[0-9]\.[0-9]\.[0-9]/\1v${{ env.PACKAGE_VERSION }}/g" README.md
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run yarn build-package
        run: yarn build-package
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Create release - v${{ env.PACKAGE_VERSION }}"
          body: "This PR includes changes for the release v${{ env.PACKAGE_VERSION }}."
          labels: "release"
          branch: "create/release"
          base: "main"
          
```

**Comment by peter-evans** [comment]
Hi @boxadesign 

Manually making changes is not going to work because the action will overwrite commits in the specified `branch`.

Instead of this:
> Manually update package.json version
> Commit change on a branch specifically named "create/release"

What I would suggest is to change the workflow to trigger on `workflow_dispatch`. Make a workflow parameter for the new version you want to set. Then during the workflow add a step that updates package.json with the value of the workflow parameter. Then the rest of your workflow can execute as-is.

**Comment by boxadesign** [comment]
Hi @peter-evans thanks for the reply. I think the first two steps I stated have confused things.

- Manually update package.json version
- Commit change on a branch specifically named "create/release"

What I meant by this is that locally I would create a branch named `create/release`, manually change the version in package.json, push this branch which would trigger the action.

**Comment by peter-evans** [comment]
Hi @boxadesign 

I understood that those were manual steps. What I'm saying is, there is a way that you can do what I think you are trying to do without creating the branch first.

Please try this workflow. Instead of doing your manual steps to commit to a branch, just go to the GitHub UI for this workflow and click "Run workflow." It will create a pull request for the release version you want.

```yml
name: Build Release
run-name: Build release v${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new release version
        required: true

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package.json version
        run: npm version ${{ github.event.inputs.version }} --git-tag-version false 

      - name: Replace version in readme.md
        run: sed -i "s/\(https:\/\/github.com\/ONSdigital\/design-system-react#\)v[0-9]\.[0-9]\.[0-9]/\1v${{ github.event.inputs.version }}/g" README.md

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run yarn build-package
        run: yarn build-package

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Create release - v${{ github.event.inputs.version }}"
          body: "This PR includes changes for the release v${{ github.event.inputs.version }}."
          labels: "release"
          branch: "create/release-${{ github.event.inputs.version }}"
          base: "main"
```

After committing this workflow, go to the UI and run it with the version you want.
![image](https://user-images.githubusercontent.com/18365890/217426230-659c9b33-494e-4d07-8fa0-43e38732b92e.png)
