### ISSUE TITLE
error: remote fork already exists.

### ISSUE THREAD

**Issue by shrinktofit** [peter-evans/create-pull-request#1639]
### Subject of the issue

Use `push-to-fork` option, build twice, the error should appear:

```
Run peter-evans/create-pull-request@v4
  with:
    path: engine-extensions
    push-to-fork: shrinktofit/engine-extensions
    token: ***
    title: Bump @editor/fbx-gltf-conv to 1.0.0-alpha.4[3](https://github.com/shrinktofit/cocos-editor/actions/runs/4228727838/jobs/7344440203#step:6:3)(editor patch: 5[4](https://github.com/shrinktofit/cocos-editor/actions/runs/4228727838/jobs/7344440203#step:6:4)8489468)
    body: 这个 PR 希望更新 FBX-glTF-conv 依赖为  1.0.0-alpha.43，包内版本为：[5](https://github.com/shrinktofit/cocos-editor/actions/runs/4228727838/jobs/7344440203#step:6:5)484894[6](https://github.com/shrinktofit/cocos-editor/actions/runs/4228727838/jobs/7344440203#step:6:6)8。
  
    add-paths: packages/fbx-gltf-conv/*
  
    commit-message: [create-pull-request] automated change
    committer: GitHub <noreply@github.com>
    author: shrinktofit <shrinktofit@users.noreply.github.com>
    signoff: false
    branch: create-pull-request/patch
    delete-branch: false
    draft: false
  
(node:4[7](https://github.com/shrinktofit/cocos-editor/actions/runs/4228727838/jobs/7344440203#step:6:7)60) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Save persisted git credentials
  "C:\Program Files\Git\cmd\git.exe" config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader
  "C:\Program Files\Git\cmd\git.exe" config --local --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader AUTHORIZATION: basic ***
  "C:\Program Files\Git\cmd\git.exe" config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
  Unset config key 'http.https://github.com/.extraheader'
Determining the base and head repositories
  "C:\Program Files\Git\cmd\git.exe" config --local --get remote.origin.url
  https://github.com/cocos/engine-extensions
  Checking if 'shrinktofit/engine-extensions' is a fork of 'cocos/engine-extensions'
  "C:\Program Files\Git\cmd\git.exe" remote add fork https://github.com/shrinktofit/engine-extensions
  error: remote fork already exists.
  Error: The process 'C:\Program Files\Git\cmd\git.exe' failed with exit code 3
Restore persisted git credentials
  "C:\Program Files\Git\cmd\git.exe" config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  "C:\Program Files\Git\cmd\git.exe" config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ***"
  Persisted git credentials restored
```

### Steps to reproduce

```yaml
# The step
- name: Create Pull Request on editor repository
        uses: peter-evans/create-pull-request@v4
        with:
          path: 'cocos-editor'
          push-to-fork: ${{github.event.inputs.editor_pr_repo}}
          token: ${{secrets.PUBLISH_FBX_GLTF_CONV_ON_NPM_REPO_TOKEN}}
          title: '更新对 @editor/fbx-gltf-conv 的依赖到 ${{github.event.inputs.main_bump_version}}(editor patch: ${{github.event.inputs.editor_patch_bump_version}})'
          add-paths: |
            app/package.json
          body: |
            这个 PR 更新对 npm 包 @editor/fbx-gltf-conv 的依赖，相关 PR：${{ steps.create_package_update_pr.outputs.pull-request-url }}。
```
