### ISSUE TITLE
Question: Raise PR on separate sub-directory repo?

### ISSUE THREAD

**Issue by geekdave** [peter-evans/create-pull-request#167]
I've got kind of an obscure use case, but I need to raise a PR on a separate repo B as the last step of a pipeline on repo A.

The checkout action supports checking out to a separate working directory.  Is there a way I can tell the create-pull-request action to raise the PR against the repo in that sub-directory?

```
      - name: Checkout repo B
        uses: actions/checkout@v2
        with:
          repository: myorg/b
          token: ${{ secrets.CI_USER_TOKEN }}
          path: repo-b
```

I can see the files in the repo using:

```
      - name: Check repo B files
        working-directory: ./repo-b
        run: |
          ls -la
```

Just can't figure out how to have the create-pull-request action use that working directory.

Thanks for putting this project out there!

**Comment by peter-evans** [comment]
Hi @geekdave 

Yes, you can use the `path` input in the same way as `actions/checkout`.

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          path: repo-b
```
