### ISSUE TITLE
Question: Accumulate commits instead of force-pushing updates to existing PR

### ISSUE THREAD

**Issue by geekdave** [peter-evans/create-pull-request#169]
We're considering using this action for a bot to accumulate updates on a specific branch `my-auto-update-branch`, which human reviewers would then review and merge to master on a weekly basis.

So far the functionality is working great, except that each time the action updates the PR, it force-pushes which wipes out the previous commit history for the other updates the action had made.  I think this is because I had been modifying files on a master checkout, and then the action was applying those changes over top the `my-auto-update-branch` feature branch.

Is there a way to configure the action to make individual commits on the feature branch without force-pushing?

I tried to instead check out the feature branch `my-auto-update-branch` with the checkout action, and then tell the create-pull-request action to use `master` as a base, but it didn't work... here's what I tried:

```
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: myorg/repo-a
          ref: my-auto-update-branch
          path: repo-a
          token: ${{ secrets.CI_USER_TOKEN }}

      - name: files
        working-directory: ./repo-a
        run: |
          echo "hello" > test.txt

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v2
        with:
          path: repo-a
          base: master
          branch: my-auto-update-branch
          token: ${{ secrets.CI_USER_TOKEN }}
          commit-message: auto update
          title: Automatic Updates 
```

But the action errors out with:

```
##[error]Working base branch 'my-auto-update-branch' was created by this action. Unable to continue. Exiting.
```

Thanks so much!

**Comment by peter-evans** [comment]
Hi @geekdave 

> Is there a way to configure the action to make individual commits on the feature branch without force-pushing?

No, there isn't. This is fundamental to how the action works and is a conscious design decision. When a workflow executes the action to _create_ or _update_ a PR, the result of those two actions should not be different, in my opinion. Rebasing the PR branch and adding new commits is the best way to maintain that consistency. I have experimented in the past with trying to keep the full commit history, but it's more trouble than it's worth.

There might be a workaround if you really need the history:

1. Create a workflow that manages the `my-auto-update-branch` branch with git commands in `run` steps
    - Create the branch (if it doesn't exist)
    - Add commits for updates
    - Push to origin
2. Create a separate workflow that uses this action to raise a PR from `my-auto-update-branch` to `master` based on [this example](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another). This should keep the entire commit history of `my-auto-update-branch` each time the PR is created/updated.

**Comment by geekdave** [comment]
Thanks so much @peter-evans - Makes total sense, and I understand the tradeoffs here.  Thanks again for making this action!  It's been super helpful!

**Comment by geekdave** [comment]
@peter-evans thanks again for your suggestions for how to make this workflow able to accumulate commits without changing history.

I gave it a whirl and I hit an issue.  Hoping it's something simple:

```
      - name: Checkout repo-b
        uses: actions/checkout@v2
        with:
          repository: my-org/repo-b
          path: repo-b
          token: ${{ secrets.CI_USER_TOKEN }}

      - name: Checkout or create repo-b update branch
        working-directory: ./repo-b
        run: |
           # Ensure that if auto-tag-updates already exists that it is fetched
           git fetch --prune --unshallow
           git checkout auto-tag-updates || git checkout -b auto-tag-updates

      - name: Update files in repo-b
        working-directory: ./repo-b
        run: |
          make update_image_versions

      - name: Push changes to repo-b update branch
        working-directory: ./repo-b
        run: |
           git config --global user.email "me@my-org.com"
           git config --global user.name "Updater Bot"
           git add .
           git commit -m "bump apiserver image from upstream build: my-org/repo-a@${{ github.sha	}}"
           git push origin auto-tag-updates

      - name: Create or update repo-b pull request with updated image
        uses: peter-evans/create-pull-request@v2
        with:
          path: repo-b
          base: master
          branch: auto-tag-updates
          token: ${{ secrets.CI_USER_TOKEN }}
          title: Automatic Tag Updates from Upstream Repos
          author: "Updater bot <me@my-org.com>"
          body: |
            Update files from upstream builds.
```

The branch gets correctly created or checked out if already exists.  And the branch gets pushed with the correct history.  But when the PR creator plugin runs it fails with:

```
##[error]Working base branch 'auto-tag-updates' was created by this action. Unable to continue. Exiting.
```

I thought that setting `base: master` would help the plugin know what the target was but no use.  Any ideas?

**Comment by peter-evans** [comment]
@geekdave It looks like you've implemented step 1 of the workaround I suggested. Now you need to implement step 2 as in the previously linked example. Note that you cannot use the `auto-tag-updates` branch when raising the PR because that's your managed branch that already exists. 

The idea is that your managed branch, `auto-tag-updates`, will be continually updated as you have already implemented. In the new job I've added below, if a diff exists between `auto-tag-updates` and `repo-b/master`, then a pull request will be created using branch `auto-tag-updates-pr`. The action will update this branch as necessary if there are changes and it's still not merged. You are then free to merge and delete the `auto-tag-updates-pr` whenever you like.

```diff
+jobs:
+ build:
+   runs-on: ubuntu-latest
+   steps:
      - name: Checkout repo-b
        uses: actions/checkout@v2
        with:
          repository: my-org/repo-b
          path: repo-b
          token: ${{ secrets.CI_USER_TOKEN }}

      - name: Checkout or create repo-b update branch
        working-directory: ./repo-b
        run: |
           # Ensure that if auto-tag-updates already exists that it is fetched
           git fetch --prune --unshallow
           git checkout auto-tag-updates || git checkout -b auto-tag-updates

      - name: Update files in repo-b
        working-directory: ./repo-b
        run: |
          make update_image_versions

     - name: Push changes to repo-b update branch
       working-directory: ./repo-b
       run: |
          git config --global user.email "me@my-org.com"
          git config --global user.name "Updater Bot"
          git add .
          git commit -m "bump files from upstream build: my-org/repo-a@${{ github.sha }}"
          git push origin auto-tag-updates

+ createPullRequest:
+   needs: build
+   runs-on: ubuntu-latest
+   steps:
+     - name: Checkout the PR base
+        uses: actions/checkout@v2
+       with:
+         repository: my-org/repo-b
+         token: ${{ secrets.CI_USER_TOKEN }}

+     - name: Apply changes to the base
+       run: |
+         git fetch origin auto-tag-updates:auto-tag-updates
+         git reset --hard auto-tag-updates

      - name: Create or update repo-b pull request with updated image
        uses: peter-evans/create-pull-request@v2
        with:
-         path: repo-b
-         base: master
-          branch: auto-tag-updates
+         branch: auto-tag-updates-pr
          token: ${{ secrets.CI_USER_TOKEN }}
          title: Automatic Tag Updates from Upstream Repos
          author: "Updater bot <me@my-org.com>"
          body: |
            Update files from upstream builds.
```

**Comment by geekdave** [comment]
Worked like a charm.  Thanks as always for your help, @peter-evans !

**Comment by expipiplus1** [comment]
Although not the same as the desired behavior above; for anyone stumbling upon this looking for a way to disable PR updating: It's not too hard to disable the PR step by checking if a PR for that branch already exists. Something like this works well for me:

```yaml
    - id: check_pr
      run: |
        echo "::set-output name=create_pr::true"
        hub pr list --state open --head $owner:$branch --format $'%U\n' | while read u; do
          echo "PR already exists: $u"
          echo "::set-output name=create_pr::false"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

...

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      if: steps.check_pr.outputs.create_pr == 'true'
      ...
```

**Comment by ronlut** [comment]
@peter-evans Sorry for continuing the discussion here, I am just not sure I understood the verdict here.
My case:
I have a [matrix](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) that generates 1 static file per job.
Let's say I have 1 job running with python 2 and another one with python 3.
They generate **different** files: `static/python2.result` and `static/python3.result`.
I want to have 1 PR containing those two changes, but they are created in different jobs (because of the matrix).
Any way to achieve that without doing it manually? I don't care if those changes show in 1 commit or in multiple, I just want to have them both. 
Currently I only get the change from the last (matrix) job - 1 file in the PR instead of 2.

Thanks!

**Comment by peter-evans** [comment]
Hi @ronlut 

This issue is about something a bit different to your use case. If you want to create a PR with the result of multiple jobs I recommend doing something like the following workflow. (Not tested)

```yml
jobs:
  build:
    strategy:
      matrix:
        python: [2, 3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build the static file pythonX.result

      - uses: actions/upload-artifact@v1
        with:
          name: python${{ matrix.python }}.result
          path: python${{ matrix.python }}.result

  createPullRequest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # This will download all artifacts created during the workflow to the root of the repository
      - uses: actions/download-artifact@v1
        with:
          path: .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

**Comment by ronlut** [comment]
@peter-evans Thanks a lot. That works perfectly.

I used one artifact for all files as it makes more sense in my specific case.
Hope my final solution will help someone in the future (stripped down, full version [here](https://github.com/ronlut/jsonperf/blob/master/.github/workflows/generate-web-results.yaml):
```
jobs:
  python-generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [2, 3]
    steps:
      - uses: actions/checkout@v2

      # Generate file

      - uses: actions/upload-artifact@v2
        with:
          path: ./python${{ matrix.version }}.result

  create-pull-request:
    needs: ['python-generate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: artifact
          path: ./generated_results_dir

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```
