### ISSUE TITLE
fatal: ambiguous argument '': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by SamHuoJudiAi** [peter-evans/create-pull-request#1716]
### Subject of the issue

I want to create a pull request from main into a features branch any time a pull request is completed.  However, I get the following error.

![image](https://user-images.githubusercontent.com/106280639/224802786-06802c75-0e16-43c2-b2ff-218d178be17c.png)

### Steps to reproduce

This is my workflow file

```
name: Cherry Pick Branch
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  release_pull_request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cherry Pick
        run: |
          git config --global user.name "xxx"
          git config --global user.email "devops@xxx.xx"
          git checkout myBranch
          git pull
          git checkout -b cherry-pick-${{ github.event.pull_request.number }}
          if git cherry-pick -m 1 ${{ github.event.pull_request.merge_commit_sha }}; then
            echo "Cherry pick successful"
          else
            git cherry-pick --abort
            echo "Cherry pick failed"
            exit 1
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Cherry pick ${{ github.event.pull_request.number }}"
          body: "Cherry pick ${{ github.event.pull_request.number }}"
          branch: cherry-pick-${{ github.event.pull_request.number }}
          base: myBranch
          labels: |
            cherry-pick
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Cherry pick ${{ github.event.pull_request.number }}"
          body: "Cherry pick ${{ github.event.pull_request.number }}"
          branch: ${{ github.event.pull_request.head.ref }}
          base: myBranch
          labels: |
            cherry-pick-conflict
```
