### ISSUE TITLE
Why exisiting commits are removed?

### ISSUE THREAD

**Issue by pawellabaj** [peter-evans/create-pull-request#1828]
### Exisiting commits in branch are removed

I have a branch 'release/v1.2.3' with commits created by maven release:prepare:
* [ci skip] prepare release v1.2.3
* [ci skip] prepare for next development iteration

I have workflow with following step:
```
      - name: Create Pull request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: release/v1.2.3
          commit-message: "build: [ci skip] automated PR"
```

After that, existing commits are removed and not merged into `main` branch, when the PR is merged

**How to keep existing commits in the branch?**

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
My workflow: https://github.com/pawellabaj/auto-record/blob/main/.github/workflows/release-published.yml
