### ISSUE TITLE
I received error '/usr/bin/git'

### ISSUE THREAD

**Issue by ivanrpassos** [peter-evans/create-pull-request#1874]
### Subject of the issue

I received this error to create a new Pull Request
In image has the listed error
![image](https://user-images.githubusercontent.com/62813966/231819559-6e43bc1e-4b87-4928-9b37-1a2d8ffd3376.png)

### My yaml file
This is my first time using GitHub Actions. My yaml file, could be wrong...
```yaml
name: Generate design tokens

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }}
          json: ${{ github.event.client_payload.tokens }}
          dir: 'input'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'style: Update design tokens'
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          body: 'Design tokens have been updated via Figma and need to be reviewed.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
```
