### ISSUE TITLE
[Question] Other Actions are not trigger by PR when using GITHUB_TOKEN

### ISSUE THREAD

**Issue by mietzen** [peter-evans/create-pull-request#1883]
### Subject of the issue

I don't think that this is a Issue, at least not in your Action. But I can't find anything reading this behaviour. 

When I'm using my `Personal Access Token` instead of the `GITHUB_TOKEN` other jobs that are triggered on `pull_request`will be triggered. But when using the `GITHUB_TOKEN` with `peter-evans/create-pull-request@v5` the generated pull request doesn't trigger any other actions that listen on `pull_request`.

Is this expected? 

### Steps to reproduce

Here is an example I'm creating a pull request which starts a approval job so automerge is possible. This only works if the pull request is created using a `Personal Access Token`.

```
jobs:
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          title: '[Github Action Bot] Update'
          commit-message: Update
          committer: GitHub Action Bot <action@github.com>
          author: GitHub Action Bot <action@github.com>
          branch: auto-update
          assignees: mietzen
          labels: |
            automated pr
            update
          body: |
            Updated blocklist
      - name: Automerge if possible
        if: steps.pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          merge-method: squash
```

```
name: Approve Pull Request

on: 
  pull_request:

jobs:
  Approve-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
```
