### ISSUE TITLE
Allow tags to be pushed

### ISSUE THREAD

**Issue by jacobolofsson** [peter-evans/create-pull-request#1913]
### Tags are not pushed

Thanks for a great action!

I am trying to combine this with the commitizen action to automatically bump the version of my repo, but instead of pushing straight to main (default behaviour of commitizen), I want to create a PR that needs to pass some CI checks, and a review.

Commitizen creates a commit (updating changelog etc) and adds a git tag to the commit with the version number (which is then used the next time to calculate the version). But when using this action to create the branch and PR, the tags are not pushed.

### Steps to reproduce

My workflow looks like this:
```yaml
name: Bump version

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.16.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: bump-version-${{ steps.cz.outputs.version }}
          title: Bump version ${{ steps.cz.outputs.version }}
```
The first time it runs, it looks like it works fine, creates the PR like intended (but no tags). The next time it runs commitizen will fail, because there is no tag to parse the previous version number from.

**Comment by peter-evans** [comment]
Hi @jacobolofsson 

I think you can push the tag yourself after the PR has been created. I haven't tested it, but something like this should work.

```yml
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.16.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: bump-version-${{ steps.cz.outputs.version }}
          title: Bump version ${{ steps.cz.outputs.version }}
      - run: |
          git checkout bump-version-${{ steps.cz.outputs.version }}
          git tag ${{ steps.cz.outputs.version }}
          git push origin ${{ steps.cz.outputs.version }}
```
