### ISSUE TITLE
Revison created by action is unkown

### ISSUE THREAD

**Issue by zoedsoupe** [peter-evans/create-pull-request#1914]
### Subject of the issue

After doing a set of changes, when trying to create the PR, it fails as the temporary branch seems not to be created

Here is my aciton:

```yaml
name: Bump peadesafios version

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGEX: v[0-9]+\.[0-9]+\.[0-9]+
  REGEX_CARGO: '[0-9]+\.[0-9]+\.[0-9]+'
  FLAKE: flake.nix
  CARGO: Cargo.toml
  BRANCH_NAME: auto-update/peadesafios
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHOR_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com

jobs:
  bump-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      - name: Get the release version from the tag
        shell: bash
        id: version
        if: env.PEADESAFIOS_VERSION == ''
        run: |
          export new_version=${{ github.ref_name }}
          echo $new_version
          echo "PEADESAFIOS_VERSION=$new_version" >> $GITHUB_ENV
      - name: Get old flake version
        run: |
          export version=$(grep -owE ${{ env.REGEX }} ${{ env.FLAKE }})
          echo "OLD_VERSION_FLAKE=$version" >> $GITHUB_ENV
      - name: Update version in flake.nix
        run: sed -i "s/$OLD_VERSION_FLAKE/$PEADESAFIOS_VERSION/g" ${{ env.FLAKE }}

      - name: Get old Cargo version
        run: |
          export version=$(grep -m 1 -owE ${{ env.REGEX_CARGO }} ${{ env.CARGO }})
          echo $version
          echo "OLD_VERSION_CARGO=$version" >> $GITHUB_ENV
      - name: Update version in Cargo.toml
        run: |
          export new_version="$(echo $PEADESAFIOS_VERSION | cut -c2-)"
          sed -i "0,/$OLD_VERSION_CARGO/s//$new_version/" ${{ env.CARGO }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Build to generate new Cargo.lock with new version
        run: cargo build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "update: flake and cargo package version"
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          title: 'peadesafios: ${{ env.OLD_VERSION_FLAKE }} -> ${{ env.PEADESAFIOS_VERSION }} '
          branch: ${{ env.BRANCH_NAME }}
          signoff: true
          delete-branch: true
          labels: automerge
          assignees: zoedsoupe
          reviewers: zoedsoupe

      - name: Auto Merge PR
        id: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
```

### Steps to reproduce

1. checkout a repo in a action
2. make changes
3. try to create a PR

Beloy the full log can be found:

```sh
Prepare git configuration
  /usr/bin/git config --global --name-only --get-regexp safe.directory /home/runner/work/desafios/desafios
  /usr/bin/git config --global --add safe.directory /home/runner/work/desafios/desafios
  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader
  /usr/bin/git config --local --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
  Unset config key 'http.https://github.com/.extraheader'
Determining the base and head repositories
  /usr/bin/git config --local --get remote.origin.url
  https://github.com/peapescarte/desafios
Pull request branch target repository set to peapescarte/desafios
Configuring credential for HTTPS authentication
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git rev-parse --git-dir
  .git
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  heads/main
  Working base is branch 'heads/main'
  /usr/bin/git remote prune origin
Pull request branch to create or update set to 'auto-update/peadesafios'
Configuring the committer and author
  Configured git committer as 'GitHub <noreply@github.com>'
  Configured git author as 'peapescarte <peapescarte@users.noreply.github.com>'
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  heads/main
  Working base is branch 'heads/main'
  /usr/bin/git checkout --progress -B 6ea65cf9-1651-480c-be08-c2dae5b4abb8 HEAD --
  Switched to a new branch '6ea65cf9-1651-480c-be08-c2dae5b4abb8'
  M	cli/Cargo.lock
  M	cli/Cargo.toml
  M	cli/flake.nix
  /usr/bin/git status --porcelain -unormal --
   M cli/Cargo.lock
   M cli/Cargo.toml
   M cli/flake.nix
  Uncommitted changes found. Adding a commit.
  /usr/bin/git add -A
  /usr/bin/git -c author.name=peapescarte -c author.email=peapescarte@users.noreply.github.com -c committer.name=GitHub -c committer.email=noreply@github.com commit -m update: flake and cargo package version --signoff
  [6ea65cf9-1651-480c-be08-c2dae5b4abb8 dc86b4a] update: flake and cargo package version
   Author: peapescarte <peapescarte@users.noreply.github.com>
   3 files changed, 3 insertions(+), 3 deletions(-)
  /usr/bin/git stash push --include-untracked
  No local changes to save
  Resetting working base branch 'heads/main'
  /usr/bin/git checkout --progress heads/main --
  Note: switching to 'heads/main'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 16b44af corrige workflow para atualização de versões
  /usr/bin/git reset --hard origin/heads/main
  fatal: ambiguous argument 'origin/heads/main': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: The process '/usr/bin/git' failed with exit code 1[28](https://github.com/peapescarte/desafios/actions/runs/4833633094/jobs/8613868707#step:10:29)
```
