### ISSUE TITLE
Action says master is up-to-date with branch and it doesn't create PR...

### ISSUE THREAD

**Issue by 403-html** [peter-evans/create-pull-request#1933]
### Subject of the issue

Action says master is up-to-date and it doesn't create PR... but I dev branch I checkout from has changes. What I can miss?

It's last few lines of code output from below
```sh
Branch 'release/v2.45.0-rc1' no longer differs from base branch 'master'
Restore git configuration
Run echo "PR number: "
PR number: 
PR url: 
Run echo "PR creation failed" && exit 1
```

### Steps to reproduce

```yml
name: Release
description: it's release!

inputs:
  token:
    description: 'Secret GH token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: dev
        fetch-depth: 0
   # Some actions connected to calculating release etc
    - name: Create branch
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git checkout -b release/v${{ env.version }}-rc${{ inputs.candidate }} dev
        git push origin release/v${{ env.version }}-rc${{ inputs.candidate }}
    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.token }}
        commit-message: 'chore: release v${{ env.version }}-rc${{ inputs.candidate }}'
        title: 'Release candidate v${{ env.version }}-rc${{ inputs.candidate }}'
        branch: release/v${{ env.version }}-rc${{ inputs.candidate }}
        base: master
    - name: Print details about release PR
      shell: bash
      run: |
        echo "PR number: ${{ steps.cpr.outputs.pull-request-number }}"
        echo "PR url: ${{ steps.cpr.outputs.pull-request-url }}"
    - name: Fail if PR creation failed
      shell: bash
      if: steps.cpr.outputs.pull-request-number == ''
      run: echo "PR creation failed" && exit 1
```
