### ISSUE TITLE
Cannot create a simple PR

### ISSUE THREAD

**Issue by fieldsfarmer** [peter-evans/create-pull-request#1935]
### Subject of the issue

I follow the example but still could not create a simple PR

### Steps to reproduce

My workflow

```
name: Test create-pull-request
on:
  # Configuring a workflow to run manually
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.XXX_TOKEN }}

permissions:
  contents: write

jobs:
  test:
    runs-on: [self-hosted, celostar]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: dummy
        run: |
          echo "hello" >>  dummy.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Test
          title: Test
          body: Test
          branch: kw-rb2
          base: kw-rb
          assignees: fieldsfarmer
          reviewers: fieldsfarmer
```
However it automatically forced pushed the change without any PR. I wish it could create a PR so that I could review it. I saw it the step in the log:

```
Pushing pull request branch to 'origin/kw-rb2'
  /usr/bin/git push --force-with-lease origin kw-rb2:refs/heads/kw-rb2
  To https://github.com/<repo>
   + b112c7e95...9face9e22 kw-rb2 -> kw-rb2 (forced update)
Branch 'kw-rb2' no longer differs from base branch 'kw-rb'
```
How to create a PR so that one could review it?
