### ISSUE TITLE
Fail creating a Pull Request in a different repository

### ISSUE THREAD

**Issue by jparisu** [peter-evans/create-pull-request#1956]
### Subject of the issue

I am trying to use this action to create a new Pull Request in a different repository than the one running the workflow.

### Steps to reproduce

I am building a centralize repository with CI actions for my organization, and I wanted to have some common resources in it.
I wanted to do a workflow that open PRs in different repositories of the organization if one of these resources changed.
To do so, I was trying to use this action as follows:

```yaml
# From eProsima/eProsima-CI
# .github/workflows/pr_test.yml

...

  test-external-pr:
    runs-on: ubuntu-22.04
    steps:

      - name: Sync repository
        uses: eProsima/eProsima-CI/external/checkout@feature/shared_resources
        with:
          path: ${{ github.workspace }}
          repository: eProsima/Fast-DDS-spy

      - name: Add file
        run: echo "some text" > ${{ github.workspace }}/test_file.txt

      - name: Try to create Pull Request
        id: open-pr
        uses: eProsima/eProsima-CI/external/create-pull-request@feature/shared_resources
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.workspace }}
          commit-message: "Auto generated commit"
          branch: eprosima-ci/test-branch
          base: main
```

This workflow is failing with following message: 

```sh
   /usr/bin/git push --force-with-lease origin eprosima-ci/test-branch:refs/heads/eprosima-ci/test-branch
  remote: Permission to eProsima/Fast-DDS-spy.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/eProsima/Fast-DDS-spy/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```

### Permissions

I checked already that both, my repository and my organization have permissions to create PRs from bots.
I also use the `${{ secrets.GITHUB_TOKEN }}` token so it should have permissions to create PRs inside the same organization.

### Reference to the issue

This is the workflow failing:
https://github.com/eProsima/eProsima-CI/actions/runs/4948311647/jobs/8848851947
