### ISSUE TITLE
Want to automate creation of a PR on behalf of a user

### ISSUE THREAD

**Issue by exosyphon-rxrevu** [peter-evans/create-pull-request#1971]
This is more of a request on using the API after struggling for several hours.

Is it possible to have someone push to a branch and then open a PR on behalf of that user? 

Here is what I have so far and it doesn't reflect the changes on the original commit. Any guidance would be very appreciated, thank you!

```
name: Create PR

on:
  push: 
    branches-ignore: 
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            title: ${{github.ref_name}}
            token: ${{secrets.TOKEN}}
            body: |  
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request
            base: main
            branch: ${{github.ref_name}}
```

**Comment by peter-evans** [comment]
Hi @exosyphon-rxrevu 

You can change the `committer` and `author` for the commit using [inputs](https://github.com/peter-evans/create-pull-request#action-inputs).

Additionally, if you want the PR to be created by a specific user then the PAT must be created on that user and passed to the `token` input.

Let me know if you need further help.

**Comment by fregante** [comment]
Judging by https://github.com/cli/cli/discussions/6575, the automatic GITHUB_TOKEN generated by GitHub can be used to create pull requests. This means it will likely create a PR "authored by GitHub Actions", which is what I'd like to see for such automated PRs. 

This is what I'd need this action to accept:

- custom PAT to push commits, this will trigger the `push` event in the workflows
- automatic GITHUB_TOKEN to create PRs, this won't trigger the `pull_request` event but that's usually duplicate anyway.

**Comment by peter-evans** [comment]
Hi @fregante 

I've made your suggestion possible in the next major version of the action. You can test it like this:

```yml
      - uses: peter-evans/create-pull-request@v6-rc
        with:
          git-token: token: ${{ secrets.PAT }}
```
Just leave the `token` input unset and it will use the default `GITHUB_TOKEN` for creating the PR.

I'll be releasing `v6` at some point in the near future.
