### ISSUE TITLE
PAT token github actions still not triggering

### ISSUE THREAD

**Issue by MartinDawson** [peter-evans/create-pull-request#2006]
I've read: https://github.com/peter-evans/create-pull-request/issues/48

And I'm using a PAT token for the automated PR. However the new actions based on that PR never get triggered even though I am using PAT and not GITHUB_TOKEN.

### Steps to reproduce

The workflow is this:

Commit pushed to release/minor_patch -> triggers the `peter-evans/create-pull-request` to raise a PR to release/major -> auto approved and merged into release/major -> SHOULD then trigger github actions but does NOT

post-minor-push.yml
```yml
name: Post minor push

on:
  push:
    branches:
      - release/minor_patch

jobs:
  # Adapted from https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md
  merge_release_minor_patch_to_release_major:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release/major

      - name: Reset promotion branch
        run: |
          git fetch origin release/minor_patch:release/minor_patch
          git reset --hard release/minor_patch

      - name: Create release/minor_patch PR -> release/major
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/major_merge_promotion
          delete-branch: true
          # Needed to run actions automatically after the bots PR is merged
          # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
          token: ${{ secrets.GH_TOKEN }}

      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_PAT }}

      - name: Enable Pull Request Automerge
        run: gh pr merge release/major_merge_promotion --squash --auto
        env:
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_PAT }}
```

Release.yml:

```yml
name: Release

on:
  push:
    branches: [main, release/major, release/minor_patch]

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16.19.1'
          always-auth: true

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn run semantic-release
        env:
          HUSKY: 0
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: : ${{ secrets.REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.CONTAINER_REPOSITORY }}:latest
```

Post minor push is triggered but not the `release.yml` push actions:

![Screenshot from 2023-05-25 21-50-46](https://github.com/peter-evans/create-pull-request/assets/15030491/6cdefb37-1c55-4c72-8403-7a82976707e6)

I'm extremely confused and stuck on this for hours.

**Comment by peter-evans** [comment]
Hi @MartinDawson 

It's not clear to me which part of your workflow is not working. When you create the pull request you are using `GH_TOKEN`. Does the new pull request trigger all the necessary workflows/checks to run for the PR branch?

Assuming it's auto-merging fine after the PR checks run, the "actor" triggering the `Release` workflow should be the user associated with the `AUTO_APPROVE_PAT` token. Is `AUTO_APPROVE_PAT` a fine-grained token, by any chance? If so, that could be your problem. Fine-grained tokens do not work (or have full support yet) in some situations.

**Comment by MartinDawson** [comment]
@peter-evans Thanks for the fast reply.

The automated PR that gets created does indeed run all of the workflow checks just fine, i.e it runs this part:

```yml
on:
  push:
    branches:
      - release/minor_patch
```

However the issue happens when that automated PR gets merged into the release/major branch. I would expect the workflows to be triggered for the release/major due to part of the yml file:

```yml

on:
  push:
    branches: [main, release/major, release/minor_patch]
```

But the worksflows never get triggered when merging the PR into release/major.

> Assuming it's auto-merging fine after the PR checks run

Yes, auto merge works fine (after we fix any conflicts).

> the "actor" triggering the Release workflow should be the user associated with the AUTO_APPROVE_PAT token.

The AUTO_APPROVE_PAT token is my token and it is a `classic token`, NOT a fine grained token.

So I seem to have done everything the docs say on this.
