### ISSUE TITLE
Adding existing labels to existing PR fails

### ISSUE THREAD

**Issue by mruoss** [peter-evans/create-pull-request#2007]
### Subject of the issue

If I use this action with the `labels` option set, it fails when updating an existing PR because it already contains the label(s).

### Steps to reproduce

Use something like this and update an existing PR:

```
      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with: 
          branch: some-branch
          base: main
          delete-branch: true
          title: 'My fancy PR with labels'
          body: |
           Labels demo
          draft: false
          labels: |
            some-label
```
