### ISSUE TITLE
Having issues creating PR on a server that is not github.com

### ISSUE THREAD

**Issue by mattinger** [peter-evans/create-pull-request#2020]
My definitions is as follows.  The repository was checked out from our enterprise github server (not github.com), so I know there's connectivity.

```
      - name: commit-and-push-with-pr
        uses: peter-evans/create-pull-request@v5
        if: ${{ inputs.create-pull-request }}
        with:
          token: ${{ steps.set-github-env.outputs.github_token }}
          path: code
          add-paths: "${{ inputs.resource-path }}/**/${{ inputs.localizable-strings-filename }} ${{ inputs.localizable-string-path }}/${{ inputs.localizable-swift-filename}}"
          base: main
          branch: ${{ inputs.commit-branch }}
          commit-message: 'Sync ${{ github.workflow }} strings from S3'
          title: 'CMS Strings update: ${{ github.workflow }}'
          body: 'Sync ${{ github.workflow }} strings from S3'
```

I've validated that GITHUB_SERVER_URL is correct:

```
env:
    GITHUB_SERVER_URL: https://github.xxxxx.com/    
```

Yet when it comes time to push the PR it's failing with this message:

```
usr/bin/git config --local --get remote.origin.url
  https://github.xxxxx.com/org/repo
  Error: The format of 'https://github.xxxxx.com/org/repo' is not a valid GitHub repository URL
```

Based on looking at utils.js, it should be picking up the GITHUB_SERVER_URL variable and validating the local git config against that, but for whatever reason it doesn't seem to working correctly.

The same workflow works on github.com repositories, and i can commit using `stefanzweifel/git-auto-commit-action@v4` for cases where the user doesn't want a PR created, so it's not a permissions issue.

**Comment by peter-evans** [comment]
Hi @mattinger 

I think the issue is the trailing `/` on the server URL. Please try this:

```yml
env:
    GITHUB_SERVER_URL: https://github.xxxxx.com
```

If this is the problem then I'll add a fix to remove trailing slashes.

**Comment by mattinger** [comment]
I double checked, and we are not using a trailing slash:

```
      - name: set-github-env
        id: set-github-env
        run: |
          github_token=...
          github_server=${{ inputs.is-ghec && 'https://github.com' || 'https://github.xxxxx.com' }}
          echo "github_token=$github_token" >> $GITHUB_OUTPUT
          echo "github_server=$github_server" >> $GITHUB_OUTPUT

      - name: git-pull
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          submodules: false
          token: ${{ steps.set-github-env.outputs.github_token }}
          github-server-url: ${{ steps.set-github-env.outputs.github_server }}
          fetch-depth: 1
          ref: main
          path: code
```

**Comment by mattinger** [comment]
Even with the env set directly, it is still failing with the same error:

```
env:
    GITHUB_SERVER_URL: https://github.xxxxx.com/
/usr/bin/docker exec  ff8985654e26e352559a497a935082ba3f3dc8ac85f239defdc7bafcf275902c sh -c "cat /etc/*release | grep ^ID"
Prepare git configuration
Determining the base and head repositories
  /usr/bin/git config --local --get remote.origin.url
  https://github.xxxxx.com/org/repo
  Error: The format of 'https://github.xxxxx.com/org/repo' is not a valid GitHub
```

**Comment by mattinger** [comment]
I'm guessing maybe this is a scoping issue @peter-evans ?   Is `process.env` actually reading from the `env` block of the action, or is that a higher level thing that's set by the action itself?  Because i'm actually executing this action on one server, and pushing a commit to another.

**Comment by peter-evans** [comment]
My guess is that `GITHUB_SERVER_URL` is not getting set correctly, so the action just uses the default, `https://github.com`. It would be helpful to see your entire workflow to understand this better.

Are you setting the env on the action like this? If not, please try it.

```yml
      - name: commit-and-push-with-pr
        uses: peter-evans/create-pull-request@v5
        if: ${{ inputs.create-pull-request }}
        env:
          GITHUB_SERVER_URL: https://github.xxxxx.com
        with:
          token: ${{ steps.set-github-env.outputs.github_token }}
          path: code
          add-paths: "${{ inputs.resource-path }}/**/${{ inputs.localizable-strings-filename }} ${{ inputs.localizable-string-path }}/${{ inputs.localizable-swift-filename}}"
          base: main
          branch: ${{ inputs.commit-branch }}
          commit-message: 'Sync ${{ github.workflow }} strings from S3'
          title: 'CMS Strings update: ${{ github.workflow }}'
          body: 'Sync ${{ github.workflow }} strings from S3'
```

**Comment by mattinger** [comment]
Yes i'm setting it like that, though i'm using the output from another step:


```
      - name: set-github-env
        id: set-github-env
        run: |
          github_token=${{ inputs.is-ghec && secrets.SVC_SERVICEACC_GHEC_TOKEN || secrets.SVC_SERVICEACC_GHES_TOKEN }}
          github_server=${{ inputs.is-ghec && 'https://github.com' || 'https://github.xxxxx.com' }}
          echo "github_token=$github_token" >> $GITHUB_OUTPUT
          echo "github_server=$github_server" >> $GITHUB_OUTPUT

      - name: commit-and-push-with-pr
        uses: peter-evans/create-pull-request@v5
        if: ${{ inputs.create-pull-request }}
        env:
          GITHUB_SERVER_URL: ${{ steps.set-github-env.outputs.github_server }}
        with:
          token: ${{ steps.set-github-env.outputs.github_token }}
          path: code
          add-paths: "${{ inputs.resource-path }}/**/${{ inputs.localizable-strings-filename }} ${{ inputs.localizable-string-path }}/${{ inputs.localizable-swift-filename}}"
          base: main
          branch: ${{ inputs.commit-branch }}
          commit-message: 'Sync ${{ github.workflow }} strings from S3'
          title: 'CMS Strings update: ${{ github.workflow }}'
          body: 'Sync ${{ github.workflow }} strings from S3'

```

As i said, is suspect that the `process` scope that's getting used in utils.js is set by the github actions runner, not by the task's `env` block.  I'm going to attempt to write a quick and dirty action to see if this theory is correct.
