### ISSUE TITLE
Exclude files from "Keep a branch up-to-date with another"

### ISSUE THREAD

**Issue by wiebekaai** [peter-evans/create-pull-request#2063]
### Exclude files from "Keep a branch up-to-date with another"

I'm using the [Keep a branch up-to-date with another](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another) example. One thing I would like differently is to checkout some config files from the original, because those need to be in git but never overwritten by the incoming patches. I have no clue which config files it's getting, but definitely not the original ones. Am I missing something?

Any help is highly appreciated!

```
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.store.branch }}
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Restore config files
        run: |
          git checkout origin/${{ matrix.store.branch }} -- config/**
          git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          commit-message: 'chore: restore config files ✨'
          title: 'Deploy to ${{ matrix.store.store }} ${{ matrix.store.flag }}'
          body: 'Deploy to ${{ matrix.store.store }} ${{ matrix.store.flag }}'
          branch: patch/${{ matrix.store.branch }}
          delete-branch: true
```
