### ISSUE TITLE
Make the action useful in the upmerge scenario

### ISSUE THREAD

**Issue by jakubtobiasz** [peter-evans/create-pull-request#2097]
### Subject of the issue

Hello,
I wanted to use this in the upmerge scenario.

1) Checkout lower branch (in my case `1.12`)
2. Create new branch (in my case `upmerge/1.12_1.13_<commit_short_hash>`)
3. Create a PR

No additional commit is added in the workflow, I just want to create a PR with commits added to lower branch.

I wanted to use the `create-pull-request` action, but from what I see it includes only commits done within the workflow run. I can open a PR, in which I'll add an option allowing to push both changes made in the workflow run and diff between the currently checked out branch. I'd like to only know if such a feature is ok for you @peter-evans 🤔?

If there's a way to achieve my scenario, just let me know :).

**Comment by peter-evans** [comment]
Hi @jakubtobiasz 

I think for this use case you can follow this example: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

Something like this:
```yml
jobs:
  upmerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Reset upmerge branch
        run: |
          git fetch origin 1.12:1.12
          git reset --hard 1.12
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: upmerge/1.12_1.13_<commit_short_hash> # get the hash in separate step
```
