### ISSUE TITLE
Author Ignored when Token Specified

### ISSUE THREAD

**Issue by sp71** [peter-evans/create-pull-request#2107]
### Subject of the issue

Whenever `token` field is specified, the author information is ignored. The PR's author will be the name associated with the token

### Steps to reproduce

```
- name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ env.GH_ACCESS_TOKEN }}
          commit-message: 'Auto-generated PR'
          committer: John Doe <john@company.com>
          author: John Doe <john@company.com>
          title: 'Automate'
          branch: 'custom'
          base: 'main'
          body: |
            _Pull Request is auto generated_
```
