### ISSUE TITLE
Action fetches working branch from target remote and results in couldn't find remote ref

### ISSUE THREAD

**Issue by pierDipi** [peter-evans/create-pull-request#2108]
### Subject of the issue

I'm debugging this workflow: https://github.com/openshift-knative/hack/blob/main/.github/workflows/release-generate-ci.yaml (latest run https://github.com/openshift-knative/hack/actions/runs/5443007629/jobs/9898976677)

The basic idea of the workflow is:

- checkout an upstream repository, the default branch `master`
- create a new branch `X` starting from `master`
- make some changes with a few commits to `X`
- create a PR using `X` and the fork, targeting the upstream repository, in particular the `master` branch

This is the action configuration:
```yaml
      - name: Create Pull Request
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SERVERLESS_QE_ROBOT }}
          path: ./src/github.com/openshift-knative/hack/openshift/release
          base: master
          branch: sync-serverless-ci
          title: "Sync Serverless CI"
          commit-message: "Sync Serverless CI"
          push-to-fork: serverless-qe/release
          delete-branch: true
          body: |
            Sync Serverless CI using openshift-knative/hack.
```

However, during the `Create or update the pull request branch` phase, the action is fetching the branch `X` (aka working branch) from the target remote repository which I wasn't expecting since that's the local branch the workflow is using and it doesn't exist remotely in the _target_ repository, I was expecting it to fetch the configured `base` branch from the target repository rather than the working branch (which is what is done at [1]).

```
Resetting working base branch 'sync-serverless-ci'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin sync-serverless-ci:sync-serverless-ci
```

I think, it is going through this `if` condition:

https://github.com/peter-evans/create-pull-request/blob/153407881ec5c347639a548ade7d8ad1d6740e38/src/create-or-update-branch.ts#L180-L185

which was added as part of `perf: git reset instead of fetch`, commit: https://github.com/peter-evans/create-pull-request/commit/249b80db6b77804d45b43fae91318b9921893acb

---

[1]
https://github.com/peter-evans/create-pull-request/blob/153407881ec5c347639a548ade7d8ad1d6740e38/src/create-or-update-branch.ts#L193-L220

### Steps to reproduce

See above description + workflow link and run
