### ISSUE TITLE
Branch 'create-pull-request/patch' no longer differs from base branch 'staging'

### ISSUE THREAD

**Issue by luizguilhermefr** [peter-evans/create-pull-request#2178]
### Subject of the issue

Hello 👋 

I am trying to use this action in my project, but I am struggling a bit with it.

I have two branches:

- staging (the main one, for development)
- master (production deployments)

Whenever I merge anything from **staging** to **master**, I trigger the following workflow:

- Bump the version (using https://github.com/phips28/gh-action-bump-version)
  - It increments the version and **commits** directly to master
- Deploy to production
- Open a PR back to staging, with the updated version that is on master

However, the last step is not working.

It is giving me the message `Branch 'create-pull-request/patch' no longer differs from base branch 'staging'`. I am afraid that's because the bump version is committed, therefore the workspace is not dirty.

➡️ Is it possible to simply open a PR with base X and target Y **without** doing any push to any branch?

My workflow file below, which is invoked after the bump version:

```yml
name: Sync-back master -> staging

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: 'peter-evans/create-pull-request@v5'
        with:
          base: staging
          title: Sync-back master -> staging
```
