### ISSUE TITLE
The action behavior differently 

### ISSUE THREAD

**Issue by cris-m** [peter-evans/create-pull-request#2223]
### Subject of the issue
The action is merging `main` branch code into `developer` and I can see any pull request on the repo.
### Steps to reproduce
Here is my action:
```yml
name: Development workflow
on:
  push:
    branches:
      - developer
create-pull-request:
    needs: test-uipath-published-package
    runs-on: ubuntu-latest
    steps:
name: Check out repository code
      uses: actions/checkout@v2
name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        delete-branch: false
        base: main 
        branch: developper 
        title: New Pull Request from Developper
        body: This is a new pull request from the developper branch.
        labels: |
          report
          automated pr
        draft: false
```

I am seeing the following line in the log:
`Pushing pull request branch to 'origin/developer'`.

After executing the action, I can see the source code in `developer` branch was changed. There is no pull request in `pull requests` tab. I cannot even see any merge
