### ISSUE TITLE
Unable to create new PR from old branch

### ISSUE THREAD

**Issue by subhroacharjee** [peter-evans/create-pull-request#2294]
### Subject of the issue
Unable to create **new PR** from an branch for which a PR exists for a _different base branch_.
### Describe your issue here.
While setting up a workflow which is supposed to create a PR to main whenever there is PR created to stable, i encountered this issue that it is not creating new PR to main as base branch but rather closing the existing PR to stable branch.
### Steps to reproduce
```yaml
name: Propagation
on:
  pull_request:
    types:
      - opened
jobs:
  propagation:
    if:  github.event.pull_request.base.ref == 'stable'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
          base: main
          title: "${{ github.event.pull_request.title }} [Base:Main]"
          body: ${{ github.event.pull_request.body }}
```
If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
https://github.com/suuubro/github-test-app/actions/runs/6034686473/job/16373564182
