### ISSUE TITLE
unable to create pull request due to cherry-picker error

### ISSUE THREAD

**Issue by cris-m** [peter-evans/create-pull-request#2341]
### Subject of the issue
I am getting stuck with create pull request problem related to `cherry-pick `.
Describe your issue here.
It seems that there on `Create or update the pull request branch` step here is my action:
```yml
  create-pull-request:
    needs: test-uipath-published-package
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
              ref: developer

      - name: Reset development branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: developer
```

<img width="1407" alt="Screenshot 2023-09-14 at 21 38 47" src="https://github.com/peter-evans/create-pull-request/assets/29815096/70b248e5-e3c6-41df-829a-1a205005f2bb">
