### ISSUE TITLE
Support commenting on a PR when closing it

### ISSUE THREAD

**Issue by bgilbert** [peter-evans/create-pull-request#2415]
### Subject of the issue

create-pull-request doesn't comment on a PR when closing it.  While it's possible to infer why the PR was closed, it'd be great if there were a way to configure some comment text to post to the PR.

**Comment by peter-evans** [comment]
Hi @bgilbert 

There is only one case where the action causes a pull request to close. That is when there is no longer a diff with the base branch. The action updates the PR branch and when GitHub sees that it has no diff anymore GitHub automatically closes the PR.

If you want to handle this case and add a comment in the PR, this is how I would recommend achieving it.

```yml
permissions:
  pull-requests: write

...

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5

      - if: steps.cpr.outputs.pull-request-operation = 'closed'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: Pull request was closed because there was no longer a diff with the base branch.
```
