### ISSUE TITLE
Commit author is `web-flow`?

### ISSUE THREAD

**Issue by Jamesking56** [peter-evans/create-pull-request#2432]
### Commit author is `web-flow`?

When we use this action to make a PR, even when we set `author`, the commit author appears to be set to `web-flow`? We have no idea where this comes from:

![image](https://github.com/peter-evans/create-pull-request/assets/253237/9c0277cb-097f-48d3-94b0-345d12465e7b)

### Steps to reproduce

Here's out workflow config:

```yaml
- uses: peter-evans/create-pull-request@v5
  with:
    author: "GitHub <noreply@github.com>"
    branch: update-symfony
    commit-message: Update Symfony
    delete-branch: true
    body: |
      Created automatically by `.github/workflows/update-symfony.yml`

      This PR will be automatically updated daily if there are more changes.

      > **Warning**
      > Closing this PR without merging in the changes will cause it to regenerate tomorrow
    # Required due to GitHub's restriction of stopping GitHub Actions workflows triggering other workflows
    # https://github.com/orgs/community/discussions/25702
    token: ${{ secrets.XXXX }}
    title: Update Symfony
```
