### ISSUE TITLE
Commit message not updated when PR is updated

### ISSUE THREAD

**Issue by M1kep** [peter-evans/create-pull-request#2460]
### Subject of the issue

It seems whenever a an existing PR/Branch is updated via the create-pull-request action the commit message and PR title is not updated.

### Steps to reproduce

I'm using a workflow with these two steps:
```
      - name: Update Version
        id: update_version
        env:
          GRAPHQL_API_TOKEN: ${{ secrets.SOME_SECRET }}
          GRAPHQL_API_ENDPOINT: "<SOME_ENDPOINT>"
        run: ./ci-scripts/update_version.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "[auto] Update version to ${{ steps.update_version.outputs.LATEST_VERSION }}"
          title: "Update version to ${{ steps.update_version.outputs.LATEST_VERSION }}"
          body: "Automated version bump."
```
 
This results in a PR with force pushes whenever there's a new change, but leaves PR title and more importantly the commit message as the original message. In the photo you can see the force pushes, but the latest version has actually moved to 7.145 which is not reflected in the messages.
![CleanShot 2023-10-19 at 14 19 38](https://github.com/peter-evans/create-pull-request/assets/2661819/d297822d-638c-406f-9157-826a738c536c)
