### ISSUE TITLE
Add no-verify option because rm -rf .git/hooks doesn't work

### ISSUE THREAD

**Issue by nealeu** [peter-evans/create-pull-request#2502]
I searched for existing solutions and found the previous request got directed to https://github.com/peter-evans/create-pull-request/pull/1875#issuecomment-1521008361

So I tried as suggested and found the hooks still run.

If I add `ls -la` to my workflow before the `rm -rf .git/hooks` (note `rm .git/hooks -rf` is the better habit to avoid typo deletions), then I find the directory is there, but just has the `.sample` hooks.

### Workaround (This, I think should be preferred to the `rm .git/hooks -rf` option)
Add the following at the beginning of hook scripts:

```sh
#!/bin/sh

[ -n "$CI" ] && exit 0

# the action e.g. npm run lint-staged or npm run test
```

### Steps to reproduce

On some repo with pre-push or pre-commit hooks (naturally ignore the redundant commit-message, but that's what I had grabbed from your sample)

```yaml
      - name: Commit changes
        run: |
          ls -la .git/hooks
          rm -rf .git/hooks
          git config --global user.name "changelog-updater"
          git config --global user.email "me@somewhere.com"
          git add .
          git commit -m "[auto] Update types from OpenAPI"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
```
