### ISSUE TITLE
Is it possible to fully restore all git state after the action?

### ISSUE THREAD

**Issue by glasser** [peter-evans/create-pull-request#2547]
### Subject of the issue

I'm looking to use this action multiple times in a workflow to create a bunch of PRs for different parts of one change. That is, my workflow will run a command that changes a bunch of files, and then use this action multiple times with `add-paths` (and explicit `branch`) to create a few different PRs so that different people can apply the change to different parts of the tree.

This actually works really well, as long as the paths are all fully disjoint: the workflow will commit the specified files to the temporary branch, stash the other files, make the PR, and restore the stashed files.

However, in some cases I might want the add-paths to overlap.  eg, maybe I will make one PR that's "merge all of the changes to the whole repo as one PR", a set of PRs that are per top-level directory, and a set of PRs that are per second-level directory.  Depending on the level of granularity and care that is required, you can merge any set of PRs; when the workflow runs again it will helpfully close any other PRs that are now redundant.

The overall `create-pull-request` model supports this, but because the changes in `add-paths` paths vanish after a call to `create-pull-request`, I can't create these overlapping PRs in a simple way.

As a workaround, I can run `git stash` after setting up my file state, and then before each call to this action I can run ` git restore --source=stash@{0} -- FILES FOR THIS PR`, and then not use `add-paths`. But it would be nice if the action just had a flag that essentially made it do this for me.

If nothing else, I'm not sure that the docs actually explain anywhere that the effect on your local git state is that you will end up back with the same branch checked out with the same commit as before you ran it, with the files matched by `add-paths` reset to their state from the commit, and all other local changes preserved. It's sort of implied by the `add-paths` documentation, but not explicitly.

### Steps to reproduce

Run this workflow:

```
name: Make multiple PRs

on: workflow_dispatch

jobs:
  make-multiple-prs:
    concurrency: only-one-at-a-time
    runs-on: ubuntu-latest
    permissions:
      # Give GITHUB_TOKEN permissions to push.
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Write some files
        run: |
          echo "# another line" >>another.yaml
          echo "# more" >>values.yaml
  
      - name: Create Pull Request for another.yaml
        uses: peter-evans/create-pull-request@v5
        with:
          branch: create-pull-request/for-another.yaml
          add-paths: another.yaml
          delete-branch: true
          title: "PR for another.yaml"

      - name: Create Pull Request for values.yaml
        uses: peter-evans/create-pull-request@v5
        with:
          branch: create-pull-request/for-values.yaml
          add-paths: values.yaml
          delete-branch: true
          title: "PR for values.yaml"

      - name: Create Pull Request for all
        uses: peter-evans/create-pull-request@v5
        with:
          branch: create-pull-request/for-all
          delete-branch: true
          title: "PR for all"
  ```

You'll end up with PRs for the individual files but no PR for "all".
