### ISSUE TITLE
Deep fetch results in massive download

### ISSUE THREAD

**Issue by stephen-strava** [peter-evans/create-pull-request#2579]
### Subject of the issue

My workflow is straightforward, containing this step:
```
      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: <branch>
          committer: <comiter>
          commit-message: <message>
          title: <title>
          body: <body>
          token: <token>
```

This workflow can run multiple times and force pushes; so it may update an existing branch/pr. When run, I see this line executed:
```
/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin <my-repo>
```
After which a very large remote pull takes place, _sometimes_. This can lead to the run taking 2 minutes at the short version and up to 40 minutes in our case for the complete pull.

The thought is that perhaps this should be using `--depth=1` in some cases (rather than `--unshallow`)

Looking at
https://github.com/peter-evans/create-pull-request/blob/f5ba48ac1e522e5e1b7b04e2ea86f584e5bf4704/src/git-command-manager.ts#L119
Which is called from
https://github.com/peter-evans/create-pull-request/blob/main/src/create-or-update-branch.ts#L189

The code in there is nuanced enough that it's not clear why we need to do a full fetch in the case that we are pushing to an existing PR.
