### ISSUE TITLE
Question about Repository  

### ISSUE THREAD

**Issue by seyedeliasfakoorian** [peter-evans/create-pull-request#2594]
I have a question, for the action of create-pull-request, can we use the token `secrets.GITHUB_TOKEN`
for the workflow action? Or the token `secrets.PAT`? I use the token `secrets.GITHUB_TOKEN` for my repository.

```yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: github-actions
          commit-message: Fix Heroku Vulnerabilities
          delete-branch: true
          labels: |
           github actions
          reviewers: seyedeliasfakoorian
          title: Fix Heroku Vulnerabilities
          body: |
            This pull request can fix vulnerabilities when Heroku has an issue deploying or needs to check logs🚀
            🌎 [View Site](https://website-breaker-demo-2e92fbab7def.herokuapp.com/)
```
