### ISSUE TITLE
Failing to create PR

### ISSUE THREAD

**Issue by NirFrankel** [peter-evans/create-pull-request#2682]
This was workflow was working fine a few days ago and recently started to break. Throwing the same username error, even though no changes have been made to the workflow or the repo.

Attempts to fix:
- Hardcoding the security token (no luck)
- Pruning in stage before (was suggested on the peter evans issues page)
- Correcting the `${​{​ steps.runscript.outputs.DEPLOYMENT_MODE }​}​` (it was coming up as blank)

Nothing seems to work, and all generated the same error:
```
fatal: could not read Username for 'https://github.com': No such device or address
##[error]The process '/usr/bin/git' failed with exit code 128
```

This error is caused here in the peter evans repo:
https://github.com/peter-evans/create-pull-request/blob/v5/src/create-pull-request.ts#L139

```
     - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: "${{ steps.runscript.outputs.DEPLOYMENT_MODE }} AMIs Updated for ${{ inputs.service }} ${{ inputs.version }}"
          branch: chore/release-${{ inputs.service }}-${{ github.run_id }}-${{ github.run_attempt }}
          delete-branch: true
          title: "TEST PR DO NOT MERGE: chore(release): Update ${{ steps.runscript.outputs.DEPLOYMENT_MODE }} AMIs for ${{ inputs.service }} ${{ inputs.version }}"
```
