### ISSUE TITLE
Action does not seem to produce outputs when adding sleep step in between 

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [peter-evans/create-pull-request#2700]
### Subject of the issue

When I invoke the `peter-evans/create-pull-request@v5` and `peter-evans/create-or-update-comment@v3` actions chained:

```yaml
      - name: create the PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          committer: ${{ env.COMMITER }}
          branch: ${{ steps.pr-branch-name.outputs.pr_branch_name }}
          base: 'main'
          title: My Title
          labels: github-actions
          body: PR automatically created

      - name: sleep for 60 seconds
        shell: bash
        run: sleep 60
        
      - name: make a comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create-pr.outputs.pull-request-number }}
          body: "some comment"
          token: ${{ secrets.MY_TOKEN }}
```

The process fails in the `make a comment` step with: 

```
Error: Missing either 'issue-number' or 'comment-id'.
```

If I ditch the `sleep` step, everything works as expected; why is that?

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
