### ISSUE TITLE
Add permissions to example in README

### ISSUE THREAD

**Issue by obecker** [peter-evans/create-pull-request#2729]
I think it makes sense to add `permissions` to the [workflow permissions](https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#workflow-permissions) paragraph and the [reference example](https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#reference-example) in your README, so that users don't have to allow write permissions to all of their workflows.

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

Example:
```
jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

   steps:
      - ...
```
