### ISSUE TITLE
PR Creation does not take place despite the step running with success

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [peter-evans/create-pull-request#2757]
I have the following workflow

```yaml
      - name: checkout the project
        uses: actions/checkout@v4

      - name: create the head branch name
        id: pr-branch-name
        shell: bash
        run: echo "pr_branch_name=_ps_foo/${{ inputs.something }}_$RANDOM" >> $GITHUB_OUTPUT

      - name: touch a file for a non-empty commit to be created
        shell: bash
        run: |
          touch ${{ steps.get-dir-name.outputs.full_lambda_dir_path }}/foo.txt  # this is from an omitted step but works as expected
  
      - name: create the PR
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          committer: ${{ env.COMMITER }}
          commit-message: "My Commit"
          branch: ${{ steps.pr-branch-name.outputs.pr_branch_name }}
          base: 'master'
          title: Generated by GitHub Actions
          labels: ${{ env.PR_LABELS }}
          body: PR automatically created by GitHub Action

      - name: add label to the PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          labels: foobar=zoobar
```

The `create the PR` step does fail (the step is green in the logs).

However I see this in its execution:

```
  HEAD is now at 0f073c0 Some commit (#5409)
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin _ps_foo/test-client_261:refs/remotes/origin/_ps_foo/test-client_261
  fatal: couldn't find remote ref _ps_foo/test-client_261
  Pull request branch '_ps_foo/test-client_261' does not exist yet.
  /usr/bin/git checkout --progress -B _ps_foo/test-client_261 61bd2bae-dfbd-4124-b5bb-e5fcf210bfda --
  Switched to a new branch '_ps_foo/test-client_261'
  /usr/bin/git rev-list --right-only --count master..._ps_foo/test-client_261
  0
  Branch '_ps_foo/test-client_261' is not ahead of base 'master' and will not be created
```
The PR is never created of course.

At the end the overall workflow fails with:

```
HttpError: Empty value for parameter 'issue_number': undefined
```

What am I doing wrong?

Isn't the addition of `foo.txt` enough to progress the `head` branch so that is ahead of `master`?
