### ISSUE TITLE
PR creation failing due to fetch failing

### ISSUE THREAD

**Issue by kierans** [peter-evans/create-pull-request#2764]
### Subject of the issue

My attempt to create a PR is failing with the error message. My use case is when the generated Swagger doc changes for my project, a PR is opened to merge the changes.

```
Create or update the pull request
  Attempting creation of pull request
  Error: fetch failed
```
 
This was working, but has recently stopped. The branch is created and pushed successfully. It’s just the PR step that is failing.

### Steps to reproduce

```yaml
jobs:
  documentation:
    name: Documentation
    runs-on: [self-hosted]
    permissions:
      contents: write
      pull-requests: write
    env:
      swaggerFile: ./swagger.json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install project dependencies
        run: |
          npm ci

      - name: Update Swagger doc
        run: |
          npm run swagger-autogen

      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        if: steps.changes.outputs.changed == 'true'
        with:
          base: main
          commit-message: 'Updated swagger doc'
          branch: docobot/githib_actions/swagger-doc
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          title: 'Update Swagger Doc'
          body: |
            Update Swagger doc due to changes in ${{ github.sha }}
          labels: |
            documentation
```

**Comment by peter-evans** [comment]
Hi @kierans 

I need more information to understand what is happening here.

Things that would help:
- A complete workflow
- A more complete snippet of the logs
- A link to the run (if public)

**Comment by kierans** [comment]
@peter-evans Thanks for looking at this.

This issue is in the context of a corporate project. I’ve updated the description with more info about the workflow job. I’ve uploaded [logs](https://github.com/peter-evans/create-pull-request/files/14303708/git-log.txt) of the run. I’ve had to redact some of the logs, but I think there’s enough there for you to see what’s happening in the run. The GHA run is not public I so can’t give you the link.

**Comment by peter-evans** [comment]
Everything looks fine, so my guess is that this problem is caused by some issue with running on self-hosted. I think if you tried this on hosted (github.com) it would work. That could be a way you can narrow down the problem.

**Comment by kierans** [comment]
This was working with `v5`. Dependabot upgraded the action to `v6`. I’ve reverted back to `v5`

Looking at a [comparison between v5 and v6][1] I’m wondering if the change to the way [git fetch][2] is invoked might be the cause? Maybe it’s a git version issue?

[1]: https://github.com/peter-evans/create-pull-request/compare/v5.0.2...v6.0.0
[2]: https://github.com/peter-evans/create-pull-request/compare/v5.0.2...v6.0.0#diff-b4c14b4e4a159934e752010b5283b97fa6e8f2a123c5ab108065623fe382f084R183

**Comment by peter-evans** [comment]
> This was working with `v5`. Dependabot upgraded the action to `v6`. I’ve reverted back to `v5`

Can you confirm that it works now after reverting back. If that's the case I can try to narrow this down.

> I’m wondering if the change to the way [git fetch](https://github.com/peter-evans/create-pull-request/compare/v5.0.2...v6.0.0#diff-b4c14b4e4a159934e752010b5283b97fa6e8f2a123c5ab108065623fe382f084R183) is invoked might be the cause?

Looking at the log, though, it's already past that point and created the PR branch successfully. The point where it fails is when it's calling the GitHub API to create the PR.

**Comment by peter-evans** [comment]
I think it's this change: https://github.com/peter-evans/create-pull-request/compare/main...infer-urls#diff-149194b9a050dce062d6db2902041d8d9b9c28245428d7435ed58a87fc25b3dc

I added a feature to infer the URLs of repositories so that PRs could be made across different GitHub platforms.

Are you using GHES or GHEC? It looks like the repo has a `https://github.com/$repo` URL, so perhaps not. Can you confirm your situation. The repo is hosted normally on github.com and you are using self-hosted runners?

This is the logic I added, which a suspect may not be working for your use case.
```typescript
    if (githubServerHostname !== 'github.com') {
      options.baseUrl = `https://${githubServerHostname}/api/v3`
    } else {
      options.baseUrl = 'https://api.github.com'
    }
```

**Comment by kierans** [comment]
> > This was working with `v5`. Dependabot upgraded the action to `v6`. I’ve reverted back to `v5`
> 
> Can you confirm that it works now after reverting back. If that's the case I can try to narrow this down.

It is.

**Comment by kierans** [comment]
> Are you using GHES or GHEC? It looks like the repo has a `https://github.com/$repo` URL, so perhaps not. Can you confirm your situation. The repo is hosted normally on github.com and you are using self-hosted runners?

Correct. The repo URL is `https://github.com/$ORG/$REPO`, and the organisation is using self hosted runners.

**Comment by kierans** [comment]
```
> Run echo $GITHUB_API_URL
https://api.github.com/
```

**Comment by peter-evans** [comment]
> ```
> > Run echo $GITHUB_API_URL
> https://api.github.com/
> ```

This is what I would expect, so I don't think the "infer-urls" feature is the problem.

Perhaps this is proxy related. From the log it looks like you are behind a proxy for https requests. Please try setting the proxy explicitly like this:
https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#proxy-support

It's possible that a library I was using has updated and somehow no longer automatically captures your proxy settings.

**Comment by kierans** [comment]
@peter-evans I tried setting the `https_proxy`. Unless I’m doiong something wrong, the proxy isn’t the issue.

```
Run peter-evans/create-pull-request@v6
  with:
    base: main
    ...
 env:
    httpProxy: http://172.17.0.1:3128
    https_proxy: http://172.17.0.1:3128
    
Create or update the pull request
  Attempting creation of pull request
  Error: fetch failed
```

**Comment by peter-evans** [comment]
The workflow you posted starts with `jobs:`. Please can you show me the full workflow. Are you setting any environment variables at the top?

Also, please could you confirm that when you test `v6` there are no other changes to the workflow, you are literally just changing the version of the action.

I'm leaning towards this being a proxy handling connection issue due to some changes to a library I using, but I'll try to figure this out! 😄

**Comment by peter-evans** [comment]
Not sure if this will fix it, but it's worth a shot. Please try this version of the action.

```yml
uses: peter-evans/create-pull-request@bump-proxy-agent
```

**Comment by kierans** [comment]
> The workflow you posted starts with `jobs:`. Please can you show me the full workflow. Are you setting any environment variables at the top?

I am not setting anything extra in the workflow.

```yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  documentation:

...
```

The runner is setting the `$http_proxy` and `$https_proxy` env vars in the shell that the run is being run in.

As you can see from the [logs][1] the action is being run with `https_proxy` and `httpProxy` being set to a value

I’ve added the following step that creates the `httpProxy` var  from the `$https_proxy` shell var to pass to the action ie:

```yaml
 - name: Set up job
    run: |
        echo "httpProxy=${https_proxy}" >> $GITHUB_ENV
```

```yaml
uses: peter-evans/create-pull-request@bump-proxy-agent
...
env:
    https_proxy: ${{ env.httpProxy }}
```

> Also, please could you confirm that when you test `v6` there are no other changes to the workflow, you are literally just changing the version of the action.

That is correct.

> I'm leaning towards this being a proxy handling connection issue due to some changes to a library I'm using, but I'll try to figure this out! 😄

I’ve tried the `bump-proxy-agent` version and still getting “Fetch failed”.

Perhaps it’s worth trying to get more information from the error in the console to continue to aid the debugging efforts.

[1]: https://github.com/peter-evans/create-pull-request/issues/2764#issuecomment-1958735941

**Comment by peter-evans** [comment]
> Perhaps it’s worth trying to get more information from the error in the console to continue to aid the debugging efforts.

Yes I think we need to try and narrow this down and make a minimal example that reproduces the problem. This must a rare edge case, because no other users have reported this (so far). This action is used a lot, so I would expect most issues to effect many users.

I'll have a think about how we can narrow this down.

**Comment by kierans** [comment]
Could it be a trust issue? The proxy will be issuing certs signed by the corporate CA. However, if the proxy/http library you’re using to make the call to create the PR doesn’t trust the proxy, that’s why the fetch could be failing. I’ve had this issue with other tools and have to setup a trust store.

We might want to provide an option in the action to pass a trust store (PEM file) to the relevant lib to test this.

**Comment by peter-evans** [comment]
If it helps to track this down, I'm actually testing proxy support for the action in my test suite here:
https://github.com/peter-evans/create-pull-request-tests/blob/master/.github/workflows/test-command.yml#L1087-L1134

The test uses this image:
https://github.com/peter-evans/forward-proxy

Which is based on:
https://github.com/nadoo/glider

It seems to work fine. I don't really know much about proxies and trust stores so I'm not sure if that could be the issue.

**Comment by SatwaniGovind** [comment]
Hi @peter-evans any update on this?
I started facing this issue when I update to v6.
I was using v5, but as reported in https://github.com/peter-evans/create-pull-request/issues/2790 , the PR creation step was failing.

**Comment by peter-evans** [comment]
Hi @SatwaniGovind 

No, there is no update because I'm unable to reproduce this, and don't have a good idea of what the problem could be.

Perhaps you could help by explaining your use case in detail.
- How are you using the action? (Ideally show workflow / link to runs / logs)
- What runners are you using? (Github hosted, self-hosted, etc)
- Are you using a proxy?
- Any other details that would help us identify this issue

**Comment by SatwaniGovind** [comment]
1. Due to security concerns, I can't share the workflow, but I can share the logs for the failure. They are as follows:
> Create or update the pull request
  Attempting creation of pull request
  Error: fetch failed
2. I am using self-hosted runners for the workflow that this action is a part of.
3. No, the workflow is not using any proxy.

**Comment by raphperrin** [comment]
Am having the same issue with self-hosted runners.
Proxy is set in the runner itself

```
name: create-pr
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  updates:
    timeout-minutes: 10
    runs-on: [selfhosted-runner]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name:
	  run: echo "something" > README.md

    - name: Create PR
      uses: peter-evans/create-pull-request@v6.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore(deps): update readme"
        branch: feat/update-readme
        title: "chore(deps): update readme"
        labels: dependencies
        delete-branch: true
```
