### ISSUE TITLE
Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by stevelacey** [peter-evans/create-pull-request#2790]
### Subject of the issue

I started getting this error on v4, so upgraded to v6, but I'm still seeing it 🤔

```
Create or update the pull request
  Attempting creation of pull request
  A pull request already exists for example:branch
  Fetching existing pull request
  Attempting update of pull request
  Error: Cannot read properties of undefined (reading 'number')
```

Seems to only happen when there's an existing pull request, if I delete the existing one the workflow will succeed.

### Steps to reproduce

Run the workflow with an existing pull request present.

```
    - uses: peter-evans/create-pull-request@v6
      with:
        title: Release ${{ inputs.next_version }}
        body: |
          ## Release [${{ inputs.next_version }}](${{ github.server_url }}/${{ github.repository }}/compare/${{ inputs.previous_version }}...${{ steps.commit.outputs.short }})

          ${{ inputs.notes }}
        author: GitHub <noreply@github.com>
        branch: release
        committer: GitHub <noreply@github.com>
        commit-message: |
          chore(release): ${{ inputs.next_version }}
        delete-branch: true
```

https://github.com/stevelacey/release-builder/blob/v1/pull-request/action.yml#L27C25-L39
