### ISSUE TITLE
Creating PR in another repo 

### ISSUE THREAD

**Issue by alsaganda** [peter-evans/create-pull-request#2808]
### Subject of the issue

I have a workflow that checks out multiple repo, repo1 is where the workflow is running and repo2 where the PR should be created. Issue is that when trying to create the PR, the repo is being set to repo1 when it should be repo2 
```
Determining the base and head repositories
Pull request branch target repository set to `owner/repo1`
```

### Steps to reproduce
```
    steps:
      - name: Checkout Repository (repo1)
        uses: actions/checkout@v4

      - name: Checkout Repository (repo2)
        uses: actions/checkout@v4
        with:
          repository: owner/repo2
          path: repo2
          token: ${{ secrets.GH_TOKEN }}
      
       # Some steps here between for running scripts in repo1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            repo2/scripts/*.txt
          commit-message: "Testing"
          title: "[Automated]'Testing"
          labels: "automated"
          base: main
          branch: "test/testing"
          body: |
            This is an auto-generated PR 
          token: ${{ secrets.GH_TOKEN }}

```

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
