### ISSUE TITLE
Using environment variables in `body-path` file

### ISSUE THREAD

**Issue by pdil** [peter-evans/create-pull-request#2824]
### Subject of the issue

Is it possible to evaluate environment variables in the file passed to the `body-path` parameter?

### Steps to reproduce

In my `body-path` I have a line that includes this:
``` md
`usmap v${{ inputs.version }}` release candidate
```

However, when the pull request is published, the PR body contains the literal text with `${{ ... }}` and not the value of `inputs.version`. Is it possible to replace this text with the value of the variable or do I need to use `body` instead and include all the text directly in the GH Action script (I'd rather not do this if possible)?

* Sample PR with this issue: https://github.com/pdil/usmap/pull/99
* Workflow: https://github.com/pdil/usmap/blob/bugfix/fix-release-workflow/.github/workflows/release.yaml
``` yaml
    - name: Open pull request
      id: open-pr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "[automated] Prepare for ${{ inputs.version }} release"
        branch: release/${{ inputs.version }}
        title: Release version ${{ inputs.version }}
        body-path: .github/workflows/release-pr-body.md
        reviewers: pdil
        assignees: pdil
        labels: release
        delete-branch: true
```
* `body-path` file: https://github.com/pdil/usmap/blob/bugfix/fix-release-workflow/.github/workflows/release-pr-body.md
