### ISSUE TITLE
Force update the branch of existing pull request

### ISSUE THREAD

**Issue by Poornachand200** [peter-evans/create-pull-request#2856]
### Subject of  the issue

Force update the branch of existing pull request

Describe your issue here.

I am trying to create a pull request with a branch already exists. I am expecting the pull request to fail like below

 Attempting creation of pull request
  A pull request already exists for nuuday:ID-3212v4
  Fetching existing pull request
  Attempting update of pull request

But instead it updated the PR loosing all the commits like below

Pull request branch 'ID-3303' already exists as remote branch 'origin/ID-3303'
  /usr/bin/git checkout --progress ID-3303 --
  Switched to a new branch 'ID-3303'
  branch 'ID-3303' set up to track 'origin/ID-3303'.
  /usr/bin/git rev-list --right-only --count main...c3672ee2-2f44-4113-90ce-c61630109611
  1
  /usr/bin/git rev-list --right-only --count main...ID-3303
  6
  /usr/bin/git diff --quiet ID-3303..c3672ee2-2f44-4113-90ce-c61630109611
  Resetting 'ID-3303'
  /usr/bin/git checkout --progress -B ID-3303 c3672ee2-2f44-4113-90ce-c61630109611 --
  Reset branch 'ID-3303'
  Your branch and 'origin/ID-3303' have diverged,
  and have 16 and 6 different commits each, respectively.
    (use "git pull" if you want to integrate the remote branch with yours)
  /usr/bin/git rev-list --right-only --count origin/ID-3303...ID-3303
  16
  Updated branch 'ID-3303'
  /usr/bin/git rev-list --right-only --count main...ID-3303
  1
  /usr/bin/git rev-parse HEAD
  b96e62a33797bf89f05bb991103b55be5a7f9856
  /usr/bin/git branch --delete --force c3672ee2-2f44-4113-90ce-c61630109611
  Deleted branch c3672ee2-2f44-4113-90ce-c61630109611 (was b96e62a3).
  /usr/bin/git checkout --progress main --
  Switched to branch 'main'
  Your branch is up to date with 'origin/main'.

### Steps to reproduce

````
name: "Kickstart the creation of a Dynamic Environment"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      JIRA-ID:
        description: "Jira ticket number, e.g. ID-1234"
        required: true
        default: "ID-1234"
      PR-type:
        type: choice
        description: "choose the PR type from the given options"
        options:
          - fix
          - feat
          - breaking-change
          - build
          - chore
          - ci
          - docs
          - style
          - refactor
          - perf
        required: true
        default: "feat"
      PR-title:
        description: "PR title in the format - e.g: Adding Refresh token to Oauth client"
        required: true

env:
  PING_HELM_CHART_VERSION: 0.9.12

jobs:
  kickstart_dynamic_environment:
    if: inputs.JIRA-ID && inputs.JIRA-ID != '' && contains(inputs.JIRA-ID, 'ID-')
    runs-on: ubuntu-latest
    name: Kick start dynamic environment
    environment: conf-${{ inputs.JIRA-ID }}
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Convert JIRA ticket number to lowercase
        run: |
          head_ref_TEMP="${{ inputs.JIRA-ID }}"
          echo "LOWERCASE_JIRA_ID=${head_ref_TEMP,,}" >>${GITHUB_ENV}

      - name: Create a random tmp file
        run: |
          touch ./.github/tmp/${{ inputs.JIRA-ID}}.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPOSITORY_ROBOT_PAT }}
          branch: ${{ inputs.JIRA-ID }}
          commit-message: "Kickstart the creation of a Dynamic Environment"
          title: "${{ inputs.PR-type }}(${{inputs.JIRA-ID}}): ${{ inputs.PR-title }}"
          assignees: ${{ github.actor }}
          draft: true
          body: |
            Jira ticket: ${{ env.LOWERCASE_JIRA_ID }}

            The dynamic environment will be available at the following addresses when it's ready:
            - https://${{ env.LOWERCASE_JIRA_ID }}-federate.dev.ciam.non-prod.managed-eks.aws.nuuday.nu
            - https://${{ env.LOWERCASE_JIRA_ID }}-federate-engine.dev.ciam.non-prod.managed-eks.aws.nuuday.nu
            - https://${{ env.LOWERCASE_JIRA_ID }}-directory.dev.ciam.non-prod.managed-eks.aws.nuuday.nu
````
If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.
