### ISSUE TITLE
Error creating new PR 

### ISSUE THREAD

**Issue by erick-fms** [peter-evans/create-pull-request#2863]
### Workflow using create-pull-request@v6 fails

Recently the `create-pull-request` action has been failing in this step:

```
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  staging
  Working base is branch 'staging'
  /usr/bin/git remote prune origin
  fatal: could not read Username for 'https://github.com/': No such device or address
  Error: The process '/usr/bin/git' failed with exit code 128
```

This works fine for more than a year.

### Our workflow file is pretty simple:

```
name: Create PR Automatic to Staging
on:
  push:
    branches:
      - develop
      
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches develop to staging
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - name: Reset staging branch
        run: |
          git fetch origin develop:develop --update-head-ok
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feature/dev-to-stg
          title: Sync Develop to Staging
          body: |
             - Automatic PR from Develop to Staging
             - By: DBRE Team
          labels: |
            Env: Staging
            From: Auto PR
          token: <token>
          delete-branch: true
``` 

Any suggestions why this is happening?
