### ISSUE TITLE
Error: Input 'token' not supplied. Unable to continue.

### ISSUE THREAD

**Issue by AmazingAng** [peter-evans/create-pull-request#2930]
### Error: Input 'token' not supplied. Unable to continue.

I provided the token but still got `Error: Input 'token' not supplied. Unable to continue.`.

I use the following code in my yaml file:
```
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GH_TOKEN }}  
        commit-message: Update tutorials
        title: "Update Tutorials"
        body: "This is an automated PR to update tutorials"
        branch: "update-tutorials-${{ github.run_id }}"
        base: "main"
        labels: "automated pr"
```

https://github.com/WTFAcademy/frontend/actions/runs/9283297372/job/25543215968#step:4:15
