### ISSUE TITLE
Merge conflict error for different files with different names

### ISSUE THREAD

**Issue by Poornachand200** [peter-evans/create-pull-request#2958]
### Merge conflict error for different files with different content in it

Describe your issue here.

I am creating a pull request from a branch called test2 to main. It throws a conflict error for a jar file though they are two different files with different name. Attached the log and steps to reproduce.

https://github.com/nuuday/ciam-server-profiles/actions/runs/9300256169/job/25595880088

### Steps to reproduce

[logs_24340228060 (2).zip](https://github.com/user-attachments/files/15585643/logs_24340228060.2.zip)

CONFLICT (rename/rename): Rename "nuuday-ciam/production/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.8.jar"->"nuuday-ciam/test/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.12.jar" in branch "HEAD" rename "nuuday-ciam/production/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.8.jar"->"nuuday-ciam/production/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.13.jar" in "31cb87be (chore(release): promoting pingfederate from test to production)"
  Auto-merging nuuday-ciam/test/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.12.jar and nuuday-ciam/production/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.13.jar, both renamed from nuuday-ciam/production/pingfederate/instance/server/default/deploy/ciam-extensions-0.1.8.jar

```
name: "Start Promotion Staging->Production"

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_call: 
    inputs:
      product:
        description: 'ping product to promote'
        required: true
        type: string
      branch:
        description: 'branch to deploy'
        required: true
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest
    name: Promoting from test to production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Copy PingDirectory
        if: inputs.product == 'pingdirectory'
        run: |
          rm -rf ./nuuday-ciam/production/pingdirectory
          cp -r nuuday-ciam/test/pingdirectory/ nuuday-ciam/production/pingdirectory
          find ./nuuday-ciam/production/pingdirectory/ -name '*_test.*' -type f -delete

      - name: Copy PingFederate
        if: inputs.product == 'pingfederate'
        run: |
          npm install --dev --prefix .build
          rm -rf nuuday-ciam/production/pingfederate
          cp -r nuuday-ciam/test/pingfederate nuuday-ciam/production/pingfederate
          find ./nuuday-ciam/production/pingfederate/ -name '*.css.map*' -type f -delete
          npm run config:production --prefix .build

      - name: Git status
        run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPOSITORY_ROBOT_PAT }}
          branch: "release/${{inputs.product}}-test-to-production"
          commit-message: "chore(release): promoting ${{inputs.product}} from test to production"
          title: "chore(release): promoting ${{inputs.product}} from test to production"
          assignees: ${{ github.actor }}
          base: main
          labels: "automated promotion"
          branch-suffix: short-commit-hash
          body: |
            THIS IS AN AUTOMATED PROMOTION FROM THE TEST ENVIRONMENT TO PRODUCTION ENVIRONMENT.

            PLEASE REVIEW THE FILE CHANGES IN THIS PR AND MERGE IT WHEN YOU ARE READY.

            WHEN THIS PR IS MERGED, THE CHANGES WILL BE AUTOMATICALLY DEPLOYED TO PRODUCTION.

```
