### ISSUE TITLE
Can't figure out how to include commits made during workflow

### ISSUE THREAD

**Issue by pbrisbin** [peter-evans/create-pull-request#3017]
### Subject of the issue

In the README, it's stated that the action should include:

> commits made during the workflow that have not been pushed

But I can't seem to make that happen.

### Steps to reproduce

```yaml
name: X

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Hi" > foo.txt
          git add foo.txt
          git commit -m "Add foo.txt"
        env:
          GIT_AUTHOR_EMAIL: commits@restyled.io
          GIT_AUTHOR_NAME: Restyled.io
          GIT_COMMITTER_EMAIL: commits@restyled.io
          GIT_COMMITTER_NAME: Restyled.io

      - uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ github.event.pull_request.head.ref }}
```

I expect a PR to be opened against this PR's branch with my `foo.txt` commit present. However, [it just says](https://github.com/restyled-io/restyler/actions/runs/9945791920/job/27474868612):

```
  /usr/bin/git rev-list --right-only --count pb/action...create-pull-request/patch
  0
  Branch 'create-pull-request/patch' is not ahead of base 'pb/action' and will not be created
```

Am I missing something obvious here?

**Comment by peter-evans** [comment]
Hi @pbrisbin 

The problem is that `pull_request` events checkout a merge commit of the PR branch merged into the target. That leaves the local git state in "detached head" mode. As mentioned [here](https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#create-your-own-commits), creating your own commits cannot work when checked out on a commit.

To fix this I think you can explicitly checkout the PR branch, not the merge commit.

```yml
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
```
