### ISSUE TITLE
When the workflow is triggered with `base` and `branch`, the PR is not created

### ISSUE THREAD

**Issue by diegocam** [peter-evans/create-pull-request#3056]
### Subject of the issue

I have this workflow that, ideally, when triggered would create a PR that merges code from `develop` to `master`. However, that PR is not created, throwing the errors:

workflow file `test_create_pr.yml`
```yml
name: Test Create PR

on:
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request to Master
        uses: peter-evans/create-pull-request@v6
        env:
          commit-message: Update master from develop
          title: Update master from develop
          branch: develop
          base: master
```

Errors:
```
2s
Run peter-evans/create-pull-request@v6
Prepare git configuration
Determining the base and head repositories
Pull request branch target repository set to americandiscount/orig-adc
Configuring credential for HTTPS authentication
Checking the base repository state
Pull request branch to create or update set to 'create-pull-request/patch'
Configuring the committer and author
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  develop
  Working base is branch 'develop'
  /usr/bin/git checkout --progress -B 2ccf44a3-5242-4978-8[1](https://github.com/americandiscount/orig-adc/actions/runs/10105309497/job/27945582101#step:3:1)d4-7d0e235705b2 HEAD --
  Switched to a new branch '2ccf44a3-5242-4978-81d4-7d0e235705b2'
  /usr/bin/git status --porcelain -unormal --
  /usr/bin/git diff --quiet --
  /usr/bin/git diff --quiet --staged --
  /usr/bin/git stash push --include-untracked
  No local changes to save
  Resetting working base branch 'develop'
  /usr/bin/git checkout --progress develop --
  Switched to branch 'develop'
  Your branch is up to date with 'origin/develop'.
  /usr/bin/git reset --hard origin/develop
  HEAD is now at 1ef9ded87 Adjust github action step
  /usr/bin/git rev-list --right-only --count develop...2ccf44a3-5242-4978-81d4-7d0e235705b2
  0
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force --depth=10 origin create-pull-request/patch:refs/remotes/origin/create-pull-request/patch
  fatal: couldn't find remote ref create-pull-request/patch
  Pull request branch 'create-pull-request/patch' does not exist yet.
  /usr/bin/git checkout --progress -B create-pull-request/patch 2ccf44a3-5242-4978-81d4-7d0e235705b2 --
  Switched to a new branch 'create-pull-request/patch'
  /usr/bin/git rev-list --right-only --count develop...create-pull-request/patch
  0
  Branch 'create-pull-request/patch' is not ahead of base 'develop' and will not be created
  /usr/bin/git rev-parse HEAD
  1ef9ded87f2d3ccb0de8ad54e8c256b0[31](https://github.com/americandiscount/orig-adc/actions/runs/10105309497/job/27945582101#step:3:34)c93287
  /usr/bin/git branch --delete --force 2ccf44a3-5242-4978-81d4-7d0e2[35](https://github.com/americandiscount/orig-adc/actions/runs/10105309497/job/27945582101#step:3:39)705b2
  Deleted branch 2ccf44a3-5242-4978-81d4-7d0e235705b2 (was 1ef9ded87).
  /usr/bin/git checkout --progress develop --
  Switched to branch 'develop'
  Your branch is up to date with 'origin/develop'.
```

### Steps to reproduce

1. Make sure the branch `develop` is ahead of `master`
2. Create the workflow `test_create_pr.yml` (as posted above)
3. Via the Github `Actions` tab, find the workflow "Test Create PR" and click it
4. Manually trigger it by selecting "Run Workflow" and selecting the `develop` branch
5. Watch the logs for the errors.
