### ISSUE TITLE
Autosync PR out of date

### ISSUE THREAD

**Issue by paymog** [peter-evans/create-pull-request#3124]
### Subject of the issue

I'm following the pattern for the auto-sync PR to keep my `prod` branch up to date with my `dev` branch. I just merged one of these PRs. then I pushed another commit to dev, the new PR was created, but I see that it's out of date

<img width="980" alt="image" src="https://github.com/user-attachments/assets/cba4d1a8-76b3-4f91-9788-fd5cd2a07320">

Here's my workflow

```
name: Auto PR from dev to prod

on:
  push:
    branches:
      - dev

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: prod
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: prod-promotion
          delete-branch: true
          title: "Auto PR: Merge changes from dev to prod"
          body: "This pull request has been automatically created to merge changes from the dev branch into the prod branch."
```
