### ISSUE TITLE
Not opening PR's

### ISSUE THREAD

**Issue by fefranco97** [peter-evans/create-pull-request#3132]
### Subject of the issue

I already made all the configurations, and tried alot others configurations, but none of it open a PR 
I'm trying to always keep my branch develop sync with branchs that start with feature
My workflow setting are correct

My acction dont give any error, just don't open a new PR

This is my code:
` 
name: '1 - [Feat] Build & Test'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  OpenPullRequest:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Debugging Information
        run: |
          echo "Current Branch:"
          git branch
          echo "Git Status:"
          git status
          echo "Latest Commit:"
          git log -1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          signoff: false
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          title: 'Feature: Atualizações para a branch develop'
          body: |
            Esta PR inclui as seguintes atualizações:
            - Descrição do que foi alterado
            - Referências a problemas ou tickets
          labels: 'Automatic-PR, Feature'
          draft: false
          branch: feature-to-develop
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
`

Someone can help me to understand what is going on here?

**Comment by Davidaprilio** [comment]
Have you been able to create an Open PR?
same problem here

**Comment by fefranco97** [comment]
> Have you been able to create an Open PR? same problem here

@Davidaprilio Hello !

Yes, it was missconfiguration, you need to reset the current branch instead of the base branch here how i did:


``` 
OpenPullRequest:
    runs-on: ubuntu-latest
    needs: [Linting, Testing]

    steps:
      - name: Get Current Branch
        uses: actions/checkout@v4

      - name: Set Branch Name  // Create a variable to save current branch, cause my trigger branch is feature/**
        run: echo "branch-name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV  

      - name: Checkout Repository  // Checkout to develop ( Base branch that need to be syncronized )
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Reset feature branch  // This is what solve the problem, instead of reseting the base branch (Dev) you need to reset tha target branch feature/something
        run: |
          git fetch origin ${{ env.branch-name }}:${{ env.branch-name }}
          git reset --hard ${{ env.branch-name }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          signoff: false
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          title: 'Feature: Atualizações para develop'
          body: |
            Your PR body
          labels: 'automatic-PR, feature'
          draft: false
          branch: feature-to-develop // Temporary branch
          delete-branch: true
```
