### ISSUE TITLE
Attempting creation of pull request   Error: Not Found

### ISSUE THREAD

**Issue by timteka** [peter-evans/create-pull-request#3235]
### Subject of the issue
Can't create PR with unclear error
```
Attempting creation of pull request
Error: Not Found
```
Describe your issue here.
After successful creation of branch your action is not able to create PR. Maybe smth wrong with multiple checkouts?
Running this action in ParentRepo
### Steps to reproduce
```
on:
  push:
    branches:
      - master
permissions: write-all
jobs:
  PR-Actions:
    runs-on: self-hosted
    
    steps:
...
- uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.myorg }}
          path: parent-repo

      - uses: actions/checkout@v4
        with:
          repository: MyOrg/ChildRepo
          ref: master
          ssh-key: ${{ secrets.myorg }}
          path: child-repo
...
here numerous CRUD stuff with files from ChildRepo
...
- name: Create Pull Request
        env:
          BRANCH: ${{ steps.newbranch.outputs.BRANCH }}
          COMMITTER: ${{ steps.initiator.outputs.COMMITTER }}
          COMMITMSG: ${{ steps.initiator.outputs.COMMITMSG }}
        uses: peter-evans/create-pull-request@v6
        with:
          author: OurCorp <16988934324553+corp-ltd@users.noreply.github.com>
          branch: ${{ env.BRANCH }}
          title: "Automatic updates to ${{ env.BRANCH }}"
          body: "This is an auto-generated PR. Initiated by  ${{ env.COMMITTER }}. \n ${{ env.COMMITMSG }}"
          commit-message: "${{ env.COMMITMSG }}"
          path: child-repo
```

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @timteka 

Are you trying to create a pull request in the parent-repo with updates you've fetched from the child-repo? Or is it the other way round?

**Comment by timteka** [comment]
The actions is triggered by push into parent. In parent I need to get some info and afterwards everything else is gonna take place in child repo. The Action creates new branch successfully in child repo, but fails on PR (though I've set already sec permissions: the machine user is a Maintainer in child repo)

**Comment by peter-evans** [comment]
> the machine user is a Maintainer in child repo

Are you referring to the machine user that owns the SSH keys?

The action can only use SSH auth for the git operations. For creating the pull request the action needs a `token`. Because you've not specified a token the action will use the default `GITHUB_TOKEN` in the repository where the workflow is running. In your case the workflow is running in the parent repo, so the token is scoped to the parent. If you want to allow the action to create a pull request in the child then you need to use a PAT created on the machine user, and pass that as the `token` input.

**Comment by peter-evans** [comment]
Also the docs [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-using-ssh-deploy-keys), where it says:

> Note that you cannot use deploy keys alone to [create a pull request in a remote repository](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository) because then using a PAT would become a requirement. This method only makes sense if creating a pull request in the repository where the workflow is running.

**Comment by timteka** [comment]
I've added the
```
- name: Create Pull Request
        env:
          BRANCH: ${{ steps.newbranch.outputs.BRANCH }}
          COMMITTER: ${{ steps.initiator.outputs.COMMITTER }}
          COMMITMSG: ${{ steps.initiator.outputs.COMMITMSG }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.myOrg }}
          author: OurCorp <16988934324553+corp-ltd@users.noreply.github.com>
          branch: ${{ env.BRANCH }}
          title: "Automatic updates to ${{ env.BRANCH }}"
          body: "This is an auto-generated PR. Initiated by  ${{ env.COMMITTER }}. \n ${{ env.COMMITMSG }}"
          commit-message: "${{ env.COMMITMSG }}"
          path: child-repo
```
Another error:
```
Attempting creation of pull request
  Error: Headers.append: "token ***" is an invalid header value.
```
