### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by wiiznokes** [peter-evans/create-pull-request#3236]
Maybe the doc should include all the necessary setup to run this action against our own repo.
You will need this:

```
permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
