### ISSUE TITLE
It is not possible to create two continuous pull requests

### ISSUE THREAD

**Issue by devjorgecastro** [peter-evans/create-pull-request#3237]
### Subject of the issue

I want to create two Pull Requests to generate a Release: The first one points to develop and the second one points to master. When I only create one pull request it works fine but when I try to create the second one it is not created.

I leave here an example of how I am trying to do it:

### Steps to reproduce

```yaml

jobs:

  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release branch
        run: git checkout -b release/1.1.0

      - name: Configure git
        run: |
          git config user.name 'Release Bot'
          git config user.email 'actions-user@users.noreply.github.com'

      - name: Create a test file
        run: |
          echo "1.1.0" > test_file.txt

      - name: Push new release branch
        run: git push origin release/1.1.0

      - name: Create Pull Request for develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add test file for release version 1.1.0"
          base: develop
          branch: release/1.1.0
          title: 'Release 1.1.0'
          body: |
            Custom message
          author: 'Release Bot <actions-user@users.noreply.github.com>'
          labels: release


      - name: Create Pull Request for master
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add test file for release version 1.1.0"
          base: master
          branch: release/1.1.0
          title: 'Release 1.1.0'
          body: |
            Custom message
          author: 'Release Bot <actions-user@users.noreply.github.com>'
          labels: release

```
Has anyone had the same problem? How could I solve it?
