### ISSUE TITLE
Cannot create a Pull Request when it flags conflicts

### ISSUE THREAD

**Issue by devjorgecastro** [peter-evans/create-pull-request#3241]
### Subject of the issue

I am trying to create a pull request but when marking conflicts it is not created. Is there a way to escape this validation and the PR is created with the conflicts so they can be resolved manually?

### Steps to reproduce

```
jobs:

  create-release-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [develop, master]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add changes
        run: |
          sed -i 's/^versionName=.*/versionName=${{ inputs.version-name }}/' version.properties
          echo "2.0.10" > test_file.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add test file for release version ${{ inputs.version-name }}"
          base: ${{ matrix.branch }}
          branch: release/${{ inputs.version-name }}
          title: 'Release ${{ inputs.version-name }}'
          body: |
            Custom message
          author: 'Release Bot <actions-user@users.noreply.github.com>'
          labels: release
```

Result
<img width="852" alt="image" src="https://github.com/user-attachments/assets/9f96fc25-ed45-4089-b1e3-56f8a661118e">
