### ISSUE TITLE
[Feature Request]: Allow commit author to be optional

### ISSUE THREAD

**Issue by thislooksfun** [peter-evans/create-pull-request#3317]
### Subject of the issue

This is an awesome action, but I have one small gripe with it: I don't want to set an author on the commits, just a committer. Currently the only way I can see to do that is to set the author to be the same as the committer, but since the default committer is the GitHub actions bot, that is a bit messy. It would be awesome if there was a way to disable setting a commit author when using this action.

### Steps to reproduce

N/A

**Comment by peter-evans** [comment]
Hi @thislooksfun 

As far as I know, it's technically not possible for a commit to have no author. Perhaps you are referring to how GitHub shows some commits as just having a committer if the author and committer are the same. That's just a UI feature to not show redundant information, but actually the commit does have an author.

As you suggested, you can make GitHub show just a committer for the commits by setting the author to the actions bot:
```yml
      - uses: peter-evans/create-pull-request@v7
        with:
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
```

I don't like adding inputs to the action unless they are strictly necessary. Sorry this a "bit messy," but this is the solution. 😄
