### ISSUE TITLE
exception when using path

### ISSUE THREAD

**Issue by kwavnet** [peter-evans/create-pull-request#3497]
With the following settings

```
Run peter-evans/create-pull-request@v7.0.5
  with:
    token: ***
    commit-message: data.json: update
  
    committer: Report Bot <noreply@github.com>
    author: Report Bot <report-bot@users.noreply.github.com>
    path: data.json
    branch: update/data
    base: master
    delete-branch: true
    title: data.json: update
    body: Update the data.json file.
    labels: automerge
  
    draft: false
    signoff: false
    sign-commits: false
    maintainer-can-modify: true
  env:
    SSH_AUTH_SOCK: /tmp/ssh-XXXXXXgzrLGR/agent.1535
    SSH_AGENT_PID: 1536
    pythonLocation: /opt/hostedtoolcache/Python/3.10.15/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib
```

on a `ubuntu-latest` 

I get
```
Prepare git configuration
  /usr/bin/git config --global --name-only --get-regexp safe.directory /home/runner/work/my-repo/my-repo/data.json
  node:internal/child_process:421
      throw new ErrnoException(err, 'spawn');
            ^
  
  Error: spawn ENOTDIR
      at ChildProcess.spawn (node:internal/child_process:421:11)
      at Object.spawn (node:child_process:761:9)
      at ToolRunner.<anonymous> (/home/runner/work/_actions/peter-evans/create-pull-request/v7.0.5/dist/index.js:3970:34)
      at Generator.next (<anonymous>)
      at fulfilled (/home/runner/work/_actions/peter-evans/create-pull-request/v7.0.5/dist/index.js:3581:58) {
    errno: -20,
    code: 'ENOTDIR',
    syscall: 'spawn'
  }
  
  Node.js v20.13.1
```

When I use `add-path` instead of `path` it just works.
I don't understand the internals, but it looks a bit like this here https://github.com/nodejs/node/issues/52667#issuecomment-2267085555
