### ISSUE TITLE
Add new input to show created PR link on action run page

### ISSUE THREAD

**Issue by ybiquitous** [peter-evans/create-pull-request#3624]
Hello. I'm sorry if this feature request was already duplicated. Please feel free to reject it then.

In this issue, I want to suggest a new input to show a created PR in a [`notice` message](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-notice-message) on an action run page like this:

<img width="628" alt="Image" src="https://github.com/user-attachments/assets/9dbf6119-503a-4db4-bb56-103b03c2fef3" />

This feature should be disabled by default, but when users want, it might be helpful because they could easily find a created or updated PR on action log pages.

Since we don't have this feature for now, we must write more workflow code to achieve the same thing. However, if the feature were added, we could just enable the input. For example:

Before:

```yaml
- name: Create pull request
  id: cpr
  uses: peter-evans/create-pull-request@v7

- name: Show pull request
  if: ${{ steps.cpr.outputs.pull-request-url && steps.cpr.outputs.pull-request-operation != 'none' }}
  env:
    PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
    PR_OPERATION: ${{ steps.cpr.outputs.pull-request-operation }}
  run: |
    echo "::notice::${PR_URL} was ${PR_OPERATION}."
```

After:

```yaml
- name: Create pull request
  uses: peter-evans/create-pull-request@v7
  with:
    message-on-success: true
```

I don't find any downsides now, but please let me know if any. Or close my suggestion if you have any justification.
Thank you for taking the time to read this.
