### ISSUE TITLE
Feature: Support Git Trailers in commit message

### ISSUE THREAD

**Issue by briceburg** [peter-evans/create-pull-request#3741]
My immediate use-case is to add a [trailer](https://alchemists.io/articles/git_trailers) to the commit message to disable commits made by this action from triggering downstream workflows. GitHub natively supports this via trailers (my preference) or blocks in the commit message per https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs

It's not immediately clear if trailers are supported out-of-box. The `commit-message` input doesn't appear to accept a multiline value at first glance, and I'm uncertain if the git implementation does not automatically remove consecutive newlines from commit messages?

Perhaps adding a `trailers` input of newline separated trailers would be helpful? e.g. something like

```yaml
name: Create Pull Request
uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
with:
  commit-message: "GitOps: Update Components"
  branch: "gitops/update-components" 
  trailers: |
    skip-checks:true
  ...
```

**Comment by peter-evans** [comment]
Hi @briceburg 

The `commit-message` input can be multiline, so you can just do this:

```yml
          commit-message: |
            GitOps: Update Components

            skip-checks: true
```

The git trailers functionality just aids adding/parsing key/value pairs from commit messages, but it's not really necessary to use it. Just adding directly to the commit message like this has exactly the same effect.
