### ISSUE TITLE
uncommitted change

### ISSUE THREAD

**Issue by xenoterracide** [peter-evans/create-pull-request#3796]
having trouble describing what's going on here because I'm not certain. It might be gradle's fault, that really really wouldn't surprise me if somehow gradle was still running some part of an update in the background. On the other hand this has been failing for days, and other steps are run between the last gradle run. It's also weird that the exact same build workflow, and makefile have succeeded in other repos.

I'm going to do some further investigation, but if you see anything.

```
Working base is branch 'main'
  /usr/bin/git checkout --progress -B e582b8a9-2180-418c-8a0c-5cdf94b8ed2a HEAD --
  Switched to a new branch 'e582b8a9-2180-418c-8a0c-5cdf94b8ed2a'
  M	buildSrc/buildscript-gradle.lockfile
  M	buildSrc/gradle.lockfile
  M	gradle/wrapper/gradle-wrapper.jar
  M	gradle/wrapper/gradle-wrapper.properties
  M	gradlew
  M	gradlew.bat
  M	module/checkstyle/gradle.lockfile
  M	module/coverage/gradle.lockfile
  M	module/publish/gradle.lockfile
  M	module/spotbugs/gradle.lockfile
  /usr/bin/git status --porcelain -unormal --
   M buildSrc/buildscript-gradle.lockfile
   M buildSrc/gradle.lockfile
   M gradle/wrapper/gradle-wrapper.jar
   M gradle/wrapper/gradle-wrapper.properties
   M gradlew
   M gradlew.bat
   M module/checkstyle/gradle.lockfile
   M module/coverage/gradle.lockfile
   M module/publish/gradle.lockfile
   M module/spotbugs/gradle.lockfile
  Uncommitted changes found. Adding a commit.
  /usr/bin/git add -A
  /usr/bin/git -c author.name=xenoterracide -c author.email=5517+xenoterracide@users.noreply.github.com -c committer.name=github-actions[bot] -c committer.email=41898282+github-actions[bot]@users.noreply.github.com commit -m [create-pull-request] automated change
  [e582b8a9-2180-418c-8a0c-5cdf94b8ed2a 423e65b] [create-pull-request] automated change
   Author: xenoterracide <5517+xenoterracide@users.noreply.github.com>
   10 files changed, 197 insertions(+), 204 deletions(-)
  /usr/bin/git stash push --include-untracked
  No local changes to save
  Resetting working base branch 'main'
  /usr/bin/git checkout --progress main --
  Switched to branch 'main'
  Your branch is up to date with 'origin/main'.
  /usr/bin/git reset --hard origin/main
  HEAD is now at 4d[57](https://github.com/xenoterracide/gradle-convention/actions/runs/13712969981/job/38352820445#step:11:63)bdd chore(deps): update npm (#117)
  /usr/bin/git rev-list --right-only --count main...e[58](https://github.com/xenoterracide/gradle-convention/actions/runs/13712969981/job/38352820445#step:11:64)2b8a9-2180-418c-8a0c-5cdf94b8ed2a
  1
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force --depth=11 origin deps/update-java:refs/remotes/origin/deps/update-java
  fatal: couldn't find remote ref deps/update-java
  Pull request branch 'deps/update-java' does not exist yet.
  /usr/bin/git checkout --progress -B deps/update-java e582b8a9-2180-418c-8a0c-5cdf94b8ed2a --
  error: Your local changes to the following files would be overwritten by checkout:
  	gradlew.bat
  Please commit your changes or stash them before you switch branches.
  Aborting
  Error: The process '/usr/bin/git' failed with exit code 1
```

```yaml
# SPDX-FileCopyrightText: Copyright © 2024 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: update-java
on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - ci/auto-update-java
      - ci/auto-update

jobs:
  update-java:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
    env:
      ORG_GRADLE_PROJECT_ghUsername: ${{ secrets.GITHUB_ACTOR }}
      ORG_GRADLE_PROJECT_ghPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch}}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - run: gradle wrapper --write-locks
      - run: make ci-update-java
      - run: |
          echo "stdout<<EOF" >> $GITHUB_OUTPUT
          git status --porcelain=1 | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        name: git status
        id: git_status
      - uses: actions/setup-python@v5
        if: ${{ contains(steps.git_status.outputs.stdout, 'gradle/wrapper/') }}
      - run: pip install -r requirements.txt
        if: ${{ contains(steps.git_status.outputs.stdout, 'gradle/wrapper/') }}
      - run: |
          reuse annotate --license 'Apache-2.0' --copyright 'Gradle, Inc' \
            --copyright-prefix spdx-string-symbol --merge-copyrights --force-dot-license gradle/wrapper/gradle-wrapper.jar
          reuse annotate --license 'CC0-1.0' --copyright 'Caleb Cushing' \
            --copyright-prefix spdx-string-symbol --merge-copyrights --force-dot-license gradle/wrapper/gradle-wrapper.properties
        name: reuse
        if: ${{ contains(steps.git_status.outputs.stdout, 'gradle-wrapper.jar') }}
      - uses: peter-evans/create-pull-request@v7
        id: create_pr
        with:
          title: "chore(deps): java"
          branch: deps/update-java
          token: ${{ secrets.GH_MERGE_PAT }}
      - run: gh pr merge --auto --squash ${{ steps.create_pr.outputs.pull-request-number }}
        if: ${{ steps.create_pr.outputs.pull-request-number != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_MERGE_PAT }}
```

https://github.com/xenoterracide/gradle-convention/actions/runs/13712969981/job/38352820445
