### ISSUE TITLE
PR doesn't get created

### ISSUE THREAD

**Issue by devranaydinoglu** [peter-evans/create-pull-request#3910]
The following workflow is supposed to create a PR, bringing the changes from `test-integration` to `test-release`, and gets run when changes get pushed to the `test-integration` branch. All the steps pass, but it doesn't seem to create a PR as it's not visible in the repo's Pull Requests tab. However, the changes from `test-integration` do get pushed to `test-release`. Any idea why it's not creating a PR?

When I change the `branch` input to a non-existing branch, it doesn't do anything at all.

"Create and approve pull requests" has been enabled under Settings -> Actions.

```yaml
permissions:
  contents: write
  pull-requests: write

jobs:
  delivery-gen:
    name: Generate delivery file
    uses: ./.github/workflows/delivery-gen.yaml
    secrets: inherit

  create-pr:
    name: Create pull request
    runs-on: k8s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          branch: "test-release"
          base: "test-integration"
```
