### ISSUE TITLE
The pull request is not being created

### ISSUE THREAD

**Issue by zhtmr** [peter-evans/create-pull-request#3912]
![Image](https://github.com/user-attachments/assets/41d74e87-3377-4762-8132-f8100040ee56)

```yml
name: Auto PR and Merge

on:
  push:
    branches:
      - 'sw**'
      - 'cm**'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: 'main'
          branch: ${{ github.ref_name }}
          title: "[auto] ${{github.event.head_commit.message}}"
          body: |
            - 자동 PR: ${{ github.ref_name }} → main
            - 커밋 메시지: ${{ github.event.head_commit.message }}
          labels: auto-merge
          assignees: ${{ github.actor }}
          reviewers: ${{ vars.REVIEWERS }}
          draft: false

      - name: Enable Auto Merge
#        if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
```

I followed the instructions above, but no PR is created automatically. When I try to create one manually, it shows no changes, just like in the screenshot.
