### ISSUE TITLE
The `base` parameter is ignored

### ISSUE THREAD

**Issue by rochdev** [peter-evans/create-pull-request#3929]
I am using this configuration (with variables expanded to their real values for that run):

```yml
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          base: v5.x
          body-path: /home/runner/work/_temp/release_notes/v5.48.2.md
          branch: v5.48.2-proposal
          draft: true
          sign-commits: true
          title: v5.48.2 proposal
          token: REDACTED
```

When I run the action from the `v5.48.2-proposal` branch, that branch is used regardless of `base`:

```
  Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  v5.48.2-proposal
  Working base is branch 'v5.48.2-proposal'
  /usr/bin/git remote prune origin
```

This results in an error later on:

```
  Resetting working base branch 'v5.48.2-proposal'
  /usr/bin/git checkout --progress v5.48.2-proposal --
  Switched to branch 'v5.48.2-proposal'
  /usr/bin/git reset --hard origin/v5.48.2-proposal
  fatal: ambiguous argument 'origin/v5.48.2-proposal': unknown revision or path not in the working tree.
```

If I switch to the base branch before running the action using `git checkout v5.x` then it works properly:

```
  Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  v5.x
  Working base is branch 'v5.x'
  /usr/bin/git remote prune origin
```

With the corresponding success later on:

```
  Resetting working base branch 'v5.x'
  /usr/bin/git checkout --progress v5.x --
  Switched to branch 'v5.x'
  Your branch is up to date with 'origin/v5.x'.
  /usr/bin/git reset --hard origin/v5.x
```

While I can switch to the base branch before running the action as a workaround, I would expect the `base` parameter to be used regardless of the active branch when the action is run.

Full output for the error: https://github.com/DataDog/dd-trace-js/actions/runs/14520131690/job/40738810547
