### ISSUE TITLE
PR not created because the action resets source to target

### ISSUE THREAD

**Issue by bluesmoon** [peter-evans/create-pull-request#3937]
My workflow is as follows.
* Some external task pushes to a branch called insights-update
* gh action should then create a PR to merge the insights-update branch into main. The action should not make any changes to the branches.

My yaml is at the bottom of the issue.

The PR is never created because the action seems to think that there are no changes between the two branches. Looking at the log, I think the problem is when `branch` is reset to be identical to `base` (step 12 below). What should I do?
  
1. At the start HEAD is at insights-update:
```
  /usr/bin/git symbolic-ref HEAD --short
  insights-update
  Working base is branch 'insights-update'
```

2. Create a new working branch at HEAD (insights-update)
```
  /usr/bin/git checkout --progress -B 93bc15a6-9be3-4044-a821-f9f561196d6c HEAD --
  Switched to a new branch '93bc15a6-9be3-4044-a821-f9f561196d6c'
  /usr/bin/git status --porcelain -unormal --
  /usr/bin/git diff --quiet --
  /usr/bin/git diff --quiet --staged --
  /usr/bin/git stash push --include-untracked
  No local changes to save
```

3. Switch back to insights-update
```
  Resetting working base branch 'insights-update'
  /usr/bin/git checkout --progress insights-update --
  Switched to branch 'insights-update'
  Your branch is up to date with 'origin/insights-update'.
  /usr/bin/git reset --hard origin/insights-update
  HEAD is now at 0185aa9 foo
```

4. Fetch main
```
  Rebasing commits made to branch 'insights-update' on to base branch 'main'
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force --depth=1 origin main:main
```

5. Switches HEAD to main:
```
  /usr/bin/git checkout --progress main --
  Switched to branch 'main'
```

6. Check commits from insights-update to working branch. No difference since working branch is identical to insights-update at this point
```
  /usr/bin/git rev-list --reverse insights-update..93bc15a6-9be3-4044-a821-f9f561196d6c .
```

7. Now reset working branch to HEAD, which is main
```
  /usr/bin/git checkout --progress -B 93bc15a6-9be3-4044-a821-f9f561196d6c HEAD --
  Switched to and reset branch '93bc15a6-9be3-4044-a821-f9f561196d6c'
```

8. Fetch main again???
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force --depth=1 origin main:main
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)        
```

9. Check commits from main to working branch. No difference since working branch is currently identical to main due to steps 5 & 7.
```
  /usr/bin/git rev-list --right-only --count main...93bc15a6-9be3-4044-a821-f9f561196d6c
  0
```

10. Fetch insights-update and switch to it
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force --depth=10 origin insights-update:refs/remotes/origin/insights-update
  remote: Enumerating objects: 178, done.        
  remote: Counting objects: 100% (144/144), done.        
  remote: Compressing objects: 100% (50/50), done.        
  Receiving objects: 100% (102/102), 497.32 KiB | 4.32 MiB/s, done.
  Resolving deltas: 100% (74/74), completed with 25 local objects.
  Pull request branch 'insights-update' already exists as remote branch 'origin/insights-update'
  /usr/bin/git checkout --progress insights-update --
  Switched to branch 'insights-update'
  Your branch is up to date with 'origin/insights-update'.
```

11. Check commits between main & insights-update. Contains 4 commits only on insights-update
```
  /usr/bin/git rev-list --right-only --count main...insights-update
  4
  /usr/bin/git diff --quiet insights-update..93bc15a6-9be3-4044-a821-f9f561196d6c
```

12. Reset insights-update to working branch which is currently main (the target branch), so after this point the source & target branches are the same
```
  Resetting 'insights-update'
  /usr/bin/git checkout --progress -B insights-update 93bc15a6-9be3-4044-a821-f9f561196d6c --
  Reset branch 'insights-update'
  Your branch is behind 'origin/insights-update' by 4 commits, and can be fast-forwarded.
    (use "git pull" to update your local branch)
```

13. Check right side commits between origin/insights-update and the new insights-update (same as main). No commits.
```
  /usr/bin/git rev-list --right-only --count origin/insights-update...insights-update
  0
```
13. Check left side commits between origin/insights-update and the new insights-update (same as main). 4 commits.
```
  /usr/bin/git rev-list --left-only --count origin/insights-update...insights-update
  4
```
14. Check commits from main to insights-update. No change since these both point to the same commit after step 12.
```
  Updated branch 'insights-update'
  /usr/bin/git rev-list --right-only --count main...insights-update
  0
  /usr/bin/git rev-parse main
  99d13eeb4feca855c1f03885bc0cb239ef84a212
  /usr/bin/git -c core.quotePath=false show --raw --cc --no-renames --no-abbrev --format=%H%n%T%n%P%n%G?%n%s%n%b%n###EOB### 99d13eeb4feca855c1f03885bc0cb239ef84a212
  /usr/bin/git rev-parse insights-update
  99d13eeb4feca855c1f03885bc0cb239ef84a212
```
15. Cleanup
```
  /usr/bin/git branch --delete --force 93bc15a6-9be3-4044-a821-f9f561196d6c
  Deleted branch 93bc15a6-9be3-4044-a821-f9f561196d6c (was 99d13ee).
  /usr/bin/git checkout --progress insights-update --
  Already on 'insights-update'
  Your branch is behind 'origin/insights-update' by 4 commits, and can be fast-forwarded.
    (use "git pull" to update your local branch)
```
16. Check if we should create the pull request
```
  Branch 'insights-update' no longer differs from base branch 'main'
```

The problem appears to be that at step 12 the source branch is reset to the target branch, so at step 14, there are no differences between source and target.

I do not see how a PR would ever be created if we reset the source branch.

workflow.yml

```yaml
name: Create Pull Request on Push to insights-update

on:
  push:
    branches:
      - insights-update # Trigger on pushes to the insights-update branch

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[automated] New insights data'
          body: 'Automated insights data update from push to insights-update.'
          branch: insights-update
          base: main
          sign-commits: true
```
