### ISSUE TITLE
Why is the committer showing up as `actions-user`?

### ISSUE THREAD

**Issue by miparnisari** [peter-evans/create-pull-request#3940]
I have a workflow like this:

```yaml
      - name: "Make commit"
        run: |
          ...
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update generated docs"
          ...
      - 
        uses: "peter-evans/create-pull-request@v7"
        with:
          token: "${{ secrets.PAT_TO_PUSH_TO_DOCS }}"
          path: "docs-repo"
          title: "Auto-generated PR: Update docs"
          body: "This PR was auto-generated by GitHub Actions."
          branch: "auto-update-branch"
```

and I see that the PR gets created correctly, but under the username `actions-user`: https://github.com/actions-user

This is neither the user that made the commit, nor the default user specified in https://github.com/peter-evans/create-pull-request/blob/450b15d522a9a77a845754ffce4e67c55697bc2c/action.yml#L27
