### ISSUE TITLE
Running this project on self-hosted agents

### ISSUE THREAD

**Issue by slashmili** [peter-evans/create-pull-request#397]
### Running self-hosted agents

When I add this action to my workflow which uses self-hosted agent, the step creates PR but it fails with this error:

```
##[error]Unable to process command '::add-path::' successfully.
##[error]Value cannot be null. (Parameter 'path')
```
<img width="1293" alt="Screenshot 2020-06-30 at 21 34 38" src="https://user-images.githubusercontent.com/585764/86169175-82210500-bb19-11ea-9c33-6ae444491271.png">

### Steps to reproduce

Setup an agent and configure `runs-on: self-hoste` to your job. It does work if I run it with `runs-on: ubuntu-latest` config

**Comment by peter-evans** [comment]
Hi @slashmili 

Thank you for this issue report. I'm fairly sure I know why this is happening but I'll need to take some time to reproduce it and find a fix.

For now, I think you might be able to workaround this issue by running the action inside a Docker container on the hosted runner. See the [documentation here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#running-in-a-container).

This is the example in the documentation with `runs-on: ubuntu-latest` changed to `runs-on: self-hosted`. I haven't tested this, but I have a feeling this would work.
```
jobs:
  createPullRequestAlpine:
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - name: Install dependencies
        run: |
          apk --no-cache add git python3
          python3 -m ensurepip

      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
```
