### ISSUE TITLE
Container does not support git-lfs

### ISSUE THREAD

**Issue by qoutland** [peter-evans/create-pull-request#43]
When trying to run this action with a repo that is using git-lfs it errors out with the following error: `This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.`

I tried installing git-lfs python package, which did not work since it must be called using `python3 -m git_lfs` vs the required `git-lfs`.

I will later be submitting a PR to fix this issue, by changing the base image to alpine and installing required packages. Up to you if you want to accept it, but it works for me here:
https://github.com/qoutland/create-pull-request

**Comment by peter-evans** [comment]
I'm happy to accept the changes you proposed in your PR, but did you check out the new multi-platform version I created recently? This doesn't use a container and so `git-lfs` should be in the path already.
According to this documentation, Git Large File Storage is installed by default in virtual environments.
https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions

```
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.2.1-multi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by qoutland** [comment]
I did not actually look into this, but I will check it out tomorrow sometime! Thanks!

**Comment by peter-evans** [comment]
Even if the multi-platform version works fine for you I'm still interested in merging your proposed change to the original container version of this Action. I'm not sure what direction GitHub are going to take to support other platforms and/or Action languages yet, so I'm maintaining both versions for the time being.
See this comment for a bit more background. https://github.com/peter-evans/create-pull-request/issues/40#issuecomment-534377007

**Comment by peter-evans** [comment]
I merged your change and created a new release. Thanks!
```
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
If you have chance, I would appreciate feedback on the `multi` version. I would like to know if it works for repos using `git-lfs`.
