### ISSUE TITLE
Handling uncommitted modification

### ISSUE THREAD

**Issue by mrchief** [peter-evans/create-pull-request#466]
### Subject of the issue

Seems like modified files are not auto committed
![image](https://user-images.githubusercontent.com/781818/88488862-5c432080-cf5e-11ea-8f85-aa341a2b83a0.png)

### Steps to reproduce

```
      - name: Update Changelog.md
        run: |
          echo "Some changes" | cat - ./CHANGELOG.md > ./temp
          mv ./temp ./CHANGELOG.md
          git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: "chore: Update changelog 📚"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ github.ref }}
          title: "chore: Automated PR"
          body: |
            Automated Pull Request 
          labels: |
            release
            automated pr
```

After running everything succeeds but no PR is created.
