### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by skirmess** [peter-evans/create-pull-request#485]
### Resource not accessible by integration

I'm trying to create a pull request in another repo by using a deploy key. The branch is created in the test4-target repository but no pull request is created. This is the output:

```
Pushing pull request branch to 'origin/create-pull-request/patch'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/create-pull-request/patch
  remote: 
  remote: Create a pull request for 'create-pull-request/patch' on GitHub by visiting:        
  remote:      https://github.com/skirmess/test4-target/pull/new/create-pull-request/patch        
  remote: 
  To github.com:skirmess/test4-target.git
   * [new branch]      HEAD -> create-pull-request/patch
##[error]Resource not accessible by integration
```

See: https://github.com/skirmess/test4-src/runs/977322857?check_suite_focus=true

### Steps to reproduce

This is the repository that should get the pull request: https://github.com/skirmess/test4-target
The repository has a read/write deploy key.

This is the repository that runs your action: https://github.com/skirmess/test4-src

It has a secret called UPDATE_KEY, containing the SSH private key in OpenSSH key format.

The used action:
```
name: Update

on: [push]

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: test4-src

      - uses: actions/checkout@v2
        with:
          repository: skirmess/test4-target
          path: test4-target
          ssh-key: ${{ secrets.UPDATE_KEY }}

      - name: update some data
        run: date > test4-target/date.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path:  test4-target
```
