### ISSUE TITLE
Question: how to create PRs (where the workflow is running) with changes from a remote upstream?

### ISSUE THREAD

**Issue by pmalek-sumo** [peter-evans/create-pull-request#516]
### Subject of the issue

I hate to ask it here but I cannot make it work myself and I suppose it's a simple tweak that I'm missing that for some reason is not obvious to me.

I'd like to set up a workflow which would run periodically and check if there are any changes in a remote upstream.
If there are any changes it should create a PR (in the fork = in the repository that the workflow is running) pulling changes from the upstream.

I've managed to write something like this but I keep getting: [gh action link](https://github.com/pmalek-sumo/telegraf/runs/1008680127?check_suite_focus=true)

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules fork upstream-changes:refs/remotes/fork/upstream-changes
  fatal: couldn't find remote ref upstream-changes
  Pull request branch 'upstream-changes' does not exist yet.
  /usr/bin/git checkout --progress -B upstream-changes HEAD
  Switched to a new branch 'upstream-changes'
  /usr/bin/git rev-list --right-only --count master...upstream-changes
  0
  Branch 'upstream-changes' is not ahead of base 'master' and will not be created
```

I'm using `push-to-fork` as I've seen in [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository) 

> Checking out a branch from a different repository from where the workflow is executing will make that repository **the target for the created pull request**

That I **do not want** since I want to create a PR in my repo (where the workflow is running).

---

My workflow that I've managed to write look like this (I want to merge change from https://github.com/influxdata/telegraf to https://github.com/pmalek-sumo/telegraf)

```yaml
name: Create PR from upstream
on:
  schedule:
    - cron: '* * * * *'
jobs:
  create-pr-from-upstream:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout 'influxdata/telegraf'
        uses: actions/checkout@v2
        with:
            repository: 'influxdata/telegraf'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.PAT }}
            push-to-fork: 'pmalek-sumo/telegraf'
            commit-message: Upstream changes
            title: Upstream changes
            body: |
              - Upstream changes

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            base: master
            branch: upstream-changes
```

**Comment by peter-evans** [comment]
Hi @pmalek-sumo 

`push-to-fork` is the wrong feature for what you want to do. I think your use case is similar to [this example](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another). The only difference is that the branch is a remote branch.

Try this workflow:
```
name: Create PR from upstream
on:
  schedule:
    - cron: '* * * * *'
jobs:
  create-pr-from-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/influxdata/telegraf.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Upstream changes
          title: Upstream changes
          body: |
            - Upstream changes

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: upstream-changes
```
