### ISSUE TITLE
[Suggestion] Add option to generate PR from file

### ISSUE THREAD

**Issue by ci010** [peter-evans/create-pull-request#53]
If we can generate the PR from some specific format of file, we can have more dynamic on pull request. Do we have any plan to do this?

**Comment by peter-evans** [comment]
@ci010 Thank you for your suggestion. Please could you explain in more detail about your use case. I'm not sure I understand. Are you referring to the pull request body content that is currently set via `PULL_REQUEST_BODY`? You would like to set this from a file?

**Comment by ci010** [comment]
@peter-evans Kind of. For example, suppose there is a env var named `CONFIG_JSON`. The action will read the config json and overwrite the original setting.

```yml
uses: peter-evans/create-pull-request@v1.4.1
env:
  CONFIG_JSON: some.json
```

And the `some.json`'s content is

```json
{
  "commit_title": "the message could be generated by steps before",
  "pull_request_body": "the content may be generated by steps before",
  "pull_request_title": "the content may be generated by steps before",
  "any_other_setting": "other things"
}
```

**Comment by peter-evans** [comment]
Thank you. That's a really clear explanation of the suggestion.

I'm struggling to think of a new use case this opens up that can't be achieved currently. The configuration for the action is already in a file and committed to the repository. So this seems like we would just be exchanging yaml format for json.

Does this open up a new use case for you? How does this make it "dynamic", as you mentioned in the first post?

Or is it simply that you would prefer to write the config in JSON instead of yaml?

**Comment by greenstatic** [comment]
I think I have the same use case as  @ci010. The problem is that I do not want to statically define the commit title and pull request body in the workflow YAML because it would be generated by a script a step before launching the step containing the `create-pull-request` action. 

I currently do not see a way to accomplish this with the ENV variables since they are not shared between steps. Having the script write a configuration file for the action would support such a use case.

**Comment by peter-evans** [comment]
Ah, thank you @greenstatic. Now I understand the problem behind this suggestion. @ci010, perhaps you could confirm that your intention behind this was to dynamically define configuration parameters for the action.

You can define variables and pass them between steps in GitHub Actions. The following method using `set-output` is the method I would recommend. Note that the step where you define the variables must have an id.
```
on:
  repository_dispatch:
    types: [create-pull-request]
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        run: date +%s > report.txt
      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=pr_title::"[Test] Add report file $(date +%d-%m-%Y)"
          echo ::set-output name=pr_body::"This PR was auto-generated on $(date +%d-%m-%Y) \
            by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_TITLE: ${{ steps.vars.outputs.pr_title }}
          PULL_REQUEST_BODY: ${{ steps.vars.outputs.pr_body }}
```

Since the action is just reading environment variables from the system, you don't actually need to explicitly pass them as long as they exist in the environment. So the following method using `set-env` *also* works, but I think explicitly passing the variables in the previous method is more readable and clear.
```
on:
  repository_dispatch:
    types: [create-pull-request]
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        run: date +%s > report.txt
      - name: Set environment variables
        run: |
          echo ::set-env name=PULL_REQUEST_TITLE::"[Test] Add report file $(date +%d-%m-%Y)"
          echo ::set-env name=PULL_REQUEST_BODY::"This PR was auto-generated on $(date +%d-%m-%Y) \
            by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I will update the documentation to show these methods.
