### ISSUE TITLE
method to override branch to diff against when triggering on a branch push?

### ISSUE THREAD

**Issue by jmhodges** [peter-evans/create-pull-request#54]
I added a specific branch I could push to trigger create-pull-request in my workflow: https://github.com/jmhodges/goreleaseapi/blob/168a1125ece9291a2fb3478e8759abe5af35a4fd/.github/workflows/rebuild_api.yml

So, it seems that create-pull-request will diff against the branch it was pushed into (makes sense!) instead of, say, master. (Unless my configuration is wrong in a way I've missed!)

It'd be nice if I could override the branch that c-p-r diffs against so I can merge in the PRs that it makes from a push to a specific testing branch.

(Or maybe I missed that feature somewhere already?)

**Comment by peter-evans** [comment]
Thanks for raising this issue. This feature doesn't exist at the moment and I'm not sure if I can add it in a safe manner. Essentially, you want to change the base of the pull request from the branch that triggered the workflow to `master`. The problem with changing the base from the currently checked out branch is that `create-pull-request` will have no idea what the base looks like and the pull request creation could fail if there is no diff, for example.

I could add an override environment variable for it and it would probably be safe in your use-case because it looks like the branch `force_rebuild_api` would be the same commit as `master`.

Could I offer an alternative for your `force_rebuild_api` trigger? How about using `on: repository_dispatch` and sending a curl request to the GitHub API to trigger the workflow manually.

You could change your workflow triggers like this:
```
name: Rebuild API when new Go release occurs
on:
  schedule:
    # Do this every 3 hours
    - cron: '* * */3 * *'
  repository_dispatch:
    types: [force-rebuild-api]
```
To trigger the workflow manually call the following. `[username]` is a GitHub username. `[token]` is a `repo` scoped Personal Access Token. The `repo` scoped Personal Access Token can be created at https://github.com/settings/tokens
```
curl -XPOST -u "[username]:[token]" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/jmhodges/goreleaseapi/dispatches --data '{"event_type": "force-rebuild-api"}'
```

If you still feel that you would prefer to override the pull request base, let me know and I'll look into it a bit more to see if I can make it safe.

**Comment by peter-evans** [comment]
@jmhodges I took another look at this and figured out a relatively safe way to override the base. In your case it should be absolutely fine because I imagine there will be little to no difference between `force_rebuild_api` and `master`.

You can try the override with the latest version.
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BASE: master
```

Regardless of whatever branch is currently checked out it will try to checkout the base override in the following way:
1. Stash the local changes
2. Checkout the base branch override
3. Pop the stash
4. Resolve conflicts (if any) in favour of the stashed version
5. (if local changes remain) Create a PR to merge into the overridden base
