### ISSUE TITLE
Create PR from push on a given branch

### ISSUE THREAD

**Issue by funes79** [peter-evans/create-pull-request#544]
### Subject of the issue

I have a question. I configured this action to list on "on push" events on "users" branch. What I would like to know if this action can use the very same branch for PR create or it must use always a new branch to create? I tried to configure the branch parameter and set it to the same branch "users" from where the push is coming, but this resulted in a loss of the original branch (probaly re-create).

So I would like to configure a very simple scenario:
 Every time a change is pushed into my branch, I would like to open a new PR againts master, approve and merge. 

Thanks

**Comment by peter-evans** [comment]
Hi @funes79 

The branch name that you specify in the `branch` input cannot be an existing branch, but what you can do is create and update a third branch which performs the merge. I think [this example](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another) fits your use case.

```
name: Update master from users
on:
  push:
    branches:
      - users
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset master branch with users changes
        run: |
          git fetch origin users:users
          git reset --hard users
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: users-update
```
