### ISSUE TITLE
Can I create PR with runtime generated Name ?

### ISSUE THREAD

**Issue by pawarashish564** [peter-evans/create-pull-request#568]
### All the PR created will have same name
I want to create automated PR with different names as per the certain conditions meet. I have some data to be committed then create a PR . 

Let me know if there is a way to do it ? using this Github action or any Github API

**Comment by peter-evans** [comment]
Hi @pawarashish564 

Sure, this is absolutely possible. Please see this section of the [documentation about dynamic configuration](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#dynamic-configuration-using-variables).

**Comment by pawarashish564** [comment]
thank you @peter-evans .

I tried this but I'm not able to do it .

```yaml
name: PR  Creator
on: push
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: |
          git config user.name 'pawarashish564'
          git config user.email 'pawarashish564@gmail.com'
          date +%s >> fileData.txt
          export num=$(od -An -N2 -i /dev/random)
          git add fileData.txt
          git commit -m "commit $num"
      - name: Create Pull Request
        run: |
          echo ::set-output name=pr_title::"[Test] PR on $(date +%d-%m-%Y) No $(od -An -N2 -i /dev/random)"

        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # commit-message: Update report 
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: ${{ steps.vars.outputs.pr_title }}
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by PR_BOT

          # [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          # assignees: pawarashish564
          # reviewers: pawarashish564
          # team-reviewers: |
            # owners
            # maintainers
          # milestone: 1
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"

```

See my code here. Basically what I am doing is committing some change and them make PR with random name .

Let me know what I have done wrong .

**Comment by pawarashish564** [comment]
Thank you @peter-evans

**Comment by pawarashish564** [comment]
I tried this. but I don't what I have done wrong.
see my code
```yaml
name: PR  Creator
on: push
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo ::set-env name=PULL_REQUEST_TITLE::"[Test] PR on $(date +%d-%m-%Y) No $(od -An -N2 -i /dev/random)"
          echo ::set-env name=PULL_REQUEST_BODY::"This PR was auto-generated on $(date +%d-%m-%Y) \
            by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
      - name: Make changes to pull request
        run: |
          git config user.name 'pawarashish564'
          git config user.email 'pawarashish564@gmail.com'
          date +%s >> fileData.txt
          export num=$(od -An -N2 -i /dev/random)
          git add fileData.txt
          git commit -m "commit $num"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # commit-message: Update report 
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: ${{ steps.vars.outputs.pr_title }}
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by PR_BOT

          # [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          # assignees: pawarashish564
          # reviewers: pawarashish564
          # team-reviewers: |
            # owners
            # maintainers
          # milestone: 1
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"

```

Basically what I'm doing is committing some change then create a PR with random name.
But I am getting this error.
![image](https://user-images.githubusercontent.com/29516182/92904297-618df900-f440-11ea-9590-f575882a3293.png)

Please help. If you want to check the [repo](https://github.com/pawarashish564/Github-actions-bot-tutorial) here.
