### ISSUE TITLE
Create PR on third-party repo?

### ISSUE THREAD

**Issue by samuela** [peter-evans/create-pull-request#577]
### Subject of the issue

Is it possible to create a PR on a repo that is not the repo owning the Action running create-pull-request? To make matters worse, I do not have push access to the repo I'd like to create the PR on, although I do have a fork of the repo.

In other words, I'd like to run this action from repo A, use it to create PRs on repo B that I can't push to, but I do have a repo B_fork.

**Comment by peter-evans** [comment]
Hi @samuela 

You can achieve this with the `push-to-fork` feature. See the [documentation here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork).

This workflow runs in repo A.
```yml
      - uses: actions/checkout@v2
        with:
          repository: repoB-owner/repoB

      # Make changes to pull request here

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MACHINE_USER_PAT }}
          push-to-fork: B_fork-owner/B_fork
```
