### ISSUE TITLE
combine create-pull-request with slash-command-dispatch and preserve ownership

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/create-pull-request#578]
### Subject of the issue

we use create-pull-request in combination with slash-command-dispatch to create pull requests triggered by slash commands.

it would be great if the PR author and commit-author could be set to the user which actually send the chatops command.

atm it seems authorship for the auto-generated commits/pull request is given to the owner of the used access token, instead of the creator of the comment.

### Steps to reproduce

the workflow looks like

```
name: Update clxProductnet

on:
  repository_dispatch:
    types: [update-productnet-command] # triggered by /update-productnet PR comment

jobs:
  updaterepo:
    name: Update clxProductnet
    runs-on: ubuntu-latest

// snip

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v3
      with:
          title: Update clxProductNet
          commit-message: composer update complex/productnet
          token: ${{ secrets.STAABM_TOKEN }}
          branch: create-pull-request/update-clxproductnet-${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

    - name: Create URL to upstream PR
      id: upstream-pr
      run: echo "::set-output name=pr-url::https://github.com/complex-gmbh/myrepo/pull/${{ steps.create-pr.outputs.pull-request-number }}"

    - name: Create comment with link to upstream PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.STAABM_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
            [Created ${{ matrix.repo }} upstream PR][1]
            [1]: ${{ steps.upstream-pr.outputs.pr-url }}
```

as you can see we already tried to define the author and committer, but it seems the `github.actor` in this context is the owner of the PAT
