### ISSUE TITLE
output parameter: pull request url

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/create-pull-request#579]
### Subject of the issue

it would be great it the action would provide a separate output parameter which contains the full url to the created Pull Request.

that would save us from building the url manually which clutters the workflow file.

### Steps to reproduce

see the following workflow, in which we create a comment - which links to the previously created PR - but requires some "ugly" manual url building

```
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v3
      with:
          title: Update clxProductNet
          commit-message: composer update complex/productnet
          token: ${{ secrets.STAABM_TOKEN }}
          branch: create-pull-request/update-clxproductnet-${{ github.actor }}

    - name: Create URL to upstream PR
      id: upstream-pr
      run: echo "::set-output name=pr-url::https://github.com/complex-gmbh/myrepo/pull/${{ steps.create-pr.outputs.pull-request-number }}"

    - name: Create comment with link to upstream PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.STAABM_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
            [Created ${{ matrix.repo }} upstream PR][1]
            [1]: ${{ steps.upstream-pr.outputs.pr-url }}
```
