### ISSUE TITLE
Failing to create pull request: Could not read Username for 'https://github.com'

### ISSUE THREAD

**Issue by adamhowardprice** [peter-evans/create-pull-request#60]
Have you seen errors like this before?

![Screen Shot 2019-10-25 at 10 51 56 AM](https://user-images.githubusercontent.com/602596/67581232-acfac400-f715-11e9-8e42-b6915ed955d8.png)

**Comment by peter-evans** [comment]
I've seen errors like that before and they are usually related to missing authentication. Based on the stack trace I can see where it's throwing this error and I was under the assumption that the token for auth was not necessary at that point. The `GITHUB_TOKEN` is set later in the process. Could you explain more about your use-case and if possible provide your workflow so I can try and reproduce the problem.

You might be able to temporarily work around the issue by adding the following step to your workflow before the `create-pull-request` action runs.
```
      - name: Set auth token
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
```

**Comment by adamhowardprice** [comment]
Can I contact you offline to send you my workflow there?

**Comment by peter-evans** [comment]
Sure. Send it to peterevans.dev@protonmail.com and I'll take a look.

**Comment by peter-evans** [comment]
@adamhowardprice The latest version includes some refactoring of the order in which authentication is set on the checked out repository. It's possible that this will solve your issue.

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
If it doesn't resolve your issue please send me your workflow so I can understand the use case.

**Comment by peter-evans** [comment]
I haven't heard from you so I'll close this issue for now. Please reopen it or send me your workflow if you need further help.

**Comment by HosseinMirzaei47** [comment]
> @adamhowardprice The latest version includes some refactoring of the order in which authentication is set on the checked out repository. It's possible that this will solve your issue.
> 
> ```
>       - name: Create Pull Request
>         uses: peter-evans/create-pull-request@v1.6.0
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> If it doesn't resolve your issue please send me your workflow so I can understand the use case.

I had the same issue. Setting the token as an env variable instead of using the `token` parameter fixed the issue for me ✅ 

```
- name: Create Pull Request
  uses: peter-evans/create-pull-request@v3
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
