### ISSUE TITLE
Passing multiple line output for Pull Request body will not display

### ISSUE THREAD

**Issue by KeisukeYamashita** [peter-evans/create-pull-request#614]
### Subject of the issue

Thank you for your nice action 🎉 

Passing multiple line output from another job to the job for Pull Request body will not display correctly.
Only the first line is displayed like below:

![image](https://user-images.githubusercontent.com/23056537/97004638-54544600-1578-11eb-9d74-cce4c607b462.png)

### Steps to reproduce

**Workflow**

```yaml
name: PR

on:
  push:
    branches:
        - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo output
        id: echo
        run: |
          script/ci/echo.sh
      - name: Create Pull Request1
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.echo.outputs.title }}
          branch: test
          body: "${{ steps.echo.outputs.body }}"
```

**script(script/ci/echo.sh)**

```bash
#!/bin/bash

echo "hello," >> testdata.csv
echo ::set-output name=title::"hello"
echo ::set-output name=body::"$(cat <<EOF
# What

Hello.
My name is KeisukeYamashita
EOF
)"
```

Will cause like this.

![image](https://user-images.githubusercontent.com/23056537/97004521-240ca780-1578-11eb-8d7b-ee43746ad7e5.png)

Is there ideas that I can solve this? Thanks in advance.
