### ISSUE TITLE
PR creation fails due to branch mismatch

### ISSUE THREAD

**Issue by ZacSweers** [peter-evans/create-pull-request#623]
### Subject of the issue

When trying to run this action using `v3`, we get this error

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules origin bot/update-baselines-1605139996:refs/remotes/origin/bot/update-baselines-1605139996
501
  fatal: couldn't find remote ref bot/update-baselines-1605139996
502
  Pull request branch 'bot/update-baselines-1605139996' does not exist yet.
503
  /usr/bin/git checkout --progress -B bot/update-baselines-1605139996 HEAD
504
  Switched to a new branch 'bot/update-baselines-1605139996'
505
  /usr/bin/git rev-list --right-only --count master...bot/update-baselines-1605139996
506
  0
507
  Branch 'bot/update-baselines-1605139996' is not ahead of base 'master' and will not be created
508
  /usr/bin/git branch --delete --force 92aae88b-a252-47d5-9881-4fb45c89e53f
509
  Deleted branch 92aae88b-a252-47d5-9881-4fb45c89e53f (was e633cf034a).
```

### Steps to reproduce

Unfortunately this is in a private repo, but happy to help debug or test things wherever possible!

Our workflow looks like this

```yml
name: Update dependency
on:
  workflow_dispatch:
    inputs:
      coordinates:
        description: 'The dependency coordinates to update'
        required: true
      version:
        description: 'The new version'
        required: true
      reviewers:
        description: 'Comma-separated list of reviewers to add, if any'
        required: false
        default: ''

env:
  COORDINATES: ${{ github.event.inputs.coordinates }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  # Publishes a new version of the target and PR's a version bump back to the repo
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Dependency
        run: ./tooling/scripts/updateDependency.sh gradle.properties ${{ github.event.inputs.coordinates }} ${{ github.event.inputs.version }}

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: <redacted>
          commit-message: 'Update ${{ github.event.inputs.coordinates }} to ${{ github.event.inputs.version }}'
          committer: <redacted>
          author: <redacted>
          title: 'Update ${{ github.event.inputs.coordinates }} to ${{ github.event.inputs.version }}'
          body: 'Updates ${{ github.event.inputs.coordinates }} to ${{ github.event.inputs.version }}. This is an automated PR from https://github.com/<our-repo>/actions/runs/${{ github.run_id }}'
          reviewers: ${{ github.event.inputs.reviewers }}
          labels: 'type:dependency'
          branch-suffix: timestamp
          branch: bot/update-baselines

```
