### ISSUE TITLE
Can't push pull request branch

### ISSUE THREAD

**Issue by aweris** [peter-evans/create-pull-request#633]
### Subject of the issue

Getting error `Pushing pull request branch to 'origin/promote'` after upgrade v3

```
 /usr/bin/git push --force-with-lease origin HEAD:refs/heads/promote
  To https://github.com/<retacted>
   ! [rejected]          HEAD -> promote (stale info)
  error: failed to push some refs to 'https://github.com/<retacted>'
  Error: The process '/usr/bin/git' failed with exit code 1
```

### Steps to reproduce

Not sure if it's reproducible outside of our repo. We're using the `on schedule` action to create image promotion PR's. We only upgraded v3 because of the `The set-env command is disabled.` warnings.

Possibly, create a new branch not exist remotely could reproduces the error.

**Comment by fglaeser** [comment]
Hi @aweris , I have the same problem, after I merged the first PR and delete the branch, the action starts to showing that same message in every run.

**Comment by peter-evans** [comment]
Hi @aweris 

From the error message you provided it appears to be rejecting the push because of the use of `--force-with-lease`. You can see it says `stale info`. My understanding is that this would happen when changes have been made to the remote branch in-between the action fetching the branch and then pushing. Do you have other actions, workflows, or even users that are making commits to the `origin/promote` branch?

It would be helpful to see your entire workflow, just in case the cause is something about the way your workflow is written.

**Comment by aweris** [comment]
Hmm, just I recreated the branches and disabled the auto branch delete. It's working now. it's possible related to the difference between upstream and local. It's possible to solve the issue with `push --set-upstream origin`

**Comment by aweris** [comment]
@peter-evans, we're reusing the branch name for scheduled events for able to keep the system consistent. 

After merging the PR, branch, `origin/promote` deleted and recreated with the next scheduled action.

**Comment by peter-evans** [comment]
> It's possible to solve the issue with `push --set-upstream origin`

Where are you running this? In the workflow?
Please show me your workflow. I want to understand what is happening here and try to reproduce it.

**Comment by aweris** [comment]
I'll try to fetch all git history with new PR. I think it's worth to try

Workflow: 

```
name: scheduled release

on:
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    - cron:  '*/5 * * * *'
      
jobs:
  check-release:
    name: check

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check
        id: check
        run: <retacted>

      - name: Sync
        if: steps.check.outputs.triggered == 'true'       
        run: <retacted>

      - name: Create Pull Request
        if: steps.check.outputs.triggered == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: <retacted>
          title: <retacted>
          body: <retacted>
          branch: promote
          reviewers: <retacted>
          labels: |
            automated
            promote
```
