### ISSUE TITLE
Error: Not Found after pushing branch to repository

### ISSUE THREAD

**Issue by kipply** [peter-evans/create-pull-request#634]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/13735595/99588254-4d262980-29b8-11eb-9c66-1c4fbc01cc0d.png">

Error encountered with v3.5.0

config; 
```
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          path: blobheart-docs-site
          branch: beep
          base: main
          commit-message: Update dependencies
          title: Update dependencies
          branch-suffix: random
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
```
