### ISSUE TITLE
Understanding how this Action should be used

### ISSUE THREAD

**Issue by imsteev** [peter-evans/create-pull-request#640]
### Subject of the issue

Perhaps I misunderstood the API of this action, but it seems like there's some assumptions I made that does not align with how this workflow works.

My use case:

* I want to create a PR from `branch-B` to `branch-A`, where `branch-B` simply contains commits on top of `branch-A`
You can think of this as creating a PR from a development branch into production branch

What this means is that I don't intend on making any commits in the Workflow context itself, and simply want to create a PR

My configuration for this was along the lines of:
```
      - name: Create PR from upstream release branch
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release-branch
          base: master
          token: ${{ secrets.TOKEN }}
```

but this quickly resulted in empty PRs that ended up not being opened because the Workflow attempts to rebase on top of master and thus does not detect that there are changes between `branch` and `base`, when in fact there are changes.

```
  Branch 'release-branch' is not ahead of base 'master' and will not be created
```

How can I use this Action given my use case above? Is it even possible?

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @imsteev 

You can use this action to do what you want to do, yes. I think [this example](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another) will help you.

In your case I think it will look something like this:
```yml
jobs:
  developPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset base branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release-branch
```
