### ISSUE TITLE
Custom Inputs to be returned as Outputs on specific events/statuses of the action

### ISSUE THREAD

**Issue by 000407** [peter-evans/create-pull-request#648]
I have noticed that there are only two outputs at the moment, namely

 1. `pull-request-number`
 1. `pull-request-url`

However, none of these appears to be useful in cases where we would need to get the status of the execution of this action. I think it would be much flexible if we can allow different key/value pairs to be set as output, at different states of the application. I think we can take these key/value pairs as inputs and at particular states of the action, we can set the same to the output. For instance,

 1. Assume an input like
 	```
 	name: Create Pull Request
    id: cpr
    uses: peter-evans/create-pull-request@v3
    with:
    	# ...
    	status_responses:
    		success: <value to be returned>
 	```
 1. When the action completes its execution successfully (`success` state), the same key/value pair can be assigned to the output like
 	```
 	pull-request-number=
 	pull-request-url=
 	status.success=<input value of key status_response.success>
 	```
I think, having something of this sort will be useful, especially in the cases where we need to determine the success/failure (or any other specific event/state) of the action.

### Steps to reproduce

N/A
