### ISSUE TITLE
No such device or address when using workspace_dispatch

### ISSUE THREAD

**Issue by tamj0rd2** [peter-evans/create-pull-request#651]
### Subject of the issue

Here's the output I get from the action:

```
Run peter-evans/create-pull-request@v3
  with:
    token: ***
    commit-message: feat(deps): add support for typescript 4.1.2
    title: Add support for Typescript 4.1.2
    base: master
    branch: bump-ts-version
    committer: GitHub <noreply@github.com>
    author: tamj0rd2 <tamj0rd2@users.noreply.github.com>
    signoff: false
    delete-branch: false
    body: Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
    draft: false
Save persisted git credentials
  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader
  /usr/bin/git config --local --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
  Unset config key 'http.https://github.com/.extraheader'
Determining the base and head repositories
Pull request branch target repository set to tamj0rd2/ncdc
Configuring credential for HTTPS authentication
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  dev
  Working base is branch 'dev'
  /usr/bin/git remote prune origin
  fatal: could not read Username for 'https://github.com': No such device or address
  Error: The process '/usr/bin/git' failed with exit code 128
```

Describe your issue here.

### Steps to reproduce

Here's my yml file. I get the failure if I trigger the workflow through the github ui.

```yml
name: Support latest typescript version
on: [workflow_dispatch]

jobs:
  upgrade:
    name: Upgrade and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - name: Install dependencies
        run: npm ci
      - name: Get current version number
        run: echo "::set-output name=version::$(npx tsc --version | sed 's/Version //g')"
        id: current_version_check
      - name: Install latest ts version
        run: npm i -D typescript@latest
      - name: Get updated version number
        run: echo "::set-output name=version::$(npx tsc --version | sed 's/Version //g')"
        id: updated_version_check
      - name: Install required ts dependencies
        if: ${{ steps.current_version_check.outputs.version != steps.updated_version_check.outputs.version }}
        run: |
          npm i -D --prefix ./black-box-tests/pre-release typescript@latest
          npm i ts-json-schema-generator@latest
      - name: Create pull request
        if: ${{ steps.current_version_check.outputs.version != steps.updated_version_check.outputs.version }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.NCDC_GITHUB_RELEASE_TOKEN }}
          commit-message: "feat(deps): add support for typescript ${{ steps.updated_version_check.outputs.version }}"
          title: Add support for Typescript ${{ steps.updated_version_check.outputs.version }}
          base: master
          branch: bump-ts-version
```

Fail: https://github.com/tamj0rd2/ncdc/runs/1461395546?check_suite_focus=true
