### ISSUE TITLE
The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by jonsage** [peter-evans/create-pull-request#690]
### Workflow using create-pull-request@v3 fails

Recently the `create-pull-request` action has been failing with:

```
The process '/usr/bin/git' failed with exit code 128
```

This is code that was working only a few weeks ago (maybe more recently, but I didn't check over Christmas)...

**UPDATE:** this is the result of changes between **3.5.2** and **3.6.0** https://github.com/peter-evans/create-pull-request/commit/45c510e1f68ba052e3cd911f661a799cfb9ba3a3

GitHub actually provide a further error message within the log:

```console
...

Rebasing commits made to branch 'master' on to base branch 'refs/heads/master' 

/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow --force origin refs/heads/master:refs/heads/master

fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
```

### Steps to reproduce

Not sure, but here is my workflow code that was working when I last used it before Christmas:

```yaml
name: Check for updated gems
on:
  workflow_dispatch:
  push:
  # 3am Mon-Fri (schedule only runs on default branch)
  schedule:
    - cron: '0 3 * * 1-5'
jobs:
  update:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Create a lock file if there isn't one
      # Update the lock file to use latest versions
      # Use same docker environment as build so same version of bundler
      - name: Update gemfile.lock 
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/jekyll:4 /bin/bash -c "chmod 777 /srv/jekyll && ( chmod 777 Gemfile.lock || true ) && bundle lock && bundle lock --conservative --update"

      - name: Create pull request for any changes
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: update-gems
          delete-branch: true
          base: ${{ github.head_ref || github.ref }}
          title: Update gems
          commit-message: Update gems
          labels: update

      - name: Check outputs
        if: steps.cpr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"; exit 1;
```

**Comment by peter-evans** [comment]
Hi @jonsage 

The reason this error occurs is because of the way you are setting the `base` input.

```yml
          base: ${{ github.head_ref || github.ref }}
```
Both of these context properties are in the format `refs/heads/<branch-name>`. It just so happened that the action worked even though it expected just `<branch-name>` for the input. The recent change broke this unintentional "feature."

You should be able to fix your workflow with an extra step like this:

```diff
+     - name: Get base branch
+       id: vars
+       run: |
+         base_ref=${{ github.head_ref || github.ref }}
+         echo ::set-output name=base_branch::${base_ref#refs/*/}

      - name: Create pull request for any changes
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: update-gems
          delete-branch: true
-         base: ${{ github.head_ref || github.ref }}
+         base: ${{ steps.vars.outputs.base_branch }}
          title: Update gems
          commit-message: Update gems
          labels: update
```

**Comment by jonsage** [comment]
Hi @peter-evans 

Thank you, this works now 🥇 

I had thought this was likely to be my fault with that line - I struggled to understand the refs available in the workflow when trying to get the functionality working, but I fiddled and was happy when it worked… but I'd be lying if I said I understood exactly what the various refs were in either GHA or Git itself. I just knew I what I wanted to work.

Thanks for looking at it, and my apologies for raising an issue for something I'd used incorrectly in the first place.

:)

**Comment by peter-evans** [comment]
No problem. Glad to be of help.

**Comment by Mike-E-angelo** [comment]
Gosh, thank you so much to all for posting about this.  Copy/pasting the error message in GOOG pulled this issue up first thing and I was able to resolve it. MUCH LOVE OUT THERE FOR ALL INVOLVED. :)

**Comment by covalentbond** [comment]
Hey @peter-evans I'm also facing the same issue.
I'm not much aware of the GitHub Actions, it would be of a great help if you can please look into it:

## Error:
```
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  master
  Working base is branch 'master'
  /usr/bin/git remote prune origin
  fatal: could not read Username for 'https://github.com': No such device or address
  Error: The process '/usr/bin/git' failed with exit code 128
```

## Steps to reproduce:
Here is the workflow code (**create-pull-request** is present in the bottom of the code)

```
name: Update upcoming events

# Run this workflow 
on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * *" # Every day at 01:00

jobs:
  # Set the job key. The key is displayed as the job name
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: zowe/zowe.github.io
          path: master

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r master/requirements.txt

      # Runs the Script to convert ics to yaml format
      - name: Run ics-to-yml.py
        run: |
          python master/_data/ics-to-yml.py

      - name: Check diff
        run: | #set an environment variable
          if git diff --exit-code; then
            echo "CHANGED=false" >> ${GITHUB_ENV}
          else
            echo "CHANGED=true" >> ${GITHUB_ENV}
          fi

      - name: Create pull request
        if: env.CHANGED == 'true'
        # Creates Pull Request only if there are differences
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./master
          title: Update upcoming events
          labels: automated-build
          commit-message: Update upcoming events

```

For reference here it's the workflow that is failing: https://github.com/zowe/zowe.github.io/runs/2488898952.
Thanks in advance!!
