### ISSUE TITLE
Author of PR not set correctly

### ISSUE THREAD

**Issue by dclong** [peter-evans/create-pull-request#695]
### Subject of the issue
I have a workflow as below. Per my understanding of the doc, the author of the PR should be `dclong` while it is actually github-actions (bot). Did I configure anything wrong? 
```
name: Create Pull Request
on:
  push:
    branches:
      - dev
jobs:
  create_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset main branch with dev changes
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create pull request from dev to main
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge dev into main
          branch: dev
          author: dclong <dclong@users.noreply.github.com>
          assignees: dclong 
```
### Steps to reproduce

1. Create a GitHub repo which has 2 branches main and dev.
2. Update `dclong` to the owner of the repository in the above workflow
3. Create a GitHub action workflow in the repository
4. push changes to the dev branch which will trigger a PR
5. Confirm that the PR is created by github-actions (bot) instead of the owner of the repository
