### ISSUE TITLE
Error: When the repository is checked out on a commit instead of a branch, the 'base' input must be supplied

### ISSUE THREAD

**Issue by aminya** [peter-evans/create-pull-request#707]
### Subject of the issue

Describe your issue here.

I get this issue when I use the action. This was not an issue before.
```
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  fatal: ref HEAD is not a symbolic ref
  /usr/bin/git rev-parse HEAD
  2208d4aa5347981e25a96ebbe0751cd21afb1e46
  Working base is commit '2208d4aa5347981e25a96ebbe0751cd21afb1e46'
  Error: When the repository is checked out on a commit instead of a branch, the 'base' input must be supplied.
```

### Steps to reproduce

```yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update precompile_*.jl file
          title: "Test: Update precompiles"
          labels: Test_SnoopCompile
          branch: "Test_SnoopCompile_AutoPR_${{ github.ref }}"

```

Full job: https://github.com/aminya/CompileBot.jl/blob/2208d4aa5347981e25a96ebbe0751cd21afb1e46/.github/workflows/workflow_ci.yml

**Comment by peter-evans** [comment]
Hi @aminya 

This error occurs because your workflow executes on tag pushes every time you make a release. If you look back in your Actions log history you will see that this error happened every time you released.

The best way to fix it is to prevent the workflow running when tags are pushed. Change your workflow as follows to ignore push events for tags and only execute for branches.
```
on:
  push:
    branches:
      - '**' 
```

**Comment by aminya** [comment]
This happened even when there was no tag creation. See the commit list:

https://github.com/aminya/CompileBot.jl/commits/master

**Comment by peter-evans** [comment]
It's unnecessary to test it on tag pushes because it already ran on the same commit when you pushed to master. See how these runs are the same commit.
![image](https://user-images.githubusercontent.com/18365890/105955853-44d62300-60ba-11eb-9915-ae77f4ffa4bb.png)

**Comment by aminya** [comment]
OK. Thanks. Might be good to add the code to the examples in the readme and a short comment about avoiding using the action on the tags.
```yaml
on:
  push:
    branches:
      - '**' 
```
