### ISSUE TITLE
pull request not created on a different base than default

### ISSUE THREAD

**Issue by Ginxo** [peter-evans/create-pull-request#743]
### Subject of the issue

I have an [flow](https://github.com/Ginxo/droolsjbpm-build-bootstrap/blob/f11fc24ab23dcd24aeb1100c6e2a911ba97d4a4b/.github/workflows/generate_files.yml#L68) which [is creating the expected PR whenever the change is produced on default branch](https://github.com/Ginxo/droolsjbpm-build-bootstrap/runs/2020763052?check_suite_focus=true) but [it's not creating it whenever the change is produced on a different branch](https://github.com/Ginxo/droolsjbpm-build-bootstrap/runs/2020781727?check_suite_focus=true) (the job result is OK, but the PR is not created, you can check `Check Outputs` section).

### Steps to reproduce

1. Create a flow containing these steps

```
      - name: Set branch name
        run: echo "BRANCH_NAME_FLOW=generate_files/$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update build chain files
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.BRANCH_NAME_FLOW }}
          base: ${{ env.GITHUB_REF##*/ }}
          delete-branch: true
          title: '[Build Chain] Update build chain and repository-list files.'
          body: |
            # Update Report
          draft: false
```
2. Add any step to checkout, modify and add any file
3. Trigger the flow by pushing changes to a branch different than default one
