### ISSUE TITLE
Is there any way to use special system environment as title?

### ISSUE THREAD

**Issue by tangcent** [peter-evans/create-pull-request#747]
one step:

```yaml
- name: patch envs
        run: |
          source ./envs/env.sh
          echo "EASY_YAPI_PR_TITLE:"$EASY_YAPI_PR_TITLE
          echo "EASY_YAPI_PR_BODY:"$EASY_YAPI_PR_BODY
```
By this step it is confirmed that the system environment variable `EASY_YAPI_PR_TITLE`&`EASY_YAPI_PR_BODY` existed and has a value.
Then, how can I use them as title and body to create pr?
My config:
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "${{EASY_YAPI_PR_TITLE}}"
          body: "${{EASY_YAPI_PR_BODY}}"
          base: master
          branch: release/stable
          labels: release
```
It is failed:

> The workflow is not valid. .github/workflows/release.yml (Line: 53, Col: 18): Unrecognized named-value: 'EASY_YAPI_PR_TITLE'. Located at position 1 within expression: EASY_YAPI_PR_TITLE .github/workflows/release.yml (Line: 54, Col: 17): Unrecognized named-value: 'EASY_YAPI_PR_BODY'. Located at position 1 within expression: EASY_YAPI_PR_BODY
