### ISSUE TITLE
Action failed on push to tags

### ISSUE THREAD

**Issue by tyankatsu0105** [peter-evans/create-pull-request#75]
I try using "create-pull-request" on actions.
I have a problem.
When I set on tags, action is failed.

https://github.com/tyankatsu0105/sandbox-actions/commit/d79cd8dd910d4ae267c9f9529d2008acb22129e3/checks?check_suite_id=313079464

But when I set on branches, action is succeded.

https://github.com/tyankatsu0105/sandbox-actions/commit/672dff9a62707807a8374696712f30093a81e17b/checks?check_suite_id=313074832

**Comment by peter-evans** [comment]
Hi @tyankatsu0105, thank you for opening this issue.

This is actually expected behaviour, but the action didn't do a good job of explaining why it failed. Pull requests can only be created when the checked out `base` is a branch. Checking out a tag will cause this error because a tag is an invalid base for a pull request. In this case, the `actions/checkout@v1` action checks out `refs/tags/test`.

I've now updated the action to fail gracefully and display the following warning.
<img width="1000" alt="Screen Shot 2019-11-16 at 9 08 37" src="https://user-images.githubusercontent.com/18365890/68984725-21c4a800-0855-11ea-993d-f7427c5a998e.png">

If you have a workflow that contains jobs to handle push events on branches as well as tags, you can make sure that the job where you create a pull request only executes when the `ref` is a branch by using a condition as follows.
```
name: Create Pull Request
on: push
jobs:
  createPullRequest:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      ...

  someOtherJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      ...
```

Please allow me to edit the title of this issue so it can be found easily by other users.

**Comment by peter-evans** [comment]
Closing this issue for now.

**Comment by Mike-EEE** [comment]
I hate to be a stickler but I am of the impression that this is an error, not a warning.  In our case we only want to continue if the file posted to a PR successfully.  Currently it does not seem to be able to do this and we get all green when in fact there is a problem.

It might be best to consider making this a further option `onerror: warning|fail` (or some equivalent) to allow users a bit more control over the behavior of this otherwise incredible action.

The `README` is tops, btw. 👍  I HAVE `README` ENVY. 😆

**Comment by peter-evans** [comment]
Valid point. I'm not sure if I should change this to be an error now as it would be breaking for anyone expecting the current behaviour.

One possible way you could work around this is to check the output variable.

```
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if pull request was created or updated
        if: steps.cpr.outputs.pr_number
        run: echo "PR created or updated"
```

**Comment by Mike-EEE** [comment]
> if I should change this to be an error now as it would be breaking for anyone expecting the current behaviour.

Correct... in the case you consider and pursue a new `onerror` property, its default value would be `warning` to keep everyone who doesn't configure it working as expected. :)

Otherwise, your helpful suggestion works just as well. 👍

**Comment by dusan-dragon** [comment]
@peter-evans Hi Boss thanks for great action.
I am curious why we cannot create PRs from tags? Our use case is that once we publish new release, we would like to generate changes files and create PR for that. At the moment it is not possible. Any ideas how to overcome this?

**Comment by peter-evans** [comment]
@dusan-dragon The reason is that the action needs to be able to commit changes. It can't do that while a tag is checked out. There must be a branch checked out (that also exists on the remote) for the action to work with. There is a slightly longer explanation [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md).

The good news is that I think there is a workaround that might work for your use case. I'm assuming that when you create a new release it is on the `master` branch.
```
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  changeLog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Create change log
        run: <commands to create your change log file>

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
This will override the default `GITHUB_REF` for the event and checkout the `master` branch instead. If you have just tagged the master branch then the commit checked out should be the same as the tag. There is a chance that in between the tag being pushed and checking out the `master` branch in the workflow another commit is made to `master`. As long as that is not a real concern, this workflow should work fine.

**Comment by dusan-dragon** [comment]
Thank you for explanation. Appreciate it.

**Comment by peter-evans** [comment]
I just tested this alternative to the above workflow where it creates a temporary branch on the tag and deletes it afterwards. This makes sure that the checked out commit is the tagged commit.

```
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  changeLog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create tag branch
        run: |
          git config --global user.name 'GitHub'
          git config --global user.email 'noreply@github.com'
          git checkout -b release-${GITHUB_REF:10}
          git push --set-upstream origin release-${GITHUB_REF:10}

      - name: Create change log
        run: <commands to create your change log file>

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master

      - name: Delete tag branch
        run: |
          git push --delete origin release-${GITHUB_REF:10}
```
