### ISSUE TITLE
Creating a PR and pushing multiple commits to that PR

### ISSUE THREAD

**Issue by jakub-pomykala** [peter-evans/create-pull-request#758]
Creating a new PR that creates a new branch and then adds multiple commits to that branch so that the PR picks those changes up.

I have an action that does changes to loads of different files and then moves and renames those files round then creates a PR. However, at the moment it is creating 20 or so PRs because that's how many files it is making changes to. I am wondering if it is possible to create just 1 PR with all those changes in there?

Thanks in advance :)

**Comment by peter-evans** [comment]
Hi @jakub-pomykala 

It's probably possible to do what you want, but it's best if you can show me a workflow or something that you've tried. In general, what I would recommend is making all of your changes during the workflow before creating the pull request. This will add them all to a single commit.

```yml
      - uses: actions/checkout@v2

      # Make all your changes here to the 20 or so files

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

**Comment by jakub-pomykala** [comment]
Hi @peter-evans sorry for such a long reply! here is a some of the action that I am running. 

```
- uses: actions/setup-java@v1
        with:
          java-version: '15' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Run Converter
        run: |
          branchName=${{ github.event.inputs.branch }}
          git init
          mkdir -p xxx/${{matrix.guides.guide}}/
          rm -f xxx/${{matrix.guides.guide}}/xxx
          cd GuideConverter
          mvn compiler:compile
          mvn exec:java -Dexec.args="${{matrix.guides.guide}} ${branchName:11}"
          rm -f xxx
          rm -f xxx
          rm -f xxx
          cd ..
          mv xxx xxx
          rm -rf xxx
          bash xxx
          git add .
          git config --global user.email "xxx"
          git config --global user.name "xxx"
          git commit -m "Updated xxx"
          git checkout --ours xxx
        continue-on-error: true
    
      - uses: peter-evans/create-pull-request@v3
        with:
            title: "To Prod: Change to ALL"
            token: ${{ secrets.XXXX }}
            body: "Updated by github actions."
            branch: "${{matrix.guides.guide}}/prod"
            base: "prod" 
            labels: "RunTests"
        name: Create Pull Request
        continue-on-error: true
```

**Comment by peter-evans** [comment]
So I see that you are running these steps in a job matrix. What I would recommend is to split the job into two. The following is a rough outline of what this would probably look like for your use case. Instead of committing, use the `upload-artifact` action to create an artifact of the changes you have made during each job in matrix. Then in the second `createPullRequest` job, download all the artifacts to reapply all the changes you want to make. Then call `create-pull-request` action once to create a single pull request.

```yml
  convert:
    strategy:
      matrix:
        guide: [guide1, guide2, guide3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Make changes to guide at path xxx/${{ matrix.guide }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.guide }}
          path: xxx/${{ matrix.guide }}

  createPullRequest:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Download all artifacts
      # https://github.com/actions/download-artifact#download-all-artifacts
      - uses: actions/download-artifact@v2
        with:
          path: xxx

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```
