### ISSUE TITLE
Push pull request branches to a fork

### ISSUE THREAD

**Issue by thread-liu** [peter-evans/create-pull-request#765]
### Can't Push pull request branches to a fork

 Error: Repository 'RT-Thread/rt-thread' is not a fork. Unable to continue.

### Steps to reproduce

```
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ github.head_ref }}
          push-to-fork: RT-Thread/rt-thread
          commit-message: rtthread-bot
          committer: GitHub <thread-liu@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.thread-liu.github.com>
          signoff: false
          branch: bot-branch
          delete-branch: true
          title: '[auto pr] rtthread-bot'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: thread-liu
          reviewers: thread-liu
          team-reviewers: |
            owners
            maintainers
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

```

![image](https://user-images.githubusercontent.com/44889940/112427691-f9b45580-8d74-11eb-85a3-f101f7432d50.png)
