### ISSUE TITLE
Error when attempting to execute the process '/usr/local/bin/git'

### ISSUE THREAD

**Issue by micahellison** [peter-evans/create-pull-request#766]
### Subject of the issue

@wren and I recently switched to this action to create PRs for jrnl versions in Homebrew, however it has stopped working this week with an error around executing git. We're having a hard time telling what's wrong, but it appears that it might be trying to access git in an incorrect location.

### Steps to reproduce

See [the GitHub Actions workflow log here](https://github.com/jrnl-org/jrnl/runs/2209697230?check_suite_focus=true#step:8:201).
```
Save persisted git credentials
  /usr/local/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  Error: There was an error when attempting to execute the process '/usr/local/bin/git'. This may indicate the process failed to start. Error: spawn /usr/local/bin/git ENOENT
```

[Here is our workflow file](https://github.com/jrnl-org/jrnl/actions/runs/693518119/workflow) (the PR request is at the very end).

**Comment by peter-evans** [comment]
Hi @micahellison 

In your `release_homebrew` job there is no checkout step. You need to checkout the repository before making changes that you want to pull request.

```yml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```
