### ISSUE TITLE
Create PR branch based on a branch other than `base`

### ISSUE THREAD

**Issue by SackCastellon** [peter-evans/create-pull-request#767]
Is there any way to create the PR branch `branch` based on a different branch other than `base`?

I have a workflow where I need to create a branch `release/x.x` based on the branch `dev` and create a pull request to merge it into `main`.

Something like this:
```
main        ---A-----------F---
                \         /
release/x.x      \     D-E
                  \   /
dev         -------B-C---------
```

However with my current configuration:
```
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
        with:
          ref: dev
          fetch-depth: 0
      - name: 'Build Changelog'
        id: changelog
        [...]
      - name: 'Update version'
        [...]
      - name: 'Create pull request'
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          commit-message: ${{ format('Bump version to {0}', env.VERSION) }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ${{ format('release/{0}', env.VERSION) }}
          base: main
          title: ${{ format('Release {0}', env.VERSION) }}
          body: ${{ steps.changelog.outputs.changelog }}
          labels: 'release'
```

What happen is the following:
```
main        ---A-----F---
               \\   /
release/x.x     \D-E
                 \   
dev         ------B-C----
```

**Comment by peter-evans** [comment]
Hi @SackCastellon 

I think what you want to do is close to this example: https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another

It will look something like this for your use case.
```yml
jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
      # checkout main (with ref is optional because main is the default branch)
      - uses: actions/checkout@v2
        with:
          ref: main

      # reset local main to match dev
      - name: Reset main branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      # make further changes (changelog, etc)

      # (remove the base input so it defaults to main)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/1.0
```
