### ISSUE TITLE
Unable to unlink - Permission denied 

### ISSUE THREAD

**Issue by NickStees** [peter-evans/create-pull-request#783]
### Subject of the issue

I am trying to automate composer updates, using a scheduled action to run 'Composer updates' and then open a new pull request from master for review. But I always get some permission denied errors. 

![2021-04-16_9-54-38](https://user-images.githubusercontent.com/2799150/115035792-ee97a580-9e9a-11eb-9920-4575fcee8749.png)

### Steps to reproduce

```
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2
        with:
          command: update drupal/core-recommended
          dev: yes
          args: --ignore-platform-reqs --with-dependencies
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.NICKS_PAT }}
            commit-message: Update dependencies
            title: Update dependencies
            delete-branch: false
            body: |
              - Dependency updates

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-dependencies
            base: master
```
