### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 128 when create an update PR with base branch having the same name to tag

### ISSUE THREAD

**Issue by tuanchauict** [peter-evans/create-pull-request#789]
### Subject of the issue

I'm trying to apply auto-merge from `main` branch into `alpha-release` branch as [Keep a branch up-to-date with another
](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another). However, I'm getting error with git:

```
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  heads/release/demo-0.0.1
  Working base is branch 'heads/release/demo-0.0.1'
  /usr/bin/git checkout --progress -B 5f8455b4-14ee-49c0-b707-eda7103c511c HEAD
  Switched to a new branch '5f8455b4-14ee-49c0-b707-eda7103c511c'
  /usr/bin/git status --porcelain -unormal
  /usr/bin/git diff --quiet
  /usr/bin/git diff --quiet --staged
  Resetting working base branch 'heads/release/demo-0.0.1'
  /usr/bin/git checkout --progress heads/release/demo-0.0.1
  Note: switching to 'heads/release/demo-0.0.1'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 19c01b1 Try to fix auto pr
  /usr/bin/git reset --hard origin/heads/release/demo-0.0.1
  fatal: ambiguous argument 'origin/heads/release/demo-0.0.1': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: The process '/usr/bin/git' failed with exit code 128
```

### Steps to reproduce

Script: https://github.com/tuanchauict/MonoFlow/blob/19c01b1c33e2135e8fe62d8d7bbc315405bf53bd/.github/workflows/alpha-release-automerge.yml
Full log sample: https://github.com/tuanchauict/MonoFlow/runs/2507239189?check_suite_focus=true

**Comment by tuanchauict** [comment]
Update: It runs successfully with a branch having no `/` like: `alpharelease`

**Comment by peter-evans** [comment]
Hi @tuanchauict 

The problem here is that `release/demo-0.0.1` is not a branch, it's a tag. The `base` input must be a branch.

If you refer back the example, I think you want to do something like this:
```yml
name: Create alpha-release promotion pull request
on:
  push:
    branches:
      - main
jobs:
  alphaReleasePromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: alpha-release
      - name: Reset alpha-release branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: alpha-release-promotion
```
