### ISSUE TITLE
Branch 'X' no longer differs from base branch 'Y'

### ISSUE THREAD

**Issue by florian30491** [peter-evans/create-pull-request#792]
### Subject of the issue

No pull request on GitHub is created when running the workflow. 

### Steps to reproduce

Change content of "main" branch that main branch is different from develop branch.

Manually dispatch a workflow run for develop branch by specifying a version at https://github.com/florian30491/GitFlowActionsTesting/actions/workflows/create_release_branch.yml

The branch main will be updated with the content of develop and no pull request on GitHub will be created.

The expected behavior is that a pull request on GitHub will be created.

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

https://github.com/florian30491/GitFlowActionsTesting

Thank you in advance for you help on this issue.

**Comment by peter-evans** [comment]
Hi @florian30491 

You don't seem to be making any changes during the workflow so there is nothing to pull request. You need to make some changes in between checkout and calling the action.

```yml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

It also might help you to read the documentation and examples to get a better idea of how this action works.
https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md

**Comment by peter-evans** [comment]
Hi @florian30491 

I think what you want to do is described in this example:
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#keep-a-branch-up-to-date-with-another

You don't need to create the branch yourself in the workflow. Let the action do it for you.

Try this workflow:
```yml
name: Create release pull request
on:
  push:
    branches:
      - develop
jobs:
  releasePullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset main branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/v${{github.event.inputs.versionName}}
```
