### ISSUE TITLE
c p r bot clobbers commits to PR when run as cron job

### ISSUE THREAD

**Issue by jamesp** [peter-evans/create-pull-request#845]
### c p r bot clobbers commits to PR when run as cron job
Developer pushes to the create-pull-request branch are being clobbered by create-pull-request running as a cron job.

We have a GHA workflow that updates python dependencies and saves them as a lockfile that is then turned into a PR by create-pull-request.  The workflow runs once a week on a Saturday and pushes to branch `auto-update-lockfiles`.  Commits that we push to the same branch are clobbered the following Saturday by the bot.

I assume this is because CPR, when run as a cron job, is using master:HEAD as the base for the starting point.  There may be an easy and obvious way around this, advice would be welcome.  I think I want something like this perhaps, where `base` is the `auto-update-lockfiles` branch if it exists, or `master` if not.  Is this possible?

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          ...
        branch: auto-update-lockfiles
        base: auto-update-lockfiles || master
```

### Steps to reproduce
See the actions workflow here:
https://github.com/SciTools/iris/blob/master/.github/workflows/refresh-lockfiles.yml

And resulting PR here:
https://github.com/SciTools/iris/pull/4137

Note that the PR 4139 that was merged into this branch has been clobbered by the force push from the bot a few days later.
