### ISSUE TITLE
create-pull-request action updating target branch instead of creating pull request

### ISSUE THREAD

**Issue by CalefiGustavo** [peter-evans/create-pull-request#853]
### Subject of the issue

Pull request is not created and instead the target branch (main) is updated with the current branch ("feature/*).

I'm not fully understanding how to approach the action. 

I need to fire the action (create a PR to main branch) on any push done on my feature branches.

As it stands my configuration is [updating my main branch with the commits of the feature branch](https://github.com/CalefiGustavo/git-flow-teste/actions/runs/883331437).

```
Run peter-evans/create-pull-request@v3
Save persisted git credentials
Determining the base and head repositories
Pull request branch target repository set to CalefiGustavo/git-flow-teste
Configuring credential for HTTPS authentication
Checking the base repository state
Pull request branch to create or update set to 'main'
Configuring the committer and author
Create or update the pull request branch
Pushing pull request branch to 'origin/main'
Branch 'main' no longer differs from base branch 'feature/teste'
Restore persisted git credentials
```

**Comment by peter-evans** [comment]
Hi @CalefiGustavo 

I think this example will help you. What you are trying to do is keep `main` up-to-date with your feature branches by creating pull requests.
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

**Comment by CalefiGustavo** [comment]
It worked, thank you.

**Comment by igortas** [comment]
@peter-evans Can't understand how to make it work the action me neither.
I like just simple PR to be created and nothing more, and me, also getting develop the be rebased on top of my feature branch.
Example:
```
name: Pull Request Action
on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Simple demo
          title: '[Example] Simple demo'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: feature, automated pr
          reviewers: igor
          branch: feature/workflow-demo
```

**Comment by peter-evans** [comment]
@igortas The action expects local changes to exist during the workflow. You don't have any step making changes and so there is nothing to pull request.

Your workflow should look like this, but you are missing the step to actually make changes between checkout and executing the action.
```yml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

What you are trying to do is just make a pull request from an existing branch with changes that you've already made. This action is designed to do much more that, so it's not particularly suitable for what you are trying to do. In your case, you could just call the GitHub API to make a PR using something like [github-script](https://github.com/actions/github-script).

**Comment by CalefiGustavo** [comment]
@igortas I got it to work with the example peter provided, I am using this script.

```
name: Create PR from feature branches
on:
  push:
    branches:
      - 'feature/**'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset feature branch
        run: |
          git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
          git reset --hard ${{ steps.extract_branch.outputs.branch }}
      - name: Create Pull Request
        uses: CalefiGustavo/create-pull-request@v3
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
```
