### ISSUE TITLE
Avoid pulling the full repo when creating a pull request

### ISSUE THREAD

**Issue by tahirmt** [peter-evans/create-pull-request#854]
### Subject of the issue

When using the action to create a pull request from an existing branch, it takes a long time because it seems like the action does a complete git clone with full git history which in my case is 1.5GB so it takes 1-3 minutes for create-pull-request to finish creating a pull request. 

Is there a way I can avoid doing this full fetch?

**Comment by tahirmt** [comment]
Hi @peter-evans it's a private repo so I can't share the run with you but here is my workflow

```
name: Update

on:
  push:

jobs:
  update:
    runs-on: macos-10.15

    steps:
      - id: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Create branch
        run: git checkout -b feature-branch

      - name: Make changes
        run: |
          touch file

      - name: Push branch
        run: git push origin feature-branch --force

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          # Using the GITHUB_TOKEN does not trigger CI
          token: ${{ secrets.PAT_TOKEN }}
          branch: feature-branch
          base: develop
          assignees: ${{ github.actor }}
          commit-message: "Updating file"
          title: "Update file"
          body: |
            :crown: *Automatic PR*
          labels: automated
```

**Comment by peter-evans** [comment]
@tahirmt This is definitely not the correct way to use the action and I want to help you fix the workflow. Please could you explain exactly what you are trying to do. It's not clear to me what you are trying to update and when it should happen.

**Comment by tahirmt** [comment]
Basically my workflow automates some code gen from a backend service to update the local schemas. So the "make changes" script would produce some changes which I want to commit to a new branch and create a PR for develop. The workflow works right now but takes longer than needed.

**Comment by peter-evans** [comment]
> changes which I want to commit to a new branch and create a PR for develop

If that's the case, you don't need to create the branch yourself. Let the action do it for you. Checking the branch out is why it's taking so long for the action to run.

```diff
name: Update

on:
  push:

jobs:
  update:
    runs-on: macos-10.15

    steps:
      - id: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'

# Remove this. The action will create the branch.
-     - name: Create branch
-       run: git checkout -b feature-branch

# Just make your changes on top of the develop branch
      - name: Make changes
        run: |
          touch file

# Remove this. The action will do it.
-     - name: Push branch
-       run: git push origin feature-branch --force

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          # Using the GITHUB_TOKEN does not trigger CI
          token: ${{ secrets.PAT_TOKEN }}
          branch: feature-branch
-         base: develop # You don't need this input because the action can work it out from the checked out branch
          assignees: ${{ github.actor }}
          commit-message: "Updating file"
          title: "Update file"
          body: |
            :crown: *Automatic PR*
          labels: automated
```

**Comment by tahirmt** [comment]
@peter-evans thanks. I’ll try it out and let you know.

**Comment by tahirmt** [comment]
I have one question, what would happen if the remote branch already exists?

**Comment by tahirmt** [comment]
Nice! That works! Thanks @peter-evans

**Comment by peter-evans** [comment]
> what would happen if the remote branch already exists?

The action will update it and use it to create/update the pull request.

Glad you got it working. 👍

**Comment by tahirmt** [comment]
@peter-evans I have one additional case where I am currently pushing a new branch. Here is my use case; to update develop from release-candidate whenever there are any pushes to release-candidate. I currently create a new branch from release-candidate and push it up to create the pull request. The action fails if I have no changes in my working directory when I run the action unless if I create the branch and push it up. I need to create the branch in case there are any merge conflicts there is already a branch that anyone can checkout and fix them and push on the same PR.

```
name: Create PR

on:
  push:
    branches:
      - release-candidate

jobs:
  update-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up branch
        run: |
          git checkout -b merge-release-candidate
          push -u origin merge-release-candidate --force

      - name: Create Pull Request
        uses: scorebet/pull-request@v2
        with:
          source_branch: "merge-release-candidate"
          destination_branch: "develop"
          pr_title: "Pull ${{ github.ref }} into develop"
          pr_body: ":crown: *An automated PR*" 
          pr_label: "merge"
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
