### ISSUE TITLE
Error while using PAT: The process '/usr/bin/git' failed with exit code 128 

### ISSUE THREAD

**Issue by ipalaznik** [peter-evans/create-pull-request#869]
### Subject of the issue
I've seen similar issues here. But still, I can't understand why we get failures sometimes. which are gone after manual restart. We're using proper PAT (with `repo` permissions for user with `write` access).
So if the action gets triggered by GitHub, it fails with the mentioned issue:
![image](https://user-images.githubusercontent.com/8269324/121907612-e346e600-cd34-11eb-9073-49303eef976b.png)

But manual restart helps end job is green, which should mean that PAT is fine.

### Steps to reproduce

 Our action is here:
```
on:
  push:
    branches:
      - develop

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.PAT }}"
          branch: develop
          title: Dependabot updates
          body: This is an auto-generated PR with dependabot updates.
```
