### ISSUE TITLE
PR's status remains Open though the commit is merged.

### ISSUE THREAD

**Issue by igovindarajan-fincad** [peter-evans/create-pull-request#876]
### Subject of the issue

The code is committed to dev automatically after all checks are passed with automerge as intended. But then the PR remains in Open state and the branch is not deleted though delete-branch is set to true.

Also, ensured that we have set Automatically delete head branches.

Below is the code snippet that is used. Please advise if we are missing something or it is how it is. Thanks!

### Steps to reproduce

```
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          author: xxx
          base: dev
          branch: xxx
          commit-message: xxx
          committer: xxx
          delete-branch: true
          team-reviewers: |
            xxx
          title: |
           xxx
          token: ${{ steps.xxx.outputs.token }}

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.xxx.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

      - name: Approve Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
```
