### ISSUE TITLE
PR deletes all prev changes pushed to branch

### ISSUE THREAD

**Issue by shaibrown5** [peter-evans/create-pull-request#877]
### Prev changes deleted

In my workflow I create a new branch based off of master, then in a different job I change a file  and push.
when I try to use this action afterwards, no PR is made.

I realised that If I don't push the changes, but only commit them, that The PR is created with those changes. 
But in my case this is not an option, I have to push the changes before hand as i later run script that need the changes from the commit.

is there a way to make this work?

### Steps to reproduce

this is a snippet of my workflow
```

  Create-New-Branch
    runs-on: [ self-hosted]
    outputs:
      branch_name: ${{steps.create-branch.outputs.BRANCH_NAME}}
      model_id: ${{steps.model-id.outputs.NEW_MODEL}}

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          repository: org/repo
          token: ${{secrets.GIT_TOKEN}}
          ref: master

      - name: create and push branch
        id: create-branch
        run: |
          RAND_NUM=$((1 + $RANDOM % 100))
          export NEW_BRANCH_NAME="test-$RAND_NUM-`date '+%F'`"
          git checkout -b $NEW_BRANCH_NAME origin/master
          git push -u origin $NEW_BRANCH_NAME
          echo "::set-output name=BRANCH_NAME::$NEW_BRANCH_NAME"


  Runtest:
    needs: [Create-New-Branch]
    runs-on: [ self-hosted]

    steps:
      - name: Checkout to new branch
        uses: actions/checkout@v2
        with:
          repository: org/repo
          token: ${{secrets.GIT_TOKEN}}
          ref: ${{needs.Create-New-Branch.outputs.branch_name}}

      - name: Change config file and push
        run: |
          python ${{github.workspace}}/config_updater.py
          git add ${{github.workspace}}/config.json
          git commit -m "updated"
          git push
        
      - another job that runs script
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GIT_TOKEN}}
          path: ${{github.workspace}}
          commit-message: updated model id 
          branch: ${{needs.Create-New-Branch.outputs.branch_name}}
          delete-branch: false
          base: master
          title: 'Updated model id in config file '

```

**Comment by peter-evans** [comment]
Hi @shaibrown5 

I'm not quite sure what you are trying to do, but in the majority of cases you shouldn't need to create a branch. The action will do that for you.

Try and simplify what you want into this format:
```yml
      # Don't add ref to this. Just leave it to checkout the default branch (in your case, master)
      - uses: actions/checkout@v2

      # Make changes to pull request here (Do not git push them)
      - name: Change config file
        run: |
          python ${{github.workspace}}/config_updater.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: my-branch-name
```
