### ISSUE TITLE
Create pull request for existing commits

### ISSUE THREAD

**Issue by dkirrane** [peter-evans/create-pull-request#878]
### Subject of the issue

I have a Dev -> Stage -> Prod workflows.
When Stage workflow passes I want to automatically create a PR from `main` branch into `production` branch

### Steps to reproduce

I've tried following
```
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GIT_HUB_TOKEN }}
            commit-message: Stage passed
            branch: main
            base: production
```

But I hit
```
Run peter-evans/create-pull-request@v3
Save persisted git credentials
Determining the base and head repositories
Restore persisted git credentials
  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  fatal: --local can only be used inside a git repository
```
