### ISSUE TITLE
V2-alpha Github committer default is wrong

### ISSUE THREAD

**Issue by aminya** [peter-evans/create-pull-request#88]
Github committer becomes Github Actions instead of the user by default.

https://github.com/aminya/Juno.jl/pull/4 

[workflow](https://github.com/aminya/Juno.jl/blob/8c2e555b136ba7c5f053e5bfa7b1da0d4e431495/.github/workflows/SnoopCompile.yml#L31-L39)

vs
https://github.com/aminya/Juno.jl/pull/3 

[workflow](https://github.com/aminya/Juno.jl/blob/ba6db69f18853f4b98c7c750e646595efeeccc3e/.github/workflows/SnoopCompile.yml#L31-L40)

**Comment by peter-evans** [comment]
Hi @aminya 

Thanks for trying out `v2-alpha`. This is actually a deliberate change that I forgot to mention in [this comment](https://github.com/peter-evans/create-pull-request/issues/82#issuecomment-569236164) (now updated). By default the action will now make commits that appear to be committed by the GitHub Actions bot user. The original logic for trying to determine what the user should be was not very well thought out and I think it makes more sense to default to the bot user and override the defaults explicitly with the `committer` and `author` inputs.

Additionally, the names of the internal environment variables have changed. Please use inputs with the `with` style instead of `env`.

In your case, you can get the original behaviour with the following settings. (Replace `your-email@address.com` with the email address you use in git config.)
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2-alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update precompile_*.jl file
          committer: Amin Yahyaabadi <your-email@address.com>
          title: '[AUTO] Update precompile_*.jl file'
          labels: SnoopCompile
          branch: create-pull-request/SnoopCompile
```

Please be aware that the `v2-alpha` version may stop working at some point when `v2` is promoted or released.

**Comment by peter-evans** [comment]
Promoted to beta today. Please use the following.

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2-beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update precompile_*.jl file
          committer: Amin Yahyaabadi <your-email@address.com>
          title: '[AUTO] Update precompile_*.jl file'
          labels: SnoopCompile
          branch: create-pull-request/SnoopCompile
```
