### ISSUE TITLE
The format of '' is not a valid GitHub repository URL

### ISSUE THREAD

**Issue by KiloOscarSix** [peter-evans/create-pull-request#885]
### Subject of the issue
Morning,
New to Github actions so apologies if I'm doing something stupid, however after trying to use your "create-pull-request" action to automate keeping a branch up to date with another branch I have ran into an error.
```
create_pull_request
The format of '' is not a valid GitHub repository URL
```

Code:
```
name: 'Development Action'

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Automatic Pull Request'
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: PAT TOKEN HERE
          commit-message: 'Automated Pull Request'
          branch: main
          title: 'Development Changes'
          body: 'Please make sure all reviewers verify the changes.'
          reviewers: hivemods, Condy-jpg, KiloOscarSix
```

Any help solving this issue or will be greatly appriciated.

**Comment by peter-evans** [comment]
Hi @KiloOscarSix 

You need to checkout the repository and make some changes before executing the action. Otherwise there is nothing for the action to work with.

```yml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

> to automate keeping a branch up to date with another branch

Please see [this example](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another) in the docs.
