### ISSUE TITLE
create-pull-request@v3.4.1 doesn't trigger other workflows on: pull_request

### ISSUE THREAD

**Issue by CreepyGnome** [peter-evans/create-pull-request#899]
### Subject of the issue

We have a workflow that is triggered by on `pull_request` branches to `develop` and it works great for all PR's developers manually create. However our automated PR's created by `create-pull-request@v3.4.1` don't seem to trigger any other workflows that have a trigger on `pull_request`.  This doesn't seem right as it created a pull request yet some how it is doing it in a way that does not actually set off any triggers when it does.

We really need PR's created by `create-pull-request@v3.4.1` to work just like any other PR that is created, including trigging other workflow actions.

### Steps to reproduce

1. Create a workflow that has a trigger on `pull_request` branches to `develop`
2. Create a manual PR and verify this workflow is triggered
3. Create another automated one using `create-pull-request@v3.4.1` that creates a PR to `develop` when lets say a specific special branch gets push to
4. Do what is needed to trigger the automated to verify it at least gets triggered
5. Check to see if the workflow created in  # 1 was triggered, and it should not have been

Here is the yaml  we use for creating the automated PR 
```yaml
- name: Create Pull Request
  uses: peter-evans/create-pull-request@v3.4.1
  with:
    branch: reconcile-${{ steps.extract_branch.outputs.branch }}
    base: develop
    title: Reconcile ${{ steps.extract_branch.outputs.branch }} to develop
    body: This is an automated pull request created to reconcile `${{ steps.extract_branch.outputs.branch }}` branch to `develop`
```  
NOTE: 
I am going to try to get permission to change it to use `create-pull-request@3` to try to use the latest version, however I didn't see any thing specific in the release notes that would give me any hope that this would work, and not sure when I will be able to even try it yet. I will update once I have with the results though.
