### ISSUE TITLE
remote: Repository not found.

### ISSUE THREAD

**Issue by jwickard** [peter-evans/create-pull-request#925]
Github action fails when pushing the pull request.

Github action seems to be working as intended, In the output logs I'm modifying a release properties the changes are getting picked up and commit to the branch in the workflow but it seems to fail when trying to push the branch up to the repository.

My GHA config:

```
steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # submodules: True
          token: ${{ secrets.NOT_DEFAULT_TOKEN }}

      # this will read current version from properties file.
      - name: Generate versions
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version'
          value: ${{ env.NEXT_VERSION }}
          
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.NOT_DEFAULT_TOKEN  }}
          branch: 'release-candidate-${{ env.NEXT_VERSION }}'
```

Output: 

Everything seems to operate as expected, write properties action modifies version and this is picked up by the create pull request action, but it seems to fail when pushing the branch to remote.

```
Pushing pull request branch to 'origin/release-candidate-0.0.2'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/release-candidate-0.0.2
  remote: Repository not found.
  fatal: repository 'https://github.com/novu/jwickard-temp-gha-repo/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```
