### ISSUE TITLE
How to skip git hooks?

### ISSUE THREAD

**Issue by cawa-93** [peter-evans/create-pull-request#935]
When creating a commit, the git tries to run the hooks. However, in this my CI case, I want to skip all hooks as well as using `--no-verify`. How can i do this using your action?

**Comment by peter-evans** [comment]
Hi @cawa-93 

Have you tried disabling the hooks in a step before the action runs? There are a few ideas I found [here](https://stackoverflow.com/questions/35997624/how-to-disable-git-hooks-for-security-reason/50866196#50866196) that might help.

```yaml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      # Disable git hooks
      - run: rm -rf .git/hooks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

Alternatively, you can [make your own commits](https://github.com/peter-evans/create-pull-request#controlling-commits) with `--no-verify` before the action runs. That might allow the action to continue without running hooks, but I'm not sure. Let me know if you test it.
