### ISSUE TITLE
Not git project found despite checking it out

### ISSUE THREAD

**Issue by nkaplatt** [peter-evans/create-pull-request#950]
### Subject of the issue

Getting `Error: The format of '' is not a valid GitHub repository URL` despite checking out and interacting with the git project at the beginning of the workflow.

Example of what the workflow is doing:

```
name: Generate config files

on:
  workflow_dispatch:
    inputs:
      <inputs defined>

jobs:
  generate_files:
    name: Generate files & open pr
    runs-on: [self-hosted]
    container: docker.io/python:slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate files
        run: python .github/scripts/make-new-changes.py
        env:
           <envs mapped to inputs>

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
```

For some reason between steps 2 and 3 the container seems to loose all knowledge of the git project/ directory as I interact with it in step 2 but in step 3 it doesn't exist ```
  /usr/bin/git config --local --get remote.origin.url
  fatal: --local can only be used inside a git repository
  Error: The format of '' is not a valid GitHub repository URL```

Not sure if it has any material impact (it shouldn't) but we only use this workflow with the dispatch cmd

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @nkaplatt 

It's difficult to say what could be causing this, but my guess is that whatever is happening in step 2 is affecting the checked out repository. You can try running the same git command as the action just on its own as in the example below. It will likely fail in the same way, and then you can debug step 1/2 to figure out what is happening.

```
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate files
        run: python .github/scripts/make-new-changes.py
        env:
           <envs mapped to inputs>

      - run: git config --local --get remote.origin.url
```
