### ISSUE TITLE
[V1] No matching distribution found for GitPython===3.0.5

### ISSUE THREAD

**Issue by darmawanalbert** [peter-evans/create-pull-request#96]
### Subject of the issue

I am using `create-pull-request@v1`. Until yesterday evening, it works just fine. 

<img width="1308" alt="Before" src="https://user-images.githubusercontent.com/12585587/72588224-32170300-392a-11ea-9045-d3e3b928b80b.png">

Starting from today, suddenly I got error: `No matching distribution found for GitPython===3.0.5`.

<img width="1289" alt="After" src="https://user-images.githubusercontent.com/12585587/72588223-32170300-392a-11ea-8964-369c999c1d6f.png">

Any idea on how to solve this? I didn't change any config from my part and already try to rerun the action 🙇 Is it expected for me to use v2 instead?

**Comment by peter-evans** [comment]
Thanks for this report. I've just checked and it affects `v2` as well.
I've not touched any code recently so it must be some dependency that is causing the problem. Trying to figure this out...

**Comment by peter-evans** [comment]
Figured out the problem. They removed Python v3.8.0 from the GitHub Actions tool cache. I'm not sure why yet, but it doesn't exist anymore. I've hotfixed `v2` by updating to Python v3.8.1.

**Comment by peter-evans** [comment]
Hotfixed `v1`. Please let me know if the issue is fixed for you.

I recommend updating to `v2`. There is a brief guide to the changes [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md).

**Comment by matilote** [comment]
I am experiencing same issue, tried with v2.1.1 version, but the problem persists.

**Comment by peter-evans** [comment]
@matilote All [my tests](https://github.com/peter-evans/create-pull-request-tests/pulls) are working fine on `v2` now. Could you share your workflow so I can investigate further.

**Comment by matilote** [comment]
@peter-evans sure, I've just changed cpr to v2, same result.

```
name: Update Manifest file

on:
    repository_dispatch:
      types: dappnode_update

jobs:
  dappnode-update:
    name: Update Manifest file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cloning nethermind repo and fetching latest tag
      run: |
        git clone https://github.com/NethermindEth/nethermind.git
        cd nethermind/ && git describe --tags > git-tag
    - name: Updating package and Nethermind versions
      run: |
        GIT_TAG="$(tail nethermind/git-tag)"
        VER="$(sed -n '3p' dappnode_package.json)"
        VERSION=${VER:14:-2}
        VERSION_UPDATED="$(./semver-update.sh patch $VERSION)"
        sed -i "3s/.*/  \"version\": \"${VERSION_UPDATED}\",/" dappnode_package.json
        sed -i "4s/.*/  \"upstreamVersion\": \"v${GIT_TAG}\",/" dappnode_package.json
        sed -i "5s/.*/    image: 'nethermind.public.dappnode.eth:${VERSION_UPDATED}'/" docker-compose.yml
        rm -rf nethermind/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update manifest
        body: |
          Manifest file has been updated.
          - Files included - dappnode_package.json
          - Auto-generated by [create-pull-request][1]
          [1]: https://github.com/peter-evans/create-pull-request
        title: 'Updating Manifest file'
        labels: manifest
        author-name: github-actions[bot]
        author-email: 41898282+github-actions[bot]@users.noreply.github.com
        committer-name: GitHub
        committer-email: noreply@github.com
        branch: manifest-update
        branch-suffix: short-commit-hash
        base: master
    - name: Checking Outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
```
