### ISSUE TITLE
Can't create PRs or use configured token

### ISSUE THREAD

**Issue by evan-forbes** [peter-evans/create-pull-request#965]
### Subject of the issue
I'm trying to use a github action that creates a PR from an upstream repo. I get the error
```
 /usr/bin/git symbolic-ref HEAD --short
  master
  Working base is branch 'master'
  /usr/bin/git remote prune origin
  fatal: could not read Username for 'https://github.com': No such device or address
```

I've seen this error in already closed issues, but they usually have to do with creating a PR from after `on_pull`, and per the examples provided in this repo, I knwo github doesn't let us do that. Here I'm attempting to create a PR on a schedule or when manually ran, so I would expect it to work. I have a key configured with repo read and write rights, `PULL_UPSTREAM`, but when I check to see if the key was ever used, it says "never used". It feels like I'm missing something simple, but has driven me up the wall trying to figure out exactly what. Worse yet, it worked one time [last week](https://github.com/evan-forbes/tendermint/pull/5) but I can't get it to work again!

here's the action
```yml

name: Pull detached upstream from tendermint/tendermint


on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 1,4'
jobs:
  pull-from-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/tendermint/tendermint.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PULL_UPSTREAM }}
          commit-message: Upstream changes
          title: Upstream changes
          body: |
            - Upstream changes

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: upstream-changes

```
also, the repo permissions are set to allow all actions, and to be able to read and write. 

When I change the token to GITHUB_TOKEN, I get a different error
```
/usr/bin/git push --force-with-lease origin HEAD:refs/heads/upstream-changes
  To https://github.com/evan-forbes/tendermint
   ! [remote rejected]     HEAD -> upstream-changes (refusing to allow a GitHub App to create or update workflow `.github/workflows/lint.yml` without `workflows` permission)
  error: failed to push some refs to 'https://github.com/evan-forbes/tendermint'
  Error: The process '/usr/bin/git' failed with exit code 1
```
### Steps to reproduce

- create a fork
- run the above action on the forked repo
