### ISSUE TITLE
'pull-request-operation' output is empty after force-update

### ISSUE THREAD

**Issue by henrahmagix** [peter-evans/create-pull-request#972]
### Subject of the issue

`steps.cpr.outputs.pull-request-operation` is empty string when a pull-request is updated, when I was expecting it to `== 'updated'`. This happens when the workflow is run a second time, so the `branch` already exists, and also the pull-request created in the first run, and this action is run on the base branch so it force-updates the pull-request.

### Steps to reproduce

Define a workflow as below, run it twice, then check the printed outputs in the action logs.

```yaml
name: Reproduce empty pull-request-operation output

on:
  workflow_dispatch:

jobs:
  reproduce_bug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "something" > new_file.txt

      - name: Create a new PR with the changed files and untracked files committed
        uses: peter-evans/create-pull-request@v3.10.1
        id: cpr
        with:
          # A consistent branch name will ensure the first run will create a PR, and every subsequent run will force-update
          # the created PR, so we don't create hundreds of duplicate PRs.
          branch: my-workflow-created-branch
          commit-message: My commit message
          title: My commit message
          body: |
            This is an auto-generated pull-request by a github action.

      - name: Print outputs
        run: |
          echo "pull-request-number:    '${{ steps.cpr.outputs.pull-request-number }}'"
          echo "pull-request-url:       '${{ steps.cpr.outputs.pull-request-url }}'"
          echo "pull-request-operation: '${{ steps.cpr.outputs.pull-request-operation }}'"
```

#### Expected

First run:
```
pull-request-number:    '2203'
pull-request-url:       'https://github.com/my_org/my_repo/pull/2203'
pull-request-operation: 'created'
```
Second run:
```
pull-request-number:    '2203'
pull-request-url:       'https://github.com/my_org/my_repo/pull/2203'
pull-request-operation: 'updated'
```

#### Actual
First run:
```
pull-request-number:    '2203'
pull-request-url:       'https://github.com/my_org/my_repo/pull/2203'
pull-request-operation: 'created'
```
Second run:
```
pull-request-number:    '2203'
pull-request-url:       'https://github.com/my_org/my_repo/pull/2203'
pull-request-operation: ''
```
