### ISSUE TITLE
Create a PR from a fork repo

### ISSUE THREAD

**Issue by manhdung20112000** [peter-evans/create-pull-request#973]
### How to create a PR into the base repo from a fork repo
Hi, I try to set up a GitHub action on the base repo that triggers every time forked repos create a new branch.

My scenario is the base repo have a lot of  `branch` that are created by contributors, the thing is these branch cannot share between them. Therefore, I forced them to fork the base repo, and they were only able to push their code into the forked repo.

I was able to PR each time a new branch is release in the base repo.
*Note: This action is trigged from the base repo*

```yaml
on: create
jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Reset current branch
        run: |
          git fetch origin ${{ github.ref }}:${{ github.ref }}
          git reset --hard ${{ github.ref }}
          
      - name: Create Pull Requestf
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update
          labels: automated pr
          assignees: ${{ github.actor }}
          branch: ${{ github.ref }}
          body: >
            📄 Submitted by ${{ github.actor }}

```

Could you help me with this, really appreciate that 🙏
