### ISSUE TITLE
Build is not triggered after the pull request

### ISSUE THREAD

**Issue by karim007** [peter-evans/create-pull-request#988]
Hi, 
I have a workflow that is triggered when a pull request is made on my main branch.  However, when the pull request is successfully merged on my main branch the build is not triggered. 

My dev workflow  that makes the pull request
```
- name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: merging dev into main
          title: merging dev into main
          base: main
```

My main workflow that must be triggered after the pull request
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

Many thanks in advance for your help
